### ISSUE TITLE
typings/text is lacking index.d.ts

### ISSUE THREAD

**Issue by tve** [Moddable-OpenSource/moddable#1014]
**Description**
The `typings/text` directory is lacking a blank `index.d.ts` file like all other directories in `typings` have. This leads to an error in vscode when using a `tsconfig.json` file in one's project that has a `typeRoots` pointing to the `moddable/typings` dir: "Cannot find type definition file for 'text'."

**Comment by phoddie** [comment]
Thanks for the report. Since you seem to know how to fix this, would you mind providing a PR?
