### ISSUE TITLE
Fail to build with Pico SDK 1.5.0

### ISSUE THREAD

**Issue by stc1988** [Moddable-OpenSource/moddable#1031]
**Moddable version:** 3.7.0
**Build environment:** macOS
**Target device:** pico

**Steps to Reproduce**
1. [Setup pico environment](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/pico.md#macos-setup).
2. `cd cd $MODDABLE/examples/helloworl`
3. `mcconfig -d -m -p pico`

```
make: *** No rule to make target `/Users/satoshi/.local/share/pico/pico-sdk/src/rp2_common/cyw43_driver/cyw43_bus_pio_spi.pio', needed by `/Users/Satoshi/Projects/moddable/build/tmp/pico/debug/helloworld/cyw43_bus_pio_spi.pio.h'.  Stop.
```

**Other information**
In current master branch(1.5.0),  [src/rp2_common/cyw43_driver](https://github.com/raspberrypi/pico-sdk/tree/1.5.0/src/rp2_common) is not exists.

**Comment by phoddie** [comment]
Thank you for the report. We'll take a look.

**Comment by stc1988** [comment]
Would it be better to fix below setup instructions  on [documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/pico.md) ?

from 
```
git clone -b master https://github.com/raspberrypi/pico-sdk
git clone -b master https://github.com/raspberrypi/pico-examples
```

to
```
git clone -b 1.4.0 https://github.com/raspberrypi/pico-sdk
git clone -b sdk-1.4.0 https://github.com/raspberrypi/pico-examples
```

**Comment by phoddie** [comment]
We would prefer to use the latest SDK. We have been working on support for that it is getting close.

Thank you for posting the temporary instructions here for developers who are blocked during this transition.

**Comment by phoddie** [comment]
I should have been a little more precise above. It is a good idea to pin to a release of the Pico SDK & tools. That will avoid future problems. I just didn't want to pin to 1.4 with our update to 1.5 pending. The Pico set-up instructions now pin to [1.5.0](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/pico.md#macos-setup) .
