### ISSUE TITLE
XS takes too long to define regular expressions in a loop

### ISSUE THREAD

**Issue by ayuan0828** [Moddable-OpenSource/moddable#1048]
**Description**:

As shown in the following results,when running the following test cases to use the ``do-while`` loop to define regular expressions, xs spent a lot of time, as did when I tried to use the ``for`` loop; But to complete the same work, hermes only used a little time. I don't know what caused this, can you tell me?

**Environment**：

```
Ubuntu 18.04 x86_64
```

**JS Information**:
XS:

```
Moddable SDK 3.7.0
```

Hermes:

```
v0.12.0
```

**Testcase**:

```public class Test {
var func = function() {
	var index = 1;
	do{
		index++;
		var re = /\t66EKZPb9ZjErsgZpMO8hrvs9gSOIrWb8a7OiNH6ylgnSovuXjKZGHyEDywxBzvzucleEdRWHhe0uLmWBoYvZ5SYdiShZcwrJSm4b?/;
	} while(index<100000);
};
func();
```

**Time of XS **:

```
4247ms
```

**Time of Hermes**:

```
12ms
```

**Comment by phoddie** [comment]
Hello. We see reports like yours with synthetic performance tests from time-to-time. They tend to arrive in clusters. For example, see #1043. They are posted to repositories for various JavaScript engines. The individuals reporting these synthetic issues have very little history on GitHub and none elsewhere. My best guess is that they are a result of an assignment for a class.
