### ISSUE TITLE
Build errors on macOS Mojave + Xcode 10.1

### ISSUE THREAD

**Issue by kimio-kosaka** [Moddable-OpenSource/moddable#106]
1. I tried to build xsbug on mac.
1. my develop environment is 
    macOS ver.10.14.1 Mojave
    Xcode Ver.10.1(10B61)
1. Build errors  are follows.
--- build messages----
\$ make
.....
(many messages)
.....
make -f serial2xsbug.mk
\# serial2xsbug debug : cc serial2xsbug.c
\# serial2xsbug debug : cc serial2xsbug
make -f simulator.mk
\# simulator debug : cc main.m
\# simulator debug : cc simulator
**xcode-select: error: tool 'ibtool' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make[1]: *** [/Users/kim/Projects/moddable/build/bin/mac/debug/Screen Test.app/Contents/Resources/English.lproj/main.nib] Error 1
make: *** [debug] Errr 2**
\$

1. So, I tried follows
\$ sudo xcode-select -s /Applications/Xcode.app/Contents
\$ make clean
\$ make
1. The build was completed.
1.  Is this build method correct?

**Comment by mkellner** [comment]
Hello, if your build completes and runs, then yes, I believe you've got it.

[This link](https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error/17980786#17980786) shows a similar question and answer.

**Comment by mkellner** [comment]
If you have any other problems with this, please reopen.
