### ISSUE TITLE
A possible performance problem with key value pair definitions in xs

### ISSUE THREAD

**Issue by ayuan0828** [Moddable-OpenSource/moddable#1068]
**Description**:

When I execute the following test case to iteratively define key value pairs, the runtime of xs is very long; However, other js engines require less time to execute the same program, such as hermes or quickjs. I think such a big difference may affect its normal use. Will xs consider optimization?

**Environment**：

```
Ubuntu 18.04 x86_64
```

**JS Information**:

```
Modable SDK 3.7.6
```

**Testcase**:

```public class Test {
var cache = {};
for(i=0;i<100000;i++){
    cache[i]=" ";
}
```

**Time of XS **:

```
1m12.203s
```

**Time of  quickjs **:

```
0m0.039s
```

**Time of Hermes**:

```
0m0.085s
```

**Comment by phoddie** [comment]
Please see #1043
