### ISSUE TITLE
Windows makefile Syntax Error

### ISSUE THREAD

**Issue by NW-Lab** [Moddable-OpenSource/moddable#1078]
**Build environment:**  Windows (Node-Red-MCU Plugin)
**Target device:** m5stick_cplus

**Description**
Build stops with a syntax error.

**Steps to Reproduce**
build.bat generated by plugin.
```
CALL "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars32.bat"
pushd %IDF_PATH%
CALL "C:\Espressif\idf_cmd_init.bat"
popd
@echo mcconfig -d -x localhost:5004 -m -p esp32/m5stick_cplus -r 180
mcconfig -d -x localhost:5004 -m -p esp32/m5stick_cplus -r 180
```

3. See error
![image](https://user-images.githubusercontent.com/8869009/229952633-524e550f-3bb8-411b-b9a3-f376844c2bd6.png)

**Other information**
Looking at the makefile, it looks like C_FLAGS_SUBPLATFORM is not defined.

**Comment by phoddie** [comment]
Oops. Thanks for catching that so quickly. We'll take a look.

**Comment by phoddie** [comment]
Should be better now. Would you please confirm?

**Comment by NW-Lab** [comment]
Now it works.
thank you.

**Comment by phoddie** [comment]
Excellent. Sorry for the trouble.
