### ISSUE TITLE
No possiblity to exchange data with AWS IoT

### ISSUE THREAD

**Issue by PatrykStachura** [Moddable-OpenSource/moddable#1084]
**Build environment:** Linux Ubuntu
**Target device:** NodeMCU ESP32

**Description**
I'm trying to achive exchange data between my IoT device and AWS IoT Core service. There's everything configured as it is described in docs and compared to your examples. I've get Device Cert, CA RSA 2048 Cert & PrivateKey Cert compiled into `.der` files as it is in `Readme.md` file inside aws directory. The thing is i achive an connection, but there's no option to exchange data between service and device. The problem like this (connectivity achive, but no possibility to exchange data) appears when there's something with `Cert`. I stuck a little bit here, because i'm not aware how it is compiled to `.der` files and if that part is working as it suposed to. Would be lovely if i've get some answear from you.  Also, there's no existing function for switch `CONNACK` 

xsbug compiler message:

![obraz](https://user-images.githubusercontent.com/123080214/231124149-3cb3ccad-fcc1-497c-9325-c5e83c436b0c.png)

main code for aws module:
![obraz](https://user-images.githubusercontent.com/123080214/231124898-8eaa35ef-9f0d-4c77-b011-34e33e563cfe.png)

forgive me grammar,
Best regards

**Comment by phoddie** [comment]
Thanks for posting the issue. @dabdoue and I have been discussing the report. We'll get a response to you shortly.

**Comment by dabdoue** [comment]
@PatrykStachura, @phoddie and I believe that your error is with the name of the function you have called `onConnect()` in `SecureClient`. Can you try renaming that function to `onReady()`? The simulator is a quick and easy way to test this as well.

**Comment by PatrykStachura** [comment]
@dabdoue Yes, my friend it was the usage of wrong methond on my side. Can be closed. Appraciate your time!
