### ISSUE TITLE
Modules: Built-ins, user, third party

### ISSUE THREAD

**Issue by rwaldron** [Moddable-OpenSource/moddable#11]
Is there documentation or a roadmap that describes how an ecosystem for built-in, user and third-party modules might work? 

The following is a few observations and some specific questions. For the purpose of this discussion, the term "built-in module(s)" refers to module(s) that ship in this repository, "user module(s)" refers to module(s) that are written for a program by the author of that program (analogous to "file modules" in Node.js) and "third-party module(s)" refers to module(s) that a program author might include in a program, but which came from some outside source (analogous to "anything that goes in `node_modules/`").

- There is no clear differentiation between a built-in, user or third-party module. For example, in Node.js built-in modules and third-party modules are required by module name and user/file modules are required via a filesystem path.
- Where would third-party modules live? Should a convention be created, eg. `xs_modules`?
- Why must user modules be declared in `manifest.json`?
- Why must _all_ modules that are being used in a project be declared in `manifest.json`?

I'm sure I and others will have more questions, but this is a start. Also, I just want to make sure that it's clear that I appreciate everyone's time and also the massive efforts that have gone into this project already—it's really incredible work!

**Comment by dckc** [comment]
I'm struggling to build a mental model of how this works.

The manifest docs consist of the sentence "The modules object describes the necessary modules on all platforms." and a short example.

If you find inspiration to elaborate a bit more, I'd appreciate it. Especially how to adapt from npm node_modules conventions.
