### ISSUE TITLE
Can't build xsbug on Windows

### ISSUE THREAD

**Issue by horihiro** [Moddable-OpenSource/moddable#110]
I tried to **[Host environment setup](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/Moddable%20SDK%20-%20Getting%20Started.md#host-windows)** step for Windows to build tools.

I got following error on step 6.

At first `build` command is not recognized.
```
C:\Users\horihiro\Projects\moddable\build\makefiles\win>build
'build' is not recognized as an internal or external command,
operable program or batch file.
```

So I executed `build.bat` instead of `build`, but I got following another error.
\# sorry for japanese message only.

```
C:\Users\horihiro\Projects\moddable\build\makefiles\win>build.bat

nmake GOAL=debug BUILD_DIR=C:\Users\horihiro\Projects\moddable\build XS_DIR=C:\Users\horihiro\Projects\moddable\xs /c /f C:\Users\horihiro\Projects\moddable\xs\makefiles\win\xsc.mak /s

    :
    (Many logs are output)
    :

# xsid piuAll.h.xsi
# xsid piuCode.h.xsi
# xsid piuPC.h.xsi
# xsid piuPlatform.h.xsi
# xsid yaml.h.xsi
# xsid yaml_config.h.xsi
# xsid yaml_private.h.xsi
# xsl modules
mc.xs.c
piuApplication.c
c1: fatal error C1083: ソース ファイルを開けません。'C:\Users\horihiro\Projects\moddable\modules\piu\All\piuApplication.c':No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.EXE"' : リターン コード '0x2'
Stop.
```

It seems that the error occured at [L32](https://github.com/Moddable-OpenSource/moddable/blob/public/build/makefiles/win/build.bat#L32
) (for debug) and [L41](https://github.com/Moddable-OpenSource/moddable/blob/public/build/makefiles/win/build.bat#L341) (for release) in [build.bat](https://github.com/Moddable-OpenSource/moddable/blob/public/build/makefiles/win/build.bat)

I tried to above command at the line 32 (or 41), I got same error.

```
C:\Users\horihiro\Projects\moddable\build\makefiles\win>%MODDABLE%\build\bin\win\debug\mcconfig -d -m -p x-win %MODDABLE%\tools\xsbug\manifest.json
piuApplication.c
c1: fatal error C1083: ソース ファイルを開けません。'C:\Users\horihiro\Projects\moddable\modules\piu\All\piuApplication.c':No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\cl.EXE"' : リターン コード '0x2'
Stop.
```

The error says `piuApplication.c` is not found, but the file exists in my computer and also the path of the file is correct.
I can't understand why the error occurred.

Could you please help to build xsbug tool?

Best Regards,

**Comment by bfriedkin** [comment]
Hello -

We are sorry to hear that you are having trouble with the Windows build.

Could you please verify that you are using the Developer Command Prompt for VS 2017 when running the build? The standard DOS Command Prompt console does not include the required build setup.

Assuming you are using the Developer Command Prompt for VS 2017, then I am wondering if there might be a problem with the text encoding of the batch file and sources. I have read about similar issues if the files are UTF-8 encoded, for example. In step 3, did you download the Moddable repository or use "git clone"? I assume you are using a stock file system on Windows.

Please let me know if any of these suggestions provide any clues. We can then investigate further.

Regards,
Brian

**Comment by horihiro** [comment]
Hi @bfriedkin 

This issue is resolved by your hint about character code. :tada::tada::tada:
Thank you so much.

I got the project files by `git clone` on **WSL** when the above error was shown.
So getting it again by Windows native `git clone`, the build process was succeeded.

Maybe there are some difference about character code between both `git clone`.

I really appricate you so much! 😄 

Best Regards,
