### ISSUE TITLE
toFixed(0) sometimes returns a trailing dot

### ISSUE THREAD

**Issue by tve** [Moddable-OpenSource/moddable#1124]
**Build environment:**  Linux
**Target device:** esp32_c3
**Description**
(0.1).toFixed(0) returns "0." instead of "0"

**Steps to Reproduce**
```
trace(`${(0).toFixed(0)} ${(0.1).toFixed(0)}\n`)
```

**Comment by phoddie** [comment]
Interesting catch. Thanks for reporting it. Definitely diverges from other engines. I'm able to reproduce this on macOS as well, so it isn't specific to the ESP32-C3 port.

**Comment by phoddie** [comment]
The fix for this will be part of the June release.

**Comment by phoddie** [comment]
Fixed
