### ISSUE TITLE
Array#sort aborts when elements are deleted

### ISSUE THREAD

**Issue by devsnek** [Moddable-OpenSource/moddable#113]
While testing https://github.com/tc39/ecma262/issues/302 I came across an issue where deleting array elements while sorting causes address boundary errors.

Repro code:

```js
'use strict';

const array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
let first = true;
array.sort((a, b) => {
  if (first) {
    first = false;
    for (let i = 0; i < array.length; i += 1) {
      delete array[i];
    }
  }
  return a - b;
});
```

**Comment by phoddie** [comment]
Nice one. We'll take a look. Thanks.

**Comment by phoddie** [comment]
This is now fixed. Thank you for the report.
