### ISSUE TITLE
documentation for XS in C lacks include file information

### ISSUE THREAD

**Issue by tve** [Moddable-OpenSource/moddable#1141]
**Describe**
There is no information in the [XS in C document](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20in%20C.md) about include files, i.e. what to `#include`. In files in the moddable tree I see includes of `xs.h`, `xsmc.h`, `xsHost.h`, `mc.xs.h` and more. Please provide info on how xs and xsmc interoperate and what to include when & where. I just ran into the issue that `xsmc.h` seemingly undef's xsDefine, so include `xs.h` and `xsmc.h` in that order causes `xsDefine` to be missing. Maybe including both is a no-no? Help...

**Comment by tve** [comment]
Another confusing thing, the example for xsmcGet uses xsVars, why not xsmcVars? This snippet doesn't work unless one includes both xsmc.h and xs.h
```
xsVars(1);
xsmcGet(xsVar(0), xsGlobal, xsID_foo);
xsmcGet(xsVar(0), xsThis, xsID("foo"));
```

**Comment by phoddie** [comment]
In short, either include "xsmc.h" or "xs.h" depending on which set of macros you are using.

The example above should use `xsmcVars` instead of `xsVars`.

The doc has been updated to adress both of these points. Thank you.

**Comment by tve** [comment]
The `xsSet` documentation mentions `xsmcSet` and the signatures look identical, but the example only shows xsSet and just `s/xsSet/xsmcSet/` doesn't work...

BTW, instead of undefining xsXXX macros in xsmc.h please consider defining them to produce a "do not use" compilation error. As it is, if one uses certain xsXXX macros the compilation succeeds or produces strange errors because the compiler assumes it's an undeclared external function.

**Comment by phoddie** [comment]
> BTW, instead of undefining xsXXX macros in xsmc.h please consider defining them to produce a "do not use" compilation error

Nice idea. What's a good way to achieve that using portable C?

**Comment by tve** [comment]
Good question...
In GCC, the following works `#pragma GCC poison xsVars`
In GCC, it also works to do something hacky like `#define xsVars(x) Use xsmcVars instead of xsVars when importing xsmc.h`
I don't know of a clean std-C solution, but I'm far from an expert at std-C
