### ISSUE TITLE
poco silently truncates display list due to lack of memory

### ISSUE THREAD

**Issue by tve** [Moddable-OpenSource/moddable#1149]
**Build environment:**  Linux
**Moddable SDK version:** 3.9.1
**Target device:** Moddable Two

**Description**
Depending on memory configuration poco silently stops drawing.

**Steps to Reproduce**
1. Extract  [repro-poco.tar.gz](https://github.com/Moddable-OpenSource/moddable/files/11713098/repro-poco.tar.gz)
2. Run in simulator as `mcconfig -v -d -m -p lin/moddable_two` (s/lin/mac/ as needed)
3. Observe a flattened cube in the display
4. In the manifest, change the chunk initial allocation to 2048 and rerun
5. Observe that only the red face of the cube gets drawn and that there is no error anywhere in sight
6. In the manifest, change the chunk incremental allocation to 4096 and rerun
7. Observe that now two faces of the cube are drawn

**Expected behavior**
Since the static allocation is unchanged in these 3 versions I expected the full flattened cube to be drawn even with a smaller initial allocation. Or, if there is an issue allocating a large contiguous chunk, that an error be reported with details so I can adjust the allocation parameters.

**Observations**
I get similar issues when the head initial allocation is set too low, e.g. 256

**Comment by phoddie** [comment]
> 1. Extract [repro-poco.tar.gz](https://github.com/Moddable-OpenSource/moddable/files/11713098/repro-poco.tar.gz)
> 2. Run in simulator as mcconfig -v -d -m -p lin/moddable_two (s/lin/mac/ as needed)

This fails because of a missing module dependency:

```
### Error: '../modules/lib/fusion/manifest.json': manifest not found!
```

Removing  that line from the manifest results in this error:

```
main.ts:35:29 - error TS2554: Expected 2-5 arguments, but got 1.

35     const outline = Outline.stroke(path)
                               ~~~~~~~~~~~~

  ../../Projects/moddable/typings/commodetto/outline.d.ts:79:41
    79     static stroke(path: CommodettoPath, weight: number, linecap?: number, linejoin?: number, miterLimit?: number): Outline
                                               ~~~~~~~~~~~~~~
    An argument for 'weight' was not provided.


Found 1 error in main.ts:35
```

**Comment by tve** [comment]
whoops! I must have fat-fingered the tgz upload

**Comment by tve** [comment]
[repro-poco.tar.gz](https://github.com/Moddable-OpenSource/moddable/files/11713316/repro-poco.tar.gz)

main:
```
import Timer from "timer"
import Poco, { PocoPrototype } from "commodetto/Poco"
import { Outline } from "commodetto/outline"

interface Bounds {
  x1: number
  y1: number
  x2: number
  y2: number
}

function calcBounds(vertices: any[]): Bounds {
  const nb = { x1: vertices[0].x, y1: vertices[0].y, x2: vertices[0].x, y2: vertices[0].y }
  for (const v of vertices) {
    // +/-1 is due to width of stroke in Outline.stroke()
    if (v.x <= nb.x1) nb.x1 = v.x - 1
    if (v.x >= nb.x2) nb.x2 = v.x + 1
    if (v.y <= nb.y1) nb.y1 = v.y - 1
    if (v.y >= nb.y2) nb.y2 = v.y + 1
  }
  return nb
}

function drawModel(poco: PocoPrototype, model: any) {
  const { vertices, faces, colors } = model
  for (let i = 0; i < faces.length; i++) {
    const points = new Array(faces[i].length * 2)
    for (let v = 0; v < faces[i].length; v++) {
      const vtx = vertices[faces[i][v]]
      points[2 * v + 0] = vtx.x
      points[2 * v + 1] = vtx.y
    }
    trace(`points: ${JSON.stringify(points)} color:${colors[i]}\n`)
    const path = Outline.PolygonPath(...points)
    const outline = Outline.stroke(path)
    poco.blendOutline(colors[i], 255, outline)
  }
}

export default function main() {
  const poco = new Poco(screen, { rotation: 0 })
  const bg = poco.makeColor(0, 0, 64)
  const red = poco.makeColor(255, 0, 0)
  const grn = poco.makeColor(0, 255, 0)
  const blu = poco.makeColor(0, 0, 255)
  const ylw = poco.makeColor(255, 255, 0)
  trace(`Display ${poco.width}x${poco.height}\n`)

  let bounds3d = { x1: poco.width, y1: poco.height, x2: 0, y2: 0 }

  function updateDisplay() {
    // project vertices
    const projBoxModel = {
      vertices: [
        { x: 45, y: 102, z: 1.0960806866158195, w: 0 },
        { x: 109, y: 132, z: 1.0666074739734863, w: 0 },
        { x: 128, y: 185, z: 1.0693351646078935, w: 0 },
        { x: 69, y: 178, z: 1.1018724902238466, w: 0 },
        { x: 86, y: 80, z: 1.1003089850454624, w: 0 },
        { x: 139, y: 118, z: 1.0686086692096703, w: 0 },
        { x: 160, y: 172, z: 1.0715068227216382, w: 0 },
        { x: 114, y: 158, z: 1.1066397492753755, w: 0 },
      ],
      faces: [
        [0, 1, 2, 3],
        [0, 3, 7, 4],
        [0, 1, 5, 4],
        [1, 2, 6, 5],
        [2, 3, 7, 6],
        [4, 5, 6, 7],
      ],
      colors: [62226, 31401, 36361, 65351, 36361, 61958],
    }

    // first time around clear screen
    poco.begin()
    poco.fillRectangle(bg, 0, 0, poco.width, poco.height)
    poco.end()

    // figure out screen area being updated
    const nb = calcBounds(projBoxModel.vertices)
    const ub = {
      x1: Math.min(bounds3d.x1, nb.x1),
      y1: Math.min(bounds3d.y1, nb.y1),
      x2: Math.max(bounds3d.x2, nb.x2),
      y2: Math.max(bounds3d.y2, nb.y2),
    }
    bounds3d = nb
    trace(`Bounds: [ ${ub.x1} ${ub.y1} ${ub.x2} ${ub.y2} ]\n`)
    poco.begin(ub.x1, ub.y1, ub.x2 - ub.x1 + 1, ub.y2 - ub.y1 + 1)
    poco.fillRectangle(bg, 0, 0, poco.width, poco.height)

    drawModel(poco, projBoxModel)
    poco.end()
  }

  updateDisplay()
  //Timer.repeat(updateDisplay, 4000)
}
```

manifest:
```
{
  "include": [
    "$(MODDABLE)/examples/manifest_base.json",
    "$(MODDABLE)/examples/manifest_typings.json",
    "$(MODDABLE)/examples/manifest_commodetto.json",
    "$(MODDABLE)/modules/commodetto/outline/manifest.json",
    "../modules/lib/fusion/manifest.json"
  ],
  "modules": {
    "*": ["./*.ts"]
  },
  "preload": ["main"],
  "creation": {
    "static": 64000,
    "chunk": {
      "initial": 30000,
      "incremental": 4096
    },
    "heap": {
      "initial": 1024,
      "incremental": 64
    },
    "stack": 256,
    "main": "main"
  }
}
```

**Comment by phoddie** [comment]
Thanks, I'm able to reproduce this. Not sure what's going on yet. Have some other things to take care of today, so may not get to it right away.

**Comment by tve** [comment]
No rush, it's not blocking anything.

**Comment by phoddie** [comment]
If it was an allocation failure, it would report an error. That got me thinking about other failure modes which led me to understanding the problem. The outlines are being garbage collected before they can be rendered. That's XS being really efficient and trying not to expand the chunk heap unless necessary. That problem only happens when using Poco without Pit, as Piu manages the lifecycle of the outlines it creates. A clean, efficient solution will take a little effort to sort out.

**Comment by tve** [comment]
I see, so something (probably poco) needs more memory, the heap is full, gc is triggered, it erroneously collects the outlines, interesting stuff ensues...?
And this is triggered by the fact that by the time poco.end() is called the variables holding the references to the outlines are long garbage and internally a gc-visible reference is not held?

**Comment by phoddie** [comment]
Basically, yes. A simple workaround is to put the outlines in an Array that persists until `end` is called. More or less, that's probably the cleanest fix to this in Poco too.

**Comment by phoddie** [comment]
Good news. I've got a solution working. The RAM overhead about as small as practical - 4 bytes per Poco instance plus (roughly) 4 bytes for each outline drawn between begin & end. That should roll out to this repository Friday.
