### ISSUE TITLE
Shouldn't embedded:io/SMBus extend embedded:io/I2C?

### ISSUE THREAD

**Issue by tve** [Moddable-OpenSource/moddable#1153]
### Discussed in https://github.com/Moddable-OpenSource/moddable/discussions/1151

<div type='discussions-op-text'>

<sup>Originally posted by **tve** June 13, 2023</sup>
In ECMA419 I read "The SMBus class extends the I2C class with additional methods" yet calling `write()` on an SMBus object produces a "no function!" exception and looking at smbus.js I don't see an implementation of write nor extension of I2C. Am I missing something?

The use-case is a TI power management chip that has a PMBus interface, which is an extension of SMBus, and it has "commands" where one just writes the command/register byte and no data. It looks like there's a non-standard `sendByte()` function that should do what I need...</div>

**Comment by phoddie** [comment]
This should now be resolved. Note that rather than subclassing, it adds the methods.
