### ISSUE TITLE
[XS in C] new-ing a slot

### ISSUE THREAD

**Issue by jamieparkinson** [Moddable-OpenSource/moddable#117]
Hi, 

If I have a slot which contains a (reference to) a function or class that I'd like to `new`, is there an easy way to do this from the C API? `xsNew*` et al appear not to be so useful when I don't have the slot to which the thing I'd like to `new` belongs.

Example:
*foo.js*
```
export default class Foo { ... }
```

*main.c*
```
...
xsVars(2);
xsVar(0) = xsCall1(xsGlobal, xsID_require, xsString("foo")); // Foo
xsVar(1) = xsNew0(xsVar(0)); // new Foo();
```

Thanks!

**Comment by phoddie** [comment]
You can do this using `xsNewFunction0`

	#define xsNewFunction0(_FUNCTION) \
		(xsOverflow(-2), \
		fxPushCount(the, 0), \
		fxPush(_FUNCTION), \
		fxNew(the), \
		fxPop())

The macro isn't in `xs.h` at the moment. You can inline it in your code for now, as Piu does in [piuAll.h](https://github.com/Moddable-OpenSource/moddable/blob/public/modules/piu/All/piuAll.h#L791).
