### ISSUE TITLE
mcrun: Persmission error

### ISSUE THREAD

**Issue by meganetaaan** [Moddable-OpenSource/moddable#1173]
**Build environment:** Linux
**Moddable SDK version:** 3.9.7
**Target device:** M5Stack

**Description**
When I try to run mcrun, it fails with the Permission denied error as shown below.

**Steps to Reproduce**
1. Build and install mods using: `mcrun -d -m -p esp32/m5stack`
2. See error

```
opt/esp/idf/tools/idf.py
/bin/sh: 1: /dev/ttyACM0: Permission denied
make: *** [/root/Projects/moddable/build/tmp/esp32/debug/look_around/makefile:122: debug] 
```

**Other information**
I've found the cause.

In the following commit, the SERIAL2XSBUG variable is left empty, causing the mcrun to attempt to execute the subsequent argument, the device file, as a command. According to the commit comment, the tool name should be specified directly here (serial2xsbug).
https://github.com/Moddable-OpenSource/moddable/commit/15a818d9c8c0d0a072e2f312f3e712a104aa976b

**Comment by phoddie** [comment]
Fix merged.
