### ISSUE TITLE
Memory leak in `xs_poco_build` function

### ISSUE THREAD

**Issue by hovhannes-96** [Moddable-OpenSource/moddable#1205]
The memory leak is found by a static analyzer developed at CAST ( https://www.linkedin.com/company/cast-center/).

In modules/commodetto/commodettoPoco.c call of [c_malloc](https://github.com/Moddable-OpenSource/moddable/blob/b0c415540d5e59e71ba3909d01063607b1f3cbce/modules/commodetto/commodettoPoco.c#L97) allocates and returns dynamic memory which is not freed.

**Comment by phoddie** [comment]
Thank you for the report. Unfortunately, the report does not provide sufficient information to reproduce the issue.

Note that a pointer to a field in the allocated the memory is immediately assigned to the host buffer of the Poco JavaScript instance:

https://github.com/Moddable-OpenSource/moddable/blob/b0c415540d5e59e71ba3909d01063607b1f3cbce/modules/commodetto/commodettoPoco.c#L97-L100

When the object is garbage collected or its JavaScript close method is called, `xs_poco_destructor` is called and the  memory allocated is freed:

https://github.com/Moddable-OpenSource/moddable/blob/b0c415540d5e59e71ba3909d01063607b1f3cbce/modules/commodetto/commodettoPoco.c#L49-L57

Based on this analysis there does not appear to be a memory leak. Therefore, I'm going to close this issue. If you have additional information that shows how this memory can be leaked, please update this issue and re-open it. Thank you.
