### ISSUE TITLE
Can't compile in linux

### ISSUE THREAD

**Issue by hiperiondev** [Moddable-OpenSource/moddable#1210]
Following: http://www.moddable.com/documentation/Moddable%20SDK%20-%20Getting%20Started#linux

after:
```
cd $MODDABLE/build/makefiles/lin
make
```
error:
```
# xsc piu/All.xsb
make[1]: xsc: No existe el fichero o el directorio
make[1]: *** [/opt/Desarrollos/Moddable-Projects/moddable/build/tmp/lin/release/xsbug/makefile:401: /opt/Desarrollos/Moddable-Projects/moddable/build/tmp/lin/release/xsbug/modules/piu/All.xsb] Error 127
make[1]: se sale del directorio '/home/opt/Desarrollos/Moddable-Projects/moddable/tools/xsbug'
```

**Comment by mkellner** [comment]
Hello @hiperiondev, I do not have problems building for x86 Ubuntu 22.04.1 or 20.04.1, or Arm Linux (rPi 4).

Please make sure your repository is up to date, remove the bin and tmp directories and try again. If you have a problem, please send the full build output.

```
cd $MODDABLE
git pull --rebase
rm -rf $MODDABLE/build/bin $MODDABLE/build/tmp
cd $MODDABLE/build/makefiles/lin
make
```

**Comment by phoddie** [comment]
Closing as no additional information has been provided. If the problem remains, please re-open.
