### ISSUE TITLE
Unspecific mcconfig error

### ISSUE THREAD

**Issue by lll000111** [Moddable-OpenSource/moddable#122]
Running examples from the examples folder worked. Then I created a directory somewhere else and copied the manifest files from examples/ plus one main.js and manifest.json from a simple example into it.

Now I get

```
mha@mint-virtual-machine ~/Projects/one.test $ mcconfig -d -m -p lin
# error: File unsupported!
### Error: incompatible platform!
```

Which file is unsupported? Which platform is incompatible? As far as I can see it's the exact same manifest files and example file, only that I copied them to another place outside the moddable/ directory. Too bad the error messages are missing specific information about what's wrong.

**Comment by phoddie** [comment]
It refers to the `File` module, hence the capital "F" in file. If you search for "[File unsupported](https://github.com/Moddable-OpenSource/moddable/blob/dc94381c29cfe76dc7e565885a2ff1eff8c501f7/modules/files/file/manifest.json#L23)" in the repository you will find it easily.

**Comment by lll000111** [comment]
May I suggest putting that into ""?

I edited a lot of my own error messages along the same lines after realizing this exact problem: Writing word and writing "word" are very different, the quotes provide crucial hints for reading the sentence.

**Comment by phoddie** [comment]
Thank you for the suggestion.. We've added the word `module` to theese messages, e.g. `File module unsupported`, for the next update.

**Comment by lll000111** [comment]
A quick question for clarification:

Apparently file system support is _only_ available on ESP8266 but not on ESP32 (or anything else)?

Asking because I got the same "File unsupported" building for "esp32" target and because of the list in https://github.com/Moddable-OpenSource/moddable/blob/dc94381c29cfe76dc7e565885a2ff1eff8c501f7/modules/files/file/manifest.json

<br>

**Follow-up question**

How different would https://github.com/Moddable-OpenSource/moddable/blob/dc94381c29cfe76dc7e565885a2ff1eff8c501f7/modules/files/file/esp/modFile.c be for ESP32?

**Comment by phoddie** [comment]
Yes, the build output that the `File` module is unsupported for the ESP32 target is accurate.

The implementation for ESP32 would be quite similar if, like the ESP8266 implementation, it also uses the SPIFFS API and quite different if it uses the file APIs in the ESP IDF instead.

**Comment by lll000111** [comment]
Okay... so do you guys have any plans for it? We may or may not do it if you won't, not sure yet. I'm certainly not expecting anything for nothing, just asking.

**Comment by phoddie** [comment]
> ...do you guys have any plans for it?

There are no immediate plans to support File on ESP32. I expect it will happen, one way or another, this calendar year.

**Comment by lll000111** [comment]
Ok, good to know, thanks!
