### ISSUE TITLE
Build moddable sdk fails on debian

### ISSUE THREAD

**Issue by pcouderc12** [Moddable-OpenSource/moddable#1234]
**Build environment:** Linux debian 12
**Moddable SDK version:** 4.2.1
**Target device:**  All

**Description**
Error message during make in step 6 :

`
make[1]: Leaving directory '/home/nous/projets/maison/components/moddable/build/makefiles/lin'
/home/nous/projets/maison/components/moddable/build/bin/lin/release/mcconfig -m -p x-lin /home/nous/projets/maison/components/moddable/tools/xsbug/manifest.json
make[1]: Entering directory '/home/nous/projets/maison/components/moddable/tools/xsbug'
# xsc piu/All.xsb
make[1]: xsc: No such file or directory

`

**Steps to Reproduce**
 Build using: 
https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/Moddable%20SDK%20-%20Getting%20Started.md#lin-instructions

**Other information**
Workaround : export path described in step 5  instead of step 7

**Comment by mkellner** [comment]
Thank you for the bug report.
I'll have updated documentation in the next drop.
