### ISSUE TITLE
documentation/network/network.md link to examples leads to 404

### ISSUE THREAD

**Issue by lll000111** [Moddable-OpenSource/moddable#124]
Page: https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/network/network.md#class-websocket-client

Link: 

> **Relevant Examples:** [websocketclient](https://github.com/Moddable-OpenSource/moddable/blob/public/examples/network/websocket/websocketclient)

   404 Page Not Found

There is not even a folder `examples/network/websocket/`

Looking through the examples I only find websocket code here (`grep -r websocket examples/`):

```
examples/piu/one-line/main.js:	import {Server} from "websocket"
examples/piu/one-line/main.js:	trace("main.js: websocket handshake success\n");
examples/piu/one-line/main.js:	trace(`main.js: websocket message received: ${value}\n`);
examples/piu/one-line/main.js:	trace("main.js: websocket close\n");
examples/piu/one-line-keyboard/main.js:	import {Client} from "websocket"
examples/piu/one-line-keyboard/main.js:	trace("websocket handshake success\n");
examples/piu/one-line-keyboard/main.js:	trace(`websocket message received: ${value}\n`);
examples/piu/one-line-keyboard/main.js:	trace("websocket close\n");
```

**Comment by lll000111** [comment]
By the way, looking through the code for websocket client/server and the examples in order to write Flow type definitions for it, are you sure this works?

For example, the documentation page says `Server` has a method `write`. I don't see one in the code. Write methods [seem to be on the `Client` created in the `Server` constructor for each new request](https://github.com/Moddable-OpenSource/moddable/blob/public/modules/network/websocket/websocket.js#L273).

**Comment by phoddie** [comment]
> By the way, looking through the code for websocket client/server and the examples in order to write Flow type definitions for it, are you sure this works?

Yes.

> For example, the documentation page says `Server` has a method `write`. I don't see one in the code. Write methods [seem to be on the `Client` created in the `Server` constructor for each new request](https://github.com/Moddable-OpenSource/moddable/blob/public/modules/network/websocket/websocket.js#L273).

The documentation you reference describes how to use the module. It does not document the implementation.

**Comment by lll000111** [comment]
> The documentation you reference describes how to use the module. It does not document the implementation.

Well that's interesting.

I don't see where there's a `write` method on `Server` instances: https://github.com/Moddable-OpenSource/moddable/blob/public/modules/network/websocket/websocket.js#L270

**Comment by phoddie** [comment]
> I don't see where there's a `write` method on `Server` instance

The `Server` is a listener waiting for incoming connections. It is not a TCP connection itself, so it is meaningless for it have a `write` function as there is no destination for the data. When the server receives a connection request, it accepts the request and creates a client instance. The client instance has a `write` function which is used to transmit data to the host at the other end of the connection.

**Comment by lll000111** [comment]
I know that, but please look at the documentation. It documents a `write` function that does not exist, but on the other hand it is silent about the listener stuff which is how the server actually works, as you write.

I'm not stupid and not a newbie. If I have a lot of "beginner questions" it's because not everything is clear from the docs.

**Comment by phoddie** [comment]
I understood that you were attempting to use the WebSocket code in a project. I have tried to help you with that. I did not understand that you were asking a question about the documentation.

**Comment by lll000111** [comment]
Yeah sorry, context switch-

**Comment by lll000111** [comment]
Actually, the whole original submission was about documentation

And I wrote "For example, **the documentation** page says `Server` has a method `write`."

> I understood that you were attempting to use the WebSocket code in a project.

Just trying to run the examples, I've not attempted to run a single line of my own code yet... so all my questions thus far only refer to the examples.

:-)

**Comment by phoddie** [comment]
> the whole original submission was about documentation

The issue identified in the original report will be corrected with the next update to the repository. Thank you.

**Comment by lll000111** [comment]
It was solved.
