### ISSUE TITLE
Variable-length RegExp lookbehind does not work

### ISSUE THREAD

**Issue by littledan** [Moddable-OpenSource/moddable#13]
The TC39 proposal for [RegExp lookbehind](https://github.com/tc39/proposal-regexp-lookbehind) specifies that variable-length lookbehinds are supposed to be supported. V8 implements this, and it's tested [in these test262 tests](https://github.com/tc39/test262/blob/master/test/built-ins/RegExp/lookBehind/variable-length.js), but it doesn't seem to be supported in the RegExp implementation in Moddable here.

A test case:

```js
/(?<=a*)/
```

This produces the following error message:

```
/home/littledan/moddable/examples/helloworld/main.js:15: error: invalid regular expression: lookbehind assertion is not fixed length!
```

Did you consider supporting variable-length lookbehind? Maybe it doesn't work out on an embedded profile.

If Moddable implements lookbehind per spec, this will be helpful for the TC39 proposal reaching Stage 4, as well as limiting compatibility issues with non-Moddable JS.

**Comment by phoddie** [comment]
Good news. We replaced PCRE with our own (brand new!) regular expression engine. The Stage 3 RegExp Lookbehind proposal now works. See our blog post, ["A smaller, more compatible regular expression engine for XS"](http://blog.moddable.tech/blog/regexp/), for further details.

**Comment by littledan** [comment]
Amazing!
