### ISSUE TITLE
Error when build examples/piu/color-picker

### ISSUE THREAD

**Issue by stc1988** [Moddable-OpenSource/moddable#1303]
**Build environment:** macOS,
**Moddable SDK version:**  [70f8bf1](https://github.com/Moddable-OpenSource/moddable/commit/70f8bf155a08a55d112720b9b62bf31033ebcd3d)
**Target device:** MacOS

**Steps to Reproduce**
1. Build  the app `examples/piu/color-picker` using this build command: `mcconfig -d -m  -p mac`
2. See error

```
ReferenceError: module "commodetto/Poco" not found
### ReferenceError: module "commodetto/Poco" not found!
make: *** [/Users/Satoshi/Projects/moddable/build/tmp/mac/mc/debug/color-picker/mc.xs.c] Error 22
make: *** Waiting for unfinished jobs....
```

I think this issue caused by commit 9b84b4b.

**Comment by phoddie** [comment]
Thanks you for the report. Your analysis is correct. We changed the manifests to reduce code size for Piu apps that do not use Poco JavaScript APIs (which is most of them). Those apps now need to include Commodetto direct. This smaller code size is particularly helpful for devices with less flash space (like Moddable Four and Moddable One) The color picker didn't get updated.

The change is easy. In $MODDABLE/modules/input/color-picker/manifest.json update the includes section:

```json
    "include": [
        "$(MODDABLE)/examples/manifest_piu.json",
        "$(MODDABLE)/examples/manifest_commodetto.json"
    ]
```

We'll get this integrated into the SDK.

**Comment by phoddie** [comment]
Closing as fixed.
