### ISSUE TITLE
make: *** [makefile:43: debug] Error 127

### ISSUE THREAD

**Issue by tejas2806** [Moddable-OpenSource/moddable#1314]
Build environment :- WSL Ubuntu 20.04

**Description**
unable to build moddable tools. something is going wrong in the moddable -> build -> makefiles ->lin -> makefile.

**Steps to Reproduce**
1. cd MODDABLE/build/makefiles/lin
2. make

**Expected behavior**
should build all the moddable tools without throwing errors

**Images**
![Screenshot 2024-02-23 165046](https://github.com/Moddable-OpenSource/moddable/assets/65996914/64b0b626-351e-4ba0-84d7-fa13695c56f5)

**Comment by mkellner** [comment]
Hello @tejas2806, 

It looks like you may have set up your environment some time ago. We changed the tools-build to only build release versions by default.

Do you have `$MODDABLE/build/bin/lin/debug` in your path? That should now be `$MODDABLE/build/bin/lin/release`.

Please give that a try and let us know how it goes.

**Comment by tejas2806** [comment]
Hi [mkellner](https://github.com/mkellner)!
I tried out your suggested changes.
![image](https://github.com/Moddable-OpenSource/moddable/assets/65996914/65bef33e-8d17-479b-92aa-240e56c56b78)

but , i am still getting same error.

**Comment by mkellner** [comment]
It is strange that you are getting the same error if you changed the path. The original error was using a path to the debug version of the application.

Please let us know what version of the SDK you are using - that is, type this on the command line and send back the first line: `git log`.
The output from my tree is: `commit 17e61bc92356d0c77db50784566edf67045de381 (HEAD -> public, origin/public, origin/HEAD)`

If you want to use the debug version of the tools, you can build them:
```
cd $MODDABLE/build/makefiles/lin
make debug
```

And for additional debug output, you can use `VERBOSE=1 make`.

**Comment by phoddie** [comment]
Closing because this has gone quiet. If it is still an issue, please reopen and include additional details. Thank you!
