### ISSUE TITLE
"mchex: command not found" on Linux

### ISSUE THREAD

**Issue by ethos-jgreenwood** [Moddable-OpenSource/moddable#1315]
In build/makefiles/lin/tools.mk, it appears that mchex was left out compared to both windows and mac versions.

I modified the file accordingly and it appears to work (attached, renamed to tools.txt so I could actually upload it).
[tools.txt](https://github.com/Moddable-OpenSource/moddable/files/14389524/tools.txt)

**Comment by phoddie** [comment]
Good catch. Thank you for the report and fix. We'll look at integrating that.
