### ISSUE TITLE
partition table question

### ISSUE THREAD

**Issue by SanjayEIC** [Moddable-OpenSource/moddable#1319]
How do I configure the partition table for an ESP32-S3 controller to use both the internal flash (4MB) and external flash (16MB)?

**Comment by phoddie** [comment]
I'm unsure if the ESP-IDF supports memory mapping more than one flash chip.  This is a general ESP-IDF question, not a Moddable SDK specific question. The Moddable SDK fully supports the ESP-IDF partition map through the `partitions.csv` file. Please see the [documentation from Espressif](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html) for further information.

**Comment by phoddie** [comment]
Closing as not a topic for this repo.
