### ISSUE TITLE
Broken links  in documents of examples

### ISSUE THREAD

**Issue by stc1988** [Moddable-OpenSource/moddable#1337]
* https://github.com/Moddable-OpenSource/moddable/tree/public/examples/piu
* https://github.com/Moddable-OpenSource/moddable/tree/public/examples/commodetto

These documents show no images.
Link that starts with `https://moddable.com/assets/` seems to unavailable.

**Comment by phoddie** [comment]
Thanks for the report. This may have happened when we upgraded the Moddable web site (it runs much faster now). We'll take a look.

**Comment by phoddie** [comment]
The images are displaying again. The main issue was that the files didn't get moved in the server upgrade. There were a couple of image URLs that needed to have a file extension added in the markdown document.

**Comment by stc1988** [comment]
Thank you for confirming. This issue seems  to be fixed.
