### ISSUE TITLE
link to Moddable Blog in documentations redirect to `moddable.com/blogblog`

### ISSUE THREAD

**Issue by stc1988** [Moddable-OpenSource/moddable#1339]
For example, https://blog.moddable.com/blog/colorpicker redirect to https://moddable.com/blogblog/colorpicker that shows `page could not be found.`

[These links ](https://github.com/search?q=repo%3AModdable-OpenSource%2Fmoddable%20https%3A%2F%2Fblog.moddable.com%2Fblog&type=code) are seems to affected by this issue.

**Comment by phoddie** [comment]
Thanks for the report. This was broken in just the last few days when fixing a redirect. We'll fix that on the site.

**Comment by phoddie** [comment]
Fixed! Please check.

**Comment by stc1988** [comment]
I confirmed this issue fixed.
