### ISSUE TITLE
The image link for Moddable Zero is broken

### ISSUE THREAD

**Issue by stc1988** [Moddable-OpenSource/moddable#1348]
It seems that there is an issue with the [link starting from https://www.moddable.com/images.](https://github.com/search?q=repo%3AModdable-OpenSource%2Fmoddable%20https%3A%2F%2Fwww.moddable.com%2Fimages&type=code)

**Comment by phoddie** [comment]
Thanks for the report. We'll sort this out. With luck it is just a web site change.

**Comment by phoddie** [comment]
This should now be fixed. Please confirm and close.
