### ISSUE TITLE
Improve error messages from mcconfig

### ISSUE THREAD

**Issue by lll000111** [Moddable-OpenSource/moddable#135]
**EDIT:** Title changed and reopened. Not just improve, when imports don't work there sometimes(?) is no message at all.

<hr>

I don't quite find an answer in https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/tools/manifest.md
That file explains existing manifest.json files, but not what those entries mean and/or do. The only sentence to explain "modules", for example, is

> The modules object describes the necessary modules on all platforms.
>
>      "modules": {
>              "*": [
>                     "$(MODULES)/files/resource/*",
>                      "$(MODULES)/base/instrumentation/*",
>      	],
>      },

So.... how does it work? What does that syntax mean?

My interpretation was that this syntax tells the compiler that all files in the paths are accessible via direct name imports (without path). And that if I have modules _with_ a path in import statements I need additional entries, but it's not quite clear what I would put in there and if my assumption even is correct.

<br>

I have JS code with a "main.js" file including a lot of stuff in various sub directories:

**Left:** string used to import the module : **Right:** Path to the files

    "*": "./DEVICE/*",
    "one.core/lib/*": "./DEVICE/node_modules/one.core/lib/*",
    "one.core/lib/system/*": "./DEVICE/node_modules/one.core/lib/system/*",
    "one.core/lib/util/*": "./DEVICE/node_modules/one.core/lib/util/*",

Example: The code has an `import * from "one.core/lib/someStuff.js"` and that file is in `./DEVICE/node_modules/one.core/lib/someStuff.js` relative to the project root (and the manifest file).

<br>

I tried writing the "modules" section of manifest.json like that, I'm not sure what the meaning of the left hand side and right hand side actually is after reading the documentation. Doesn't work, apparently it means something different from what I tried.

**Comment by bfriedkin** [comment]
Hello -

We apologize for the confusion here. Indeed it can sometimes be tricky to get the `modules` properties and associated application `import` statements correct. Your understanding is essentially correct. The `modules` section defines which modules are built by the application. Entries in a modules array that have named keys are matched by import statements in the app. The property values for these entries do correspond to path names to the JavaScript modules source. Wildcards can be used in both the keys and the values. Based on your notes, I believe that the issues you are having are due to small syntax errors in your `main.js` and `manifest.json` files.

Note that we don't use file extensions, e.g. ".js" in import statements or in the manifest.

There are a number of manifest files in the [examples](https://github.com/Moddable-OpenSource/moddable/tree/public/examples) directory that use wildcards and named keys. In particular the [`manifest_commodetto.json`](https://github.com/Moddable-OpenSource/moddable/blob/public/examples/manifest_commodetto.json) and [`manifest_piu.json`](https://github.com/Moddable-OpenSource/moddable/blob/public/examples/manifest_piu.json) files likely include some patterns that cover what you are trying to achieve.

That said, a simple and focused working example can often help to resolve issues at hand. I've attached an `imports` example app the shows a handful of different module and import variations. The example is based on the directory hierarchy you've shared here.

If the working example doesn't help to get you past the issue at hand, please provide more details about the error(s) you are seeing at build/run time.

Regards,
Brian

[imports.zip](https://github.com/Moddable-OpenSource/moddable/files/2923938/imports.zip)

**Comment by lll000111** [comment]
Thank you! This helps.

<br>

> Note that we don't use file extensions, e.g. ".js" in import statements or in the manifest.

As in "not allowed to use it"?

If that is so, I have a feature request: Please allow the file extension. Our project shares code across browser, React Native, node.js, and use of the extension in import statements is a Best Practice. Some bundlers even require it. Some platforms won't find it without extension.

#### UPDATE

Solved for now, I do a string replace by regexp after Babel to remove any `.js` endings, added to the build script.

Also, I found [the answer to issue #91](https://github.com/Moddable-OpenSource/moddable/issues/91#issuecomment-424100301) about file extensions and `fxFindModule` and `fxLoadModule`.

**Comment by lll000111** [comment]
I played around with your example zip. When I change an import in main.js to be nonsensical (random string pointing nowhere) I get no errors and the build just runs through.

I think there should definitely be an error (and a message).

My own code still does not work, I'll keep experimenting. The problem seems to be that within the lib under node_modules I use relative paths from `./`, from the app those same files are imported using the longer path relative to the node_modules directory `one.core/lib/` Since there are no error messages I don't know what is going on.... I only get

    ### Error: (host): No such file or directory

**EDIT:** Looks like `mcconfig` exits right away and does not do anything at all when this error message is displayed. manifest see below, main.js is in the directory I call `mcconfig` from and where manifest.json is located. I moved it all into `DEVICE/` so that is the new `./` now (previously manifest and main where one level up).

I added two entries for each directory under node_modules: One for imports from within the lib, one (longer path) for imports from the app code (main.js). main.js has an import for `import { initInstance } from 'one.core/lib/instance';`, and that instance.js file has several imports for `./*`, i.e. file in the same directory as itself. Since there is an entry in manifest.json to that directory for both import paths that should work.

No `.js` endings in the import statements any more.

```
...
"modules": {
                "*": "./main",
                "./*": "./node_modules/one.core/lib/*",
                "../*": "./node_modules/one.core/lib/*",
                "./system/*": "./node_modules/one.core/lib/system/*",
                "./util/*": "./node_modules/one.core/lib/util/*",
                "one.core/lib/*": "./node_modules/one.core/lib/*",
                "one.core/lib/system/*": "./node_modules/one.core/lib/system/*",
                "one.core/lib/util/*": "./node_modules/one.core/lib/util/*",
        },
```

Anyway, the lack of error messages is my main issue, I added the rest for context only.

**Comment by lll000111** [comment]
Update 2: When I remove all "modules" entries but the first one for main than the build runs through and the simulator starts (building for Linux during these basic build tests). The runtime then complains about not finding the module (of course).

With the other "modules" lines I'm back to the error mentioned above. The directories listed there all exist and have .js files in them.

**Comment by lll000111** [comment]
The lines

```
"one.core/lib/*": "./node_modules/one.core/lib/*",
"one.core/lib/system/*": "./node_modules/one.core/lib/system/*",
"one.core/lib/util/*": "./node_modules/one.core/lib/util/*",
```

cause the error. I don't know why. The directories exist.

I solved it by not using "one.core/lib/..." as path and removing those now no longer needed entries. This is okay for me, that's from the (platform specific) app file, here main.js, the paths from within the lib are harder to change since those are for all platforms.

**Comment by lll000111** [comment]
**Update** &mdash; I thought I had this figured out but I cannot make sense of this latest error:

Runtime error in xsbug: `require: module "./util/recipe-find-linked-rules" not found!`

But there is a line in manifest.json for this:

    "./util/*": "./node_modules/one.core/lib/util/*",

Run from the build root (same directory as manifest.json and where I run mcconfig from):

```
$ ls -l ./node_modules/one.core/lib/util/
total 48
...
-rw-r--r-- 1 mha mha  1252 Mar  4 13:00 recipe-find-linked-rules.js
...
```

**Comment by bfriedkin** [comment]
Hello -

Unfortunately it is difficult to know the cause of this error without knowing what the `import` statement is.

I've attached another simple working example here that uses your same `./util/*` pattern. Note that in this example, using `./util/*` or `util/*` in the `manifest.json` and `main.js` files achieve the same result.

Regards,
Brian

[imports2.zip](https://github.com/Moddable-OpenSource/moddable/files/2931716/imports2.zip)

**Comment by lll000111** [comment]
> Unfortunately it is difficult to know the cause of this error without knowing what the import statement is.

I'm working on a small and simple test zip archive...

**Comment by lll000111** [comment]
By the way, doesn't the error message I posted above show the path?

> `require: module "./util/recipe-find-linked-rules" not found!`

That file is includes twice. Once from a file in the same directory that uses `./recipe-find-linked-rules`, and once from a file in the parent directory which uses the path that is shown.

```
$ grep -r recipe-find-linked-rules .
./node_modules/one.core/lib/object-recipes.js:import { findAllLinkedRules } from './util/recipe-find-linked-rules';
./node_modules/one.core/lib/util/type-checks.js:import { findAllLinkedRules } from './recipe-find-linked-rules';
```

**Comment by lll000111** [comment]
Never mind, I decided to avoid the whole issue by changing the paths during the build process.
