### ISSUE TITLE
Type of wifi WiFiOptions.bssid is ArrayBuffer, not string

### ISSUE THREAD

**Issue by cmidgley** [Moddable-OpenSource/moddable#1352]
**Build environment:** Windows
**Moddable SDK version:** OS201127-4913-gd487dd776
**Target device:** ESP32

**Description**
In `typings/wifi.d.ts` the definition for `bssid` on `WiFiOptions` is defined as `string` but I believe it is actually `ArrayBuffer`.

Current `wifi.d.ts`:

```ts
  export type WiFiOptions = {
    bssid?: string,
    ssid: string,
    password?: string
  }
```

Proposed change:

```ts
  export type WiFiOptions = {
    bssid?: ArrayBuffer
    ssid: string,
    password?: string
  }
```

**Comment by phoddie** [comment]
(Hey, Chris!) Yes, that's a mistake. I'll apply your fix for that.
