### ISSUE TITLE
encountered "can't init zlib" error with the pngdisplay program on Moddable Two device, but works on simulator.

### ISSUE THREAD

**Issue by kitazaki** [Moddable-OpenSource/moddable#1353]
**Description**
I encountered "can't init zlib" error with the pngdisplay program on Moddable Two device, but works on simulator.

**Build environment:** macOS
**Moddable SDK version:** 4.8.0
**ESP IDF version:** 5.2.2
**Target device:** Moddable Two, desktop simulator

**Steps to Reproduce**
1. change directory to the pngdisplay sample program: `cd $MODDABLE/examples/commodetto/pngdisplay`
3. Build and install the app using this build command: `mcconfig -d -m -p esp32/moddable_two ssid="[ssid]" password="[password]"`
4. upload test.png in same directory to the devide: `curl -T test.png http://[ip address]/upload`
5. See error

**Images**
(Moddable Two)
![img_6302_720](https://github.com/Moddable-OpenSource/moddable/assets/23477407/8ff8f9a4-e1a9-44fb-987b-74d420fb09b2)
![____________________________2024-06-06_20 42 51](https://github.com/Moddable-OpenSource/moddable/assets/23477407/b7c3af2c-f001-495a-a4ee-2149ca2dc040)

(simulator)
![スクリーンショット 2024-06-07 9 35 29](https://github.com/Moddable-OpenSource/moddable/assets/23477407/da6d2c8b-011d-462f-8e6e-1dfcd70a90bf)

**Other information**

I'm going to do porting sample programs to Node-RED MCU nodes.
displaying JPEG works fine, but PNG works only on simulator.

https://github.com/kitazaki/node-red-contrib-mcu-display-image

![palette](https://github.com/Moddable-OpenSource/moddable/assets/23477407/37bc3725-4f54-4720-a538-4440984aa0e4)
![flow](https://github.com/Moddable-OpenSource/moddable/assets/23477407/c1908305-cabc-4a29-9589-7745fea94abc)
![img_6301](https://github.com/Moddable-OpenSource/moddable/assets/23477407/ca816388-ac63-4f57-9fe6-e370a21ae15c)

**Comment by phoddie** [comment]
The zlib decoder requires a relatively large block of memory to operate. The size of this block is unrelated to the size of the image. It looks like it is failing to allocate that. If you try running on a device that has PSRAM, I expect it will work since there will be plenty of memory. You may be able to adjust the `creation` for your Node-RED project to free up some memory for zlib on devices without PSRAM.

The reason that this works on the simulator is that it has nearly infinite memory, since it runs on your computer.

**Comment by kitazaki** [comment]
@phoddie 

Thank you for your comment.
It works fine with M5Stack Core2 (ESP32 + PSRAM 8MB)

![M5Core2](https://github.com/Moddable-OpenSource/moddable/assets/23477407/6e5f39fa-6f0d-4bc4-a66a-4fbd9858fa0c)

![2](https://github.com/Moddable-OpenSource/moddable/assets/23477407/b5539868-c554-4caf-b269-6ff8cf9ebe02)

**Comment by kitazaki** [comment]
closed.
