### ISSUE TITLE
JSON.parse('-0') should evaluate to -0

### ISSUE THREAD

**Issue by mathiasbynens** [Moddable-OpenSource/moddable#137]
`Object.is(JSON.parse('-0'), -0)` should evaluate to `true`. It's currently `false` in XS.

```
$ eshost -se 'Object.is(JSON.parse("-0"), -0)'
#### Chakra, JavaScriptCore, SpiderMonkey, V8, V8 --harmony
true

#### XS
false
```

See https://github.com/tc39/ecma262/pull/1466.

**Comment by phoddie** [comment]
Thanks for the report. This will be fixed in our next push.

**Comment by phoddie** [comment]
Fixed. Update to `xst` binaries pushed so you should be able to verify easily.

**Comment by mathiasbynens** [comment]
```
$ eshost -se 'Object.is(JSON.parse("-0"), -0)'
#### Chakra, JavaScriptCore, SpiderMonkey, V8, V8 --harmony, XS
true
```

Thanks for the quick fix!
