### ISSUE TITLE
[documentation]mcrun support the `-t` option?

### ISSUE THREAD

**Issue by stc1988** [Moddable-OpenSource/moddable#1380]
I found that mcrun supports -t build option since [Moddable SDK 4.3.4](https://github.com/Moddable-OpenSource/moddable/releases/tag/4.3.4).
On the other hand, the [documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/tools/tools.md#mcrun) still states that it is not supported.

**Comment by phoddie** [comment]
You raise a good point.

The reality is a little complicated.. `-t build` is supported but other options for `-t` such as `clean` are not supported for all target platforms (and `deploy` doesn't appear to be supported for any target).

I'll update the documentation to mention that `-t build` is supported.

**Comment by stc1988** [comment]
I confirmed this fixed.
