### ISSUE TITLE
[documentaion]Audio Streamers support streaming over HTTPS?

### ISSUE THREAD

**Issue by stc1988** [Moddable-OpenSource/moddable#1384]
The documentation for [Audio Streamers](https://github.com/Moddable-OpenSource/moddable/blob/public/examples/pins/audioout/http-stream/readme.md?plain=1#L40) states that TLS is not implemented, but [OpenAIStreamer](https://github.com/Moddable-OpenSource/moddable/blob/3fe65e93a775773ca70b253bd80c536692a450b1/examples/pins/audioout/openai-stream/openaistreamer.js#L41-L62) does.
Is this statement unnecessary?

**Comment by phoddie** [comment]
Good point. That statement is obsolete. I've removed it. That will propagate in the the next SDK update. Thank you.

**Comment by stc1988** [comment]
I confirmed this fixed. Thank you .
