### ISSUE TITLE
Error compiling "cryptdigest" example

### ISSUE THREAD

**Issue by lll000111** [Moddable-OpenSource/moddable#139]
Platform: Linux

```
# cc xsBigIntEx.c.o
# cc mont.c.o
# cc ec.c.o
# cc modular.c.o
# cc bin.c.o
# cc modBase64.c.o
# cc mc.resources.c
/home/mha/Projects/moddable/modules/crypt/arith/xsBigIntEx.c: In function ‘fxBigInt_ec_double’:
/home/mha/Projects/moddable/modules/crypt/arith/xsBigIntEx.c:544:17: error: ‘true’ undeclared (first use in this function)
   r->identity = true;
                 ^
/home/mha/Projects/moddable/modules/crypt/arith/xsBigIntEx.c:544:17: note: each undeclared identifier is reported only once for each function it appears in
/home/mha/Projects/moddable/modules/crypt/arith/xsBigIntEx.c:548:16: error: ‘false’ undeclared (first use in this function)
  r->identity = false;
                ^
/home/mha/Projects/moddable/modules/crypt/arith/xsBigIntEx.c: In function ‘fxBigInt_ec_add’:
/home/mha/Projects/moddable/modules/crypt/arith/xsBigIntEx.c:626:18: error: ‘true’ undeclared (first use in this function)
    r->identity = true;
                  ^
/home/mha/Projects/moddable/modules/crypt/arith/xsBigIntEx.c:631:16: error: ‘false’ undeclared (first use in this function)
  r->identity = false;
                ^
/home/mha/Projects/moddable/modules/crypt/arith/xsBigIntEx.c: In function ‘fxBigInt_ec_mul’:
/home/mha/Projects/moddable/modules/crypt/arith/xsBigIntEx.c:678:16: error: ‘true’ undeclared (first use in this function)
  r->identity = true;
                ^
/home/mha/Projects/moddable/modules/crypt/arith/xsBigIntEx.c: In function ‘fxBigInt_ec_mul2’:
/home/mha/Projects/moddable/modules/crypt/arith/xsBigIntEx.c:698:16: error: ‘true’ undeclared (first use in this function)
  r->identity = true;
                ^
/home/mha/Projects/moddable/build/tmp/lin/debug/mc/cryptdigest/makefile:476: recipe for target '/home/mha/Projects/moddable/build/tmp/lin/debug/mc/cryptdigest/xsBigIntEx.c.o' failed
make: *** [/home/mha/Projects/moddable/build/tmp/lin/debug/mc/cryptdigest/xsBigIntEx.c.o] Error 1
```

<br>

Unfortunately, when I define true and false the compilation *appears* to run through...

```
$ mcconfig -d -m -p lin
# xsid xsBigIntEx.c.xsi
# xsl modules
# cc mc.xs.c
# cc xsBigIntEx.c.o
# ld mc.so
mha@mint-virtual-machine ~/Projects/one.moddable/DEVICE $ 
```

... but nothing happens (xsbug is open and remains silent).

Seems to work on ESP32, the only other platform I tested. I use Linux for the basic tests to catch simpel errors like "module not found" without having to write to the board every time...

**Comment by bfriedkin** [comment]
Hello -

Thank you for reporting this issue. We have been able to reproduce the error building on Ubuntu 18.04 Linux as well.

An easy workaround is to add the following to xsBigIntEx.c (after the MIN define):

```
#ifndef MIN
#define MIN(a, b)	((a) <= (b) ? (a) : (b))
#endif
#ifndef true
	#define true (1)
#endif
#ifndef false
	#define false (0)
#endif
```
Keep in mind that on desktop hosts, you need to manually launch `xsbug` before building and running your Moddable app. When I do that I see the following in the `xsbug` console:

```
Calculated hash: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
Expected hash: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
PASS
PASS
PASS
```

Would you be able to give this another try? Let us know how that goes. We will review the fix and roll into our next open source release.

Regards,
Brian

**Comment by lll000111** [comment]
I had done all of that, only that I used `#define true 1` without parentheses but I tried exactly your code just now. I had also started xsbug separately, I had already noticed that behavior. The compilation finishes as shown above and xsbug remains completely silent and empty.

Well, I guess maybe it actually _does_ run through, but the `trace` does not show? It works fine in all the other stuff I tried though.

**EDIT:**

I wrote nonsense at the beginning of main.js to trigger an error but I still see nothing at all.

```
$ mcconfig -d -m -p lin
# xsc main.xsb
# xsl modules
# cc mc.xs.c
# ld mc.so
$
$  # nothing in xsbug either
```

**Comment by lll000111** [comment]
All "Linux" builds are stuck now for some reason, meaning the compile runs through and then nothing happens. Even the things that worked just fine. I did not change anything in `$MODDABLE` apart from the above `#define` (and my PR for "file"), `git status` agrees, there are no changes. I removed everything in `$MODDABLE/build/tmp/` and tried again, no change.

**Comment by lll000111** [comment]
### SOLVED

Having written this comment it finally "clicked" when I looked at the makefile call with `nohup` running this in the background. Of course, there was a simulator still running which I just needed to kill.

------------

Looking at the generated makefile in moddable/build/tmp/lin/debug/mc/helloworld/

Removing the "silent" make flag, when all is build it just says "make: Nothing to be done for 'all'."

To run the result I see the command is

```bash
$(shell nohup $(SIMULATOR) $(BIN_DIR)/mc.so > /dev/null 2>&1 &)
```

Next I try to manually run

```
$MODDABLE/build/bin/lin/debug/simulator $MODDABLE/build/bin/lin/debug/mc/helloworld/mc.so
```

and, with xsbug running because I started it from another shell, after some time I get

```
Failed to register: Timeout was reached
```
