### ISSUE TITLE
The image is not displaying correctly in moddable-six.md

### ISSUE THREAD

**Issue by stc1988** [Moddable-OpenSource/moddable#1393]
The image at [line 171](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/moddable-six.md?plain=1#L171)  is not displaying correctly.

<img width="810" alt="スクリーンショット 2024-08-17 0 04 33" src="https://github.com/user-attachments/assets/5c900f69-a85e-4d44-9a0d-217f306d0c42">

**Comment by phoddie** [comment]
Thanks for catching that. It looks like that image wasn't updated when we migrated the doc from a gist to the repo.

**Comment by phoddie** [comment]
Fixed.
