### ISSUE TITLE
ESP32: Digital.write makes a glitch noise

### ISSUE THREAD

**Issue by ghamaya** [Moddable-OpenSource/moddable#1403]
When you use the Digital module for critical control, it is better to use clear description. Below sample (pin:4, pin:5) shows the difference.
```
import Timer from "timer";
import Digital from "pins/digital";
let outpin = new Digital({pin: 5, mode: Digital.Output})
let blink = 0;
Timer.repeat(() => {
	blink = blink ^ 1;
	Digital.write(4, blink);	// pin: 4
	outpin.write(blink);		// pin: 5
}, 200);
```

![digitalout2](https://github.com/user-attachments/assets/8f9f8aee-7fe9-4e2a-a2fe-2aada22d668c)

**Comment by phoddie** [comment]
Interesting image, thank you.

The `Digital.write()` API doesn't fully initialize the pin itself. It assumes that has been done elsewhere. The `Digital` instance does full initialization.

The ECMA-419 IO APIs (which include Digital) eliminate this ambiguity by only provide the `write` method on an instance.

So, yes, it is better to use either the `new Digital` or [ECMA-419'digital](https://github.com/Moddable-OpenSource/moddable/blob/public/examples/io/digital/blink/main.js).
