### ISSUE TITLE
how to  add new display driver

### ISSUE THREAD

**Issue by qwert1213131** [Moddable-OpenSource/moddable#143]
i have a lcd drivered by st7789,
how to configure?

**Comment by phoddie** [comment]
You need the parameters for your particular display. Those should come from your display provider. The ST7789 controller is MIPI compatible, so it should work with the ILI9341 [driver](https://github.com/Moddable-OpenSource/moddable/blob/public/modules/drivers/ili9341/modIli9341.c). The [documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/drivers/ili9341/ili9341.md) for the driver explains how to configure the initialization of registers, SPI bus speed, and more by modifying your project's manifest.
