### ISSUE TITLE
Error object property "name" should be writable

### ISSUE THREAD

**Issue by lll000111** [Moddable-OpenSource/moddable#144]
I give `Error` objects names (i.e. setting `name`property, sometimes replacing an existing `message` property too) because I prefer this over sub-classing Errors, which only is simple on ES 2015 and with a functional style I don't have a single "class", "this", "bind" in any of my code, it's "just functions".

This is perfectly legal JS. It should just be a normal object.

## Code

```js
const e = new Error('test');
e.name = 'TestError';
trace(e.name + ' ' + e.message);
```

## Result

Error: `set name: not writable!`

![image](https://user-images.githubusercontent.com/25476357/54084163-8f671e80-432d-11e9-8d3a-5a67bddbfede.png)

**Comment by lll000111** [comment]
It seems to me that this is due to [xs/sources/xsError.c setting `XS_GET_ONLY`](https://github.com/Moddable-OpenSource/moddable/blob/public/xs/sources/xsError.c#L121).

I set this to `XS_INTERNAL_FLAG | XS_DONT_DELETE_FLAG | XS_DONT_ENUM_FLAG` and then I could set a message in JS code.<br> 

I also still cannot set the `name` property even though as far [as I can see it only has `XS_DONT_ENUM_FLAG` set](https://github.com/Moddable-OpenSource/moddable/blob/public/xs/sources/xsError.c#L50).

<br>

**EDIT:** Am I confused? `message` apparently *can* be set, with or without the above change. It's only `name` that is not writable. I guess this comment is useless :-(
Time to change the issue title...

I can't see why a `name` property cannot be assigned to Error instances :(

<br>

**EDIT²:** Now I'm **really** confused. In my project code `message` is not writable either, but it worked in the small example above.

<br>

I think [`name` is in the Error constructor's `Prototype` object](https://tc39.github.io/ecma262/#sec-error.prototype.name). When I assign to an Error instance `name` property it should create a new property on the instance. Still, even the original `name` property on the prototype is writable, even if nobody should do that.

[From the ECMAscript standard](https://tc39.github.io/ecma262/#sec-properties-of-error-instances)

> Error instances are ordinary objects that inherit properties from the Error prototype object

No write protection, no special object.

MDN even has [this example **"Throwing a custom error"**:](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/name#Throwing_a_custom_error)

```js
var e = new Error('Malformed input'); // e.name is 'Error'
e.name = 'ParseError';
throw e;
// e.toString() would return 'ParseError: Malformed input'
```

**Comment by lll000111** [comment]
## Workaround

_Just for the record_

Instead of a direct assignment using `Object.defineProperty` on the object:

```js
const err = new Error("Sum Ting Wong, Wi Tu Lo, Ho Lee Fuk, Bang Ding Ow";

Object.defineProperty(
  err,
  'name',
  {
    enumerable: true,
    writable: true,
    configurable: true,
    value: 'FileNotFoundError'
  }
);
```

**Comment by phoddie** [comment]
This is a consequence of freezing of the `Error.prototype` during preload. You can read more about that [here](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/preload.md).

**Comment by lll000111** [comment]
I already know you are freezing prototypes. However, the way this works and is supposed to work, looking at other runtimes, is that a new property *in the instance* is created. If the measure you took prevent adding an instance property this is not just "freezing the prototype".

**Comment by lll000111** [comment]
I read the link again, I had already read it some time ago, just to be sure I did not misread.

The example there explicitly directly changes the prototype object. This has nothing to do with *this* issue here. Assigning to `name` does not modify the prototype object in any way, it creates a new property directly on the instance object. The instance is in RAM and should be writable.

**Comment by phoddie** [comment]
It is a consequence of `Error.prototype` being frozen. The `name` property is on the prototype as per [section 19.5.3.3](https://tc39.github.io/ecma262/#sec-error.prototype.name) of the ECMAScript language specification. When an object is frozen, writes to existing properties fail, including those on instances that use the frozen prototype.

**Comment by lll000111** [comment]
Okay, they indeed do. TIL.

**Comment by lll000111** [comment]
Interesting that Object.defineProperty() still works.
