### ISSUE TITLE
manifest.json: "creation" values are not explained

### ISSUE THREAD

**Issue by lll000111** [Moddable-OpenSource/moddable#147]
https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/tools/manifest.md#creation

The only explanation:

> The creation object defines the creation parameters of the XS machine that will run the app. See [the XS in C documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20in%20C.md) for details.

That page does not tell me e.g. what `static` does/means. It is briefly mentioned [here](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20in%20C.md#machine-allocation) as part of a `struct`. In the example below exactly this value is left out.

In particular, is there any number that sets a maximum? Or is memory allocated as long as there is any free physical memory left? Is this "`static`" property the maximum amount of memory used by a virtual machine, in bytes?

I checked the code as far as `xs/platforms/esp/xsHost.c`.

<br>
Related: #146

**Comment by lll000111** [comment]
Whatever. I'll figure it out.

**Comment by lll000111** [comment]
For the record, should anyone get here, because unanswered questions that you come across while searching for a problem you have have an xkcd and also a Dilbert, I think:

Found this:

https://github.com/Moddable-OpenSource/moddable/blob/public/xs/platforms/esp/xsHost.c#L660

which defines `ESP_cloneMachine` which uses `stackSize`  for a call to `malloc`.

That function is used by `./build/devices/esp32/xsProj/main/main.c` to create the virtual machine:

https://github.com/Moddable-OpenSource/moddable/blob/public/build/devices/esp32/xsProj/main/main.c#L141

<br>

To get support for all the RAM on the board go to `$MODDABLE/build/devices/esp32/xsProj/` and set `CONFIG_SPIRAM_SUPPORT=y` in the ESP-IDF sdkconfig file, as well as enabling `SPIRAM_USE_MALLOC`, probably.

Reference: https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/kconfig.html#config-spiram-support

<br>

**Still,** after following &mdash; or trying to &mdash; this allocation I'm still not sure what that allocated memory is for. It appears to be the heap? The explanations of "context" [in "XS in C"](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20in%20C.md#machine) is confusing when I compare it with the linked code, no word about heap or the allocated memory, or what "context" actually means. Also, `ESP_cloneMachine` from above calls `xsSetContext(result, NULL);`before returning, setting the context to `NULL`???

The documentation could really explain a bit more.

**Comment by chances** [comment]
The manifest documentation has removed the reference to the XS in C document and the [machine allocation documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20in%20C.md#machine-allocation) _still_ does not explain what the `staticSize` (i.e. `static` in manifests) is/does.

@lll000111 I've opened #521
