### ISSUE TITLE
Open source the Moddable Zero PCB files? 

### ISSUE THREAD

**Issue by rwaldron** [Moddable-OpenSource/moddable#15]
This request is probably best served by creating a dedicated repository

**Comment by bfriedkin** [comment]
Hello -

I apologize for the delayed response and thank you for your suggestion.

While we don't open source the Moddable Zero PCB files, we do provide [wiring guides](https://github.com/Moddable-OpenSource/moddable/tree/public/documentation/displays) for a wide variety of displays supported by the [Moddable SDK](https://github.com/Moddable-OpenSource/moddable). Our [display examples](http://www.moddable.com/display) web page contains videos of displays supported on both the ESP8266 and ESP32, and wiring guide / driver documentation links.

Regards,
Brian
