### ISSUE TITLE
BuyDisplay 2.8” CTP ESP8266 power

### ISSUE THREAD

**Issue by pprimm** [Moddable-OpenSource/moddable#154]
The power PIN 2 VDD BuyDisplay ER-TFTM028-4 should be connected PIN 2 to either the VIN PIN (5V) or the 3V3 PIN of the ESP8266 dependent on the JP open/closed per Table 4.3 in data sheet. I suggest this be included in the Configuration section of the wiring guide to add clarification. Your wiring guide for that display is great, btw

**Comment by phoddie** [comment]
Document updated
