### ISSUE TITLE
xsBigInt.o isn't in nmake.esp32.mk

### ISSUE THREAD

**Issue by horihiro** [Moddable-OpenSource/moddable#156]
Just after clone this repo and setting up for esp32, example `httpsgetjson` cannot be built.

But when following entry is added to [`XS_OBJ`](https://github.com/Moddable-OpenSource/moddable/blob/public/tools/mcconfig/nmake.esp32.mk#L93) in `%moddable%/tools/mcconfig/nmake.esp32.mk`, it can be build.

```
	$(LIB_DIR)\xsBigInt.o \
```

Is it necessary entry?

**Comment by bfriedkin** [comment]
Hello -

Thank you for reporting this issue. The file does need to be added to nmake.esp32.mk. The fix will be available in our next open source release.

Regards,
Brian

**Comment by horihiro** [comment]
Thank you so much for adding the file entry
