### ISSUE TITLE
Ble security long term key persist

### ISSUE THREAD

**Issue by diogoviannaaraujo** [Moddable-OpenSource/moddable#159]
Hi,

I've been trying the ble secure examples, but it asks for pairing every time it connects.
Do i need to manually persist the LTK?
Or this is how ble paring is handled and i should implement myself some security scheme for long term communication and only use it for short term?

Thanks

**Comment by bfriedkin** [comment]
Hello -

The BLE security examples request pairing but not bonding. Bonding is required to store the long term key and hence avoid any pairing UI, once both devices persist the keys.

There is an optional bonding property available in the securityParameters. Set the property to true to request bonding:

```
onReady() {
     this.securityParameters = { bonding:true, mitm:true, ioCapability:IOCapability.DisplayOnly };
}
```

For details on the available properties, please refer to the [securityParameters](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/network/ble/ble.md#securityparameters-1) section in the[ BLE reference documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/network/ble/ble.md).

Regards,
Brian

**Comment by diogoviannaaraujo** [comment]
That’s it!

Was not aware of the differences between bonding and pairing, 

Thanks bfriedkin!
