### ISSUE TITLE
Uploads to Moddable Zero often fail under Windows 10

### ISSUE THREAD

**Issue by wdimmit** [Moddable-OpenSource/moddable#18]
Uploading code (in this case the "drag" example) to the Moddable Zero fails more than 50% of the time.  
This is under Windows 10 x64.

Two examples follow:

![image](https://user-images.githubusercontent.com/3732438/34085423-891542ee-e345-11e7-91a9-7b951319e1fc.png)

![image](https://user-images.githubusercontent.com/3732438/34085430-98744a00-e345-11e7-94e0-655d09a45915.png)

**Comment by phoddie** [comment]
Failures were due to a cable that couldn't handle high speed data. Closing as that is the primary issue here. The batch behavior is being addressed separately.
