### ISSUE TITLE
how to "make clean"

### ISSUE THREAD

**Issue by wilberforce** [Moddable-OpenSource/moddable#181]
I've updated to the latest copy of the moddable source and trying to make an ESP8266 project. I'm getting link errors as the source needs to be rebuilt. How can I trigger a fresh build as
`mcconfig -d -m -p esp`  does not work,

adding the -v options I can see some other paths so I can force a rebuild be renaming the `lib` folder
`moddable\build\tmp\esp\debug\lib`.

Wondering if there is a better way..

**Comment by lprader** [comment]
To do a clean build, take the following steps:

- Delete the `$MODDABLE/build/tmp` directory
- Delete all subdirectories in the `$MODDABLE/build/bin` directory
- Rebuild tools as usual

**Comment by wilberforce** [comment]
Thanks.
