### ISSUE TITLE
xsbug on running board - without reflashing with mcconfig

### ISSUE THREAD

**Issue by wilberforce** [Moddable-OpenSource/moddable#183]
is it possible to join a running firmware

I have tried (on windows):

```
xsbug
serial2xsbug.exe COM3  921600 8N1
```

however the esp8266 does not appear and I have to reflash.

**Comment by phoddie** [comment]
The firmware only attempts to connect to xsbug at start-up. If that times out, it moves on. If you reset the esp8266 it will connect to xsbug. I do that on macOS from time-to-time.
