### ISSUE TITLE
Windows - sim and xsbug window sizes

### ISSUE THREAD

**Issue by wilberforce** [Moddable-OpenSource/moddable#199]
I'm not using the screen simulator - so resize the window to be small and put to the side of the screen (as these does not seem to be a way to hide)

However this seem to affect the xsbug Windows size on relaunch - it launches small and I have to resize it.

 The last saved size of these windows seem to effect each other.

**Comment by bfriedkin** [comment]
@wilberforce -

Thank you for pointing this out. We've fixed the problem and the fix will be available in the next Open Source update. BTW, there is a minimize button on both the xsbug and simulator windows.

![image](https://user-images.githubusercontent.com/10502707/60611870-37d93c80-9d7c-11e9-8a91-30ea3e9ed100.png)

Regards,
Brian
