### ISSUE TITLE
[idea] class Resource methods like Class file

### ISSUE THREAD

**Issue by wilberforce** [Moddable-OpenSource/moddable#202]
If The resource class had properties like position and methods like read, it could be drop in replace for the File class as they would operate the same way.

Could be done as an extend on the resource class.

**Comment by phoddie** [comment]
The `Resource` class is a host buffer. It is analogous to `ArrayBuffer` and `SharedArrayBuffer`. It provides a `slice` method like those to extract portions of the data. Like `ArrayBuffer` and `SharedArrayBuffer`, it can be passed as an argument type TypedArray constructors (e.g. `Uint8Array`) and the `DataView` constructor to access the content in various ways.

Like a file, all of these data buffers are simply an array of bytes. `Resource` is read-only and `ArrayBuffer` and `SharedArrayBuffer` are read/write. You could wrap a buffer in an object that emulates the `File` API. It would work:

```
class ResourceFile extends Resource {
    constructor(name) {
         super(name);
         this.position = 0;
    }
   // etc...
}
```

To keep the built-in base functionality as small as possible, I wouldn't recommend adding this functionality to the `Resource` class itself as there are many valid uses of `Resource` that do not require, or benefit from, having a File API.
