### ISSUE TITLE
Implement Promise.allSettled

### ISSUE THREAD

**Issue by mathiasbynens** [Moddable-OpenSource/moddable#211]
This is a stage 3 proposal.

- Repo: https://github.com/tc39/proposal-promise-allSettled
- Spec: https://tc39.es/proposal-promise-allSettled/

Ref. https://github.com/tc39/proposal-promise-allSettled/issues/11.

**Comment by phoddie** [comment]
Thank you for the reminder.

**Comment by phoddie** [comment]
FYI - this is now implemented and tested. Software release expected later this month.

**Comment by mathiasbynens** [comment]
Thanks for the update. I'll mention the Moddable/XS implementation when asking for Stage 4 at TC39 later this month.

**Comment by phoddie** [comment]
Excellent. FWIW- our plan is to have it published by the upcoming TC39 meeting.

**Comment by phoddie** [comment]
`allSettled` is now part of this repository.
