### ISSUE TITLE
ESP32 Arduino core

### ISSUE THREAD

**Issue by dariosalvi78** [Moddable-OpenSource/moddable#215]
You use the Arduino core for the ESP8266, why not doing the same for the ESP32?

The main advantage would be that one could reuse the thousands of Arduino libraries and marshal the C code with JS using your "XS-in-C" method.

**Comment by phoddie** [comment]
Hey @dariosalvi78. Thanks for your excellent suggest.

As you know, the ESP32 has two distinct operating environments - Arduino and the ESP-IDF. Both have their benefits. We chose to focus our development on the ESP-IDF to support our commercial customers. That has proven to be a good choice for their needs.

We would very much welcome and ESP32 Arduino port of the Moddable SDK. Getting the basics working should be a pretty manageable project. It would deliver exactly the benefits you describe to the Arduino community, which would be great.

We're happy to support that effort as needed. Unfortunately, at this time we don't have the bandwidth to take on that port ourselves.
