### ISSUE TITLE
Request: Post schematics/BOM/CAD for devices

### ISSUE THREAD

**Issue by negativekelvin** [Moddable-OpenSource/moddable#221]
Could you please add schematics, BOM, and mechanical drawings for the moddable-one/two/three devices?

**Comment by zgramana** [comment]
And any STL files for enclosures ;-)

**Comment by phoddie** [comment]
We are not publishing the design documents for our hardware at this time.

@jernst has created a nice [back cover](https://github.com/jernst/openscad/tree/master/moddable-2-box) for Moddable Two.

**Comment by negativekelvin** [comment]
This is dumb.  You can get schematics for a MacBook but not these extremely simple boards?  You already have a bunch of open issues re: hardware that would be solved if the user could refer to a schematic.
