### ISSUE TITLE
question: nonstandard JSON

### ISSUE THREAD

**Issue by boneskull** [Moddable-OpenSource/moddable#222]
I notice most/all of the `manifest_*.json` files in `examples/` have trailing commas, which is not valid JSON.  I couldn't find this documented anywhere, either.  Can somebody explain?

**Comment by phoddie** [comment]
Yes, trailing commas are invalid in JSON. The XS parser has long allowed this for convenience.

In the interest of consistency, we will update XS to match the specification here. It will take a little while, as it will require revisiting the JSON files in the repository.

> Side note: Surprisingly, the test262 test suite used for ECMAScript conformance testing does not have a test case for this situation.
