### ISSUE TITLE
How two upload example to the Moddable Two

### ISSUE THREAD

**Issue by blackhuman** [Moddable-OpenSource/moddable#224]
As title says, I can't upload the compile result to the *Moddable Two* board, the esptools.py constantly says "A fatal error occurred: Timed out waiting for packet header". I had read the *Moddable Two* development guide, and had no clue about this.

Before this, I've successfully uploaded some example to the *M5Stack Core* board. *M5Stack Core* board has an embedded CP2012 UART which display the "/dev/cu.SLAB_USBtoUART" port on MacOS. The *Moddable Two* was shipping with the same CP2012 UART program board, but when I plugged it to the *Moddable Two* board and started flash it using command `mcconfig -d -m -p esp32/moddable_two` in the example "network/ble/ios-media-sync" dir, the error "Timed out waiting for packet header" shows up.

I've also tried to push the *flash* button behind the board to try to make the board turn in to the boot mode, but encountered the same error.

Evironment:
- UPLOAD_PORT has been set.
- ESPTOOL_BAUD has been set to 115200.
- MODDABLE has been set.
- IDF_PATH has been set.
- PATH has been set properly.

There is a question: how to make the board be in the boot mode? and how to get rid of the "Timed out waiting for packet header" error?

**Comment by bfriedkin** [comment]
Hello -

Sorry to hear that you are having trouble flashing the app. Could you please confirm that the programming board is plugged into the Moddable Two the correct way? The pin labels on the programming board should match the labels on the Moddable Two. See the attached picture below:

![IMG_1746](https://user-images.githubusercontent.com/10502707/60735933-0d1cee80-9f0a-11e9-9628-d00b6c2d15f8.JPG)

Also, we default the upload speed to 921600. The build defines an `UPLOAD_SPEED` environment variable for this purpose. You shouldn't need to override this value for the Moddable Two. Here is the upload portion of the console output from my Moddable Two build:

```
esptool.py v2.6
Serial port /dev/cu.SLAB_USBtoUART
Connecting........_____.
Chip is ESP32D0WDQ5 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: 24:6f:28:19:d1:9c
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
```

Please let us know if these suggestions resolved the issue. We can diagnose further if the board is properly connected at the default baud rate.

Regards,
Brian

**Comment by blackhuman** [comment]
Still didn't work. My *Moddable Two* was shipping with an pre-programmed test program which can drag and drop the small component. (Show as following picture)

![image](https://user-images.githubusercontent.com/2269615/60751374-49258180-9fe6-11e9-8a39-7bf1b6fe8c56.png)

And I plugged the programming board as follows: (TX->RX,RX-TX)

![Pasted Graphic 1](https://user-images.githubusercontent.com/2269615/60751397-78d48980-9fe6-11e9-81da-3e254cd4a79e.jpg)

To diminish the uncertain factor, I do use the origin esp32 *hello world* example to test, with Serial Port and Serial baud rate set.

![image](https://user-images.githubusercontent.com/2269615/60751427-d10b8b80-9fe6-11e9-9c7e-7ee3c1389f1b.png)

Unfortunately, the result is same as before, with same error. (Note. the blue LED blinks when starting to flash)

￼￼￼[![Failure to Flash to the Moddable Two](https://video-to-markdown.netlify.com/.netlify/functions/image?url=https%3A%2F%2Fvimeo.com%2F346503145)](https://vimeo.com/346503145 "Failure to Flash to the Moddable Two")

**Comment by blackhuman** [comment]
Shocking! when I recorded the video, I found that what the printing on the board is "moddable one", which means that I got an esp8266 based *Moddable One* instead of the esp32 based *Moddable Two*. Maybe the vendor made a mistake to shipping the wrong board? I'll confirm with vendor for this.

**Comment by bfriedkin** [comment]
Following up privately to resolve shipment issue.

- Brian

**Comment by davidmoshal** [comment]
I have the same problem, and I do have the Moddable Two.
#236
