### ISSUE TITLE
Moddable Two: No GPIO Pin 25?

### ISSUE THREAD

**Issue by zgramana** [Moddable-OpenSource/moddable#225]
The status of pin 25--a very important pin for sound--on the moddable two is confusing, and would appreciate clarification.

The [product info page for the Two](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/moddable-two.md#pinout) clearly shows pin 25 routed out to a pad labelled both `GP25` and `SPK +`. Weirdly, however, while the photo _looks_ like my Two in most respects, the product photo's PCB silkscreen actually says `moddable one`.

![image](https://user-images.githubusercontent.com/759830/60760507-4711f180-9feb-11e9-9aa3-81b85ef1cbb4.png)

On the Moddable Two that I received, pin 25 is just not broken out at all, full stop.

![image](https://user-images.githubusercontent.com/759830/60760488-ebdfff00-9fea-11e9-85cf-8cabd72d3b01.png)

Did I get a wrong revision of the board, or the right one? If the later, why was the pin 25 breakout removed? I can understand why you might have decided to not break it out as an I2S internal DAC speaker driver circuit, but not breaking it out at all just makes it very hard to use I2S (which the ESP's excel at). While technically the matrix allows I2S from other pins, I haven't been about to get it to work and several knowledgable ESP32 sources have said it's unlikely to work in most scenarios due to timing issues.

Everything about the Two, an integrated ESP32 + cap touch screen, screams to be paired with I2S sound and an SD card. Even though the Moddable SDK doesn't allow it for the Two, I have been able to get an sdcard working via HSPI by using the Arduino IDE instead (why no HSPI support for the Two in the Moddable SDK?), but the lack of pin 25 access has left me crestfallen.

Is there any reason to _not_ solder a wire onto the pin 25 pad directly (other than soldering skill ability)?

**Comment by zgramana** [comment]
I can get mono using the I2S device (0) + the internal DAC using pin 26 (which also worked without modification with the `piu/sound` demo). However, I'm not able to get anything out of an external [MAX98357A DAC/amp](https://www.sparkfun.com/products/14809?_ga=2.160987961.585427172.1562435070-159683055.1561939606). I can see the signal from the Two on the breakout board's pins, using pins 26, 22, and (pin 25 alternate) 16, but I'm not getting audio out. Further troubleshooting will require protocol analysis with the scope to see if there are timing issues.

**Comment by waldopt** [comment]
The image of the Moddable Two in the Getting Started guide was an internal version that included testing for audio output. The initial release of the Moddable Two did not include that. We anticipate adding GPIO 25 to the external header in a feature rev of the Moddable Two.

**Comment by zgramana** [comment]
I hope you'll update that photo so that others don't get confused. That image is the bulk of the extent documentation on the hardware side of things, given there are no published schematics, etc., so I'm sure others like me give it a lot of attention.

**Comment by lprader** [comment]
@zgramana, I've updated the photo in the pinout to show the board we actually released. It'll show up in our next open source update.
