### ISSUE TITLE
[Feature][PIU] Enable image scaling

### ISSUE THREAD

**Issue by zgramana** [Moddable-OpenSource/moddable#232]
Currently, when placing an image into a texture that has a bounding box larger than the image itself, the image will either be centered or tiled. There does not appear to be a way to scale an `Image` or a `Texture` using `piu`.

It's a pretty standard part of UI toolkits to be able to set an image to scale proportionally to fit it's bounding box, so this omission is surprising.

**Comment by phoddie** [comment]
There's no fundamental restriction in Piu regarding image transformations. And, indeed most UI toolkits on computers and mobile devices provide image transformations. Piu could certainly support transformations. Its precursor in KinomaJS did just that.

That said, Piu is not a graphics engine, it is a UI engine. Piu uses the host graphics engine. On macOS it uses the Apple graphics engine, for example. On microcontrollers, it uses the Commodetto graphics framework with the Poco rendering engine. Both [Poco](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/commodetto/poco.md) and [Commodetto](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/commodetto/commodetto.md) are extensively documented.  The [Design Constraints](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/commodetto/commodetto.md#target-hardware) section of the Commodetto documentation provides a brief statement of the hardware requirements (actually, we run on much less capable systems than are described there!).

The rendering engine must live within a very strict set of constraints. It already provides:

- fully buffered rendering to eliminate flicker
- fully clipped rendering to optimize update speed
- direct display of compressed images to optimize flash storage
- scan line rendering to minimize memory use
- alpha blending to deliver high quality anti-aliased images.

That's already a lot on a little device. And it is fast. We haven't seen a way too add image scaling to that mix while maintaining all the other very desirable characteristics. It is surely possible to implement image scaling on such devices, but doing so within  the fully set of constraints without sacrificing the quality of the user and developer experience is neither trivial nor obvious.

This repository is open to contributions., If you or someone else has the expertise and time to implement scaling we would surely welcome the feature.
