### ISSUE TITLE
copy/paste from xsbug log

### ISSUE THREAD

**Issue by dckc** [Moddable-OpenSource/moddable#240]
I can't seem to copy/paste from the xsbug log. Am I missing something? Or is this not yet supported?

p.s. xs and my moddable two are great fun!

**Comment by wilberforce** [comment]
Hey Dan,
I can cut and paste from the windows client - what platform are you on?

**Comment by dckc** [comment]
Linux

**Comment by mkellner** [comment]
A fix will be in the next opensource drop.

**Comment by mkellner** [comment]
Software has been updated. 
Please let me know if the update resolved your issue.

**Comment by dckc** [comment]
works great; thanks!
