### ISSUE TITLE
Documentation suggestion for Getting Started Guide

### ISSUE THREAD

**Issue by mikew67** [Moddable-OpenSource/moddable#248]
In the Moddable SDK – Getting Started guide, In the ESP32 setup sections (for all hosts?), at step 4 you say:

> Download and untar the ESP32 GCC toolchain. Copy the extracted xtensa-esp32-elf directory into your ~/esp32 directory.

There are **two** xtensa-esp32-elf directories, at the top level of the expanded tar and the first level down.  Please add a note to make sure the user copies the top level.

Stumbled on this by accident and was _interesting_ to unravel...

Mike

**Comment by lprader** [comment]
I've added a note to the getting started guide. It'll show up in our next open source release.

**Comment by phoddie** [comment]
Documentation update is live
