### ISSUE TITLE
preload SyntaxError hard to diagnose without file, line

### ISSUE THREAD

**Issue by dckc** [Moddable-OpenSource/moddable#249]
Any clues on how to _find_ the SyntaxError that's being reported? IOU a copy of the code I'm running, but it loads just fine before I added it to the `preload` section of my manifest.

```
$ mcconfig -d -m -p lin
# xsl modules
# mcrez resources
Total resource size: 0 bytes
### SyntaxError: eval: invalid script!
```

context:
https://github.com/Agoric/harden/issues/47#issuecomment-522350184

**Comment by phoddie** [comment]
The build now reports the path and line number of errors detected during preload. For example, here's the output when adding a syntax error to helloworld/main.js (with the manifest updated to preload main.js):

```
# cc xsmc.c
# cc xsre.c
# xsc main.xsb
# mcrez resources
/Users/hoddie/Projects/moddable/examples/helloworld/main.js:16: error: missing ;!
```
