### ISSUE TITLE
JSON.stringify throws cyclic value! with cycle-avoiding replacer

### ISSUE THREAD

**Issue by dckc** [Moddable-OpenSource/moddable#254]
I'm trying port the [serialize ibid cycle](https://github.com/Agoric/SwingSet/blob/master/test/test-marshal.js#L128) from `@agoric/SwingSet`. xs throws `cyclic value!` at https://github.com/Agoric/marshal/blob/v0.0.1/marshal.js#L398

I reduced it to this function; if I run this in node, it works as expected. If I call it from a `main.js` under xs, it throws:

```js
export function cycleFun() {
  const cycle = ['a', 'x', 'c'];
  cycle[1] = cycle;

  const seen = new Set();

  function skipSeen(k, v) {
    if (seen.has(v)) {
      return undefined;
    }
    seen.add(v);
    return v;
  }

  return JSON.stringify(cycle, skipSeen);
}

console.log(cycleFun());
```

I _think_ the [JSON.stringify spec](https://www.ecma-international.org/ecma-262/5.1/#sec-15.12.3) says this should work.

I looked at [xsJSON.c](https://github.com/Moddable-OpenSource/moddable/blob/public/xs/sources/xsJSON.c)... is it checking for cycles before calling replacer or something? I'm struggling to see if the logic is quite the same as the spec.

cc @warner

**Comment by phoddie** [comment]
Curious. The snippet also works in Safari. We'll take a look. Thanks for the standalone test case. That will help.

**Comment by phoddie** [comment]
Fixed!
