### ISSUE TITLE
Creating compatible JPEG images (tip)

### ISSUE THREAD

**Issue by wdimmit** [Moddable-OpenSource/moddable#27]
After a bit of trial and error, I've sorted out how to create `readJPEG` compatible JPEG images from the command line.  Requires ImageMagick.

`convert image.jpg -sampling-factor 1x1 -define jpeg:extent=5000b image_encoded.jpg`

The key here is  `-sampling-factor 1x1` without it, the tool produces incompatible images (H2V2, I think).  Also useful is `-define jpeg:extent=5000b` which adjusts the quality parameter as needed to cram the image into a limited file size.

**Comment by phoddie** [comment]
Tip is great, thank you. It was also a good motivation to implement H2V2 subsampling in commodettoReadJPEG.c. That's there now.
