### ISSUE TITLE
HTTP server never completes with the responseComplete callback

### ISSUE THREAD

**Issue by sean618** [Moddable-OpenSource/moddable#275]
When using chunked responses the server never seems to do the final responseComplete callback. It looks like stage 10 of the server is never being called (which also means the server.connections is never adjusted back down).

I don't not entirely sure, but it seems like maybe the didReceive function in modSocket is getting called with a null pbuf (maybe because it's getting a TCP FIN from the client?). This causes the socket to get set to kPendingDisconnect | kPendingClose.

This kPendingClose overrides all other pending states which means the socket is closed without any callbacks (even the disconnect one). So stage 10 is never called.

(Based on an ESP32 build)

**Comment by phoddie** [comment]
Closing this out as the HTTP server is working reliably on ESP32, ESP8266, and Raspberry Pi Pico W. If there is additional information about this specification failure, please add that and reopen. Thank you.
