### ISSUE TITLE
Please update the Getting Started > MacOS > Host environment setup > 4. for Catalina's new default shell

### ISSUE THREAD

**Issue by mikew67** [Moddable-OpenSource/moddable#276]

**Comment by mikew67** [comment]
Apple changed the default shell in Catalina to zsh.  Thus the setup instructions for setting $PATH, etc. need to be changed. Here's the guidance from Apple:
[Use zsh as the default shell on your Mac](https://support.apple.com/en-us/HT208050)

**Comment by andycarle** [comment]
@mikew67 Thank you for pointing this out. I've added a note on this to the Getting Started Guide. That change will come with our next open source push.

&nbsp;- Andy
