### ISSUE TITLE
Parallel processing while running XS on the ESP32 platform with JS and C code?

### ISSUE THREAD

**Issue by mikew67** [Moddable-OpenSource/moddable#279]
Suspect I need some additional documentation for my intended  robotics application using XS on a dual core ESP32, written mainly in JS, but with some peripheral drivers, etc., in C.  Here are some questions:

1. If I understand correctly, JS is a single-threaded environment.  If I want to run parallel JS execution streams, there is no _light-weight_ threading mechanism.  But there is a _heavy-weight_ mechanism -- instantiate multiple machines (each with its own XS environment).  This can be done within JS using the **worker** facility, or  in C by doing _machine allocation_ using the **xsCreateMachine** macro (as documented in the XS in C.md file).  Correct?
2. Any sample code for this beyond what's cited in the XS in C file?
3. In the specific case of the dual-core ESP32 platform, is there any guidance on how many _machines_ can be instantiated? Is it possible to allocate a machine to a specific core?  Exclusively?
4. For the case of a separate process written entirely in C (i.e., not dependent on XS), what portions of the ESP32 resources (memory, peripherals, interrupt levels, etc.) can be used without conflicting with the XS machine(s)?  What I have in mind here is something similar to the Nordic nRF52xx series, where the Bluetooth LE stack (called a _SoftDevice_) lives in a protected memory region and reserves roughly half of the system resources, while the other memory region is set aside for the application code along with the remaining peripherals.  There's a strict allocation of the MCU's peripherals between the two worlds.  All interrupts are mediated by the _SoftDevice_ and execution time is also hard allocated in the single ARM core nRF52xx by the the _SoftDevice_. An event handler in the former provides for application time slots.  Very clean and workable.  For example, see Section 7 of a typical [_SoftDevice_ spec](https://infocenter.nordicsemi.com/pdf/S132_SDS_v4.0.pdf).
I don't expect you to have this level of detail for the current XS implementation, but perhaps we can collaborate on documenting same or figure out a simpler scheme.

Thanks,

Mike

**Comment by phoddie** [comment]
The Moddable SDK has long supported a subset of the Web Worker API. On ESP32, the workers run on separate cores, based on the scheduler policies.

[Documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/base/worker.md) and [example](https://github.com/Moddable-OpenSource/moddable/tree/public/examples/base/worker) available. Also, this [Gist](https://gist.github.com/phoddie/c42da1b5c381b0806a04a897308d1119).
