### ISSUE TITLE
Build of simple Pins/Blink example app for ESP32 is broken & xsbug behaves weirdly, too

### ISSUE THREAD

**Issue by mikew67** [Moddable-OpenSource/moddable#280]
Getting really weird behavior.  Here's a minimal repeatable sequence:

1. Running on a MacBook Pro 10,1 (15" Retina, 2013), using Catalina 15.1 (final)
2. Target is an ESP32_Devkitc_V4 (Had trouble getting serial USB connection to Moddable Two -- see the next issue statement.)
3. Did a fresh Mac reboot; started Terminal, built, loaded and ran Hello World example. All OK. (See attached Terminal log and screenshot of xsbug.). Note in particular pathname of file open in xsbug view pane and console output.
<img width="1196" alt="Hello World works fine on ESP32_Devkitc_V4" src="https://user-images.githubusercontent.com/1269461/68077280-39dcf780-fd7e-11e9-9f1b-2c3489546579.png">
4. Killed xsbug (so it'll start fresh in next step).
5. Built, loaded and ran Pins/Blink example app.  From Terminal log, everything worked fine, but...
<img width="1142" alt="Build, load, and startup of Blink app appears OK" src="https://user-images.githubusercontent.com/1269461/68077306-a1934280-fd7e-11e9-993c-2eeec453d6e3.png">
6. xsbug is doing something completely different: (a) its source view is still open on Hello World, not blink, and (b) its console log (and apparently the code that got loaded) is entirely different than Blink.
<img width="1196" alt="but xsbug is doing something completely different" src="https://user-images.githubusercontent.com/1269461/68077331-1d8d8a80-fd7f-11e9-9c03-d39a876e082d.png">

Here's the full Terminal log (including the contents of main.js and the manifest file from Blink):
[Blink debug log.txt](https://github.com/Moddable-OpenSource/moddable/files/3800973/Blink.debug.log.txt)

And a check of some Environment Variables:
<img width="1150" alt="Checking Environment variables" src="https://user-images.githubusercontent.com/1269461/68077344-40b83a00-fd7f-11e9-829a-26c03914d66a.png">

What's going on here?  Some boneheaded configuration error on my part?

TIA,

Mike

**Comment by mkellner** [comment]
It looks like blink is running because of the output. The source display is showing the last opened file. Blink has never yet hit a breakpoint.

Click the "main" tab at the top to show the machine that is running. Then you should see the instrumentation and controls like stop and pause. Press pause.

**Comment by mkellner** [comment]
![image](https://user-images.githubusercontent.com/6822704/68077433-0059bb80-fd81-11e9-80c2-627215a090d6.png)

**Comment by mkellner** [comment]
Helloworld automatically stops and displays the source because there is a `debugger;` strategically placed at the top of the file.

**Comment by mikew67** [comment]
Aha, thanks, Michael.  Looks like a case of RTFM -- specifically, xsbug in my case.  Also, didn't think the app was running because I didn't see any "flashing LEDs", understandable once I double-checked the schematic for the ESP32_Devkitc_V4 and realized the only LED was a power indicator, not a GPIO-connected indicator. Hung a logic probe on GPIO2.  Blinking away  :-)
Thanks for the quick reply.
Mike
