### ISSUE TITLE
Constructor that returns an async IIFE fails in XS

### ISSUE THREAD

**Issue by dtex** [Moddable-OpenSource/moddable#282]
Hi,

I have the following pattern that works in V8 but is throwing in XS.

````js
class Thing {  
  constructor(myName) {
    return (async () => {
      this.name = myName;
      return this;
    })();
  }
}

(async () => {
  let thing1 = await new Thing("Hartman");
  let thing2 = await new Thing("Lovitz");
})();
````

The message I see in the xsbug console is
````bash
/Users/donovan/Projects/embeddedTest/main.js (3) # Break: ?: new async!
````

I understand that this example isn't actually doing anything that requires async, I just wanted to provide a minimal example.

My questions are:
1. Am I asking in the right place?
2. Should this work in XS?

I took a look in the 262 results and didn't see any obviously related "non-pass" (I hate saying "failure", it's so negative).

**Comment by dtex** [comment]
Oh wait, I think I found it:  

From Conformance.md
> ... some platforms do not support eval, new Function, new AsyncFunction or new Generator

I'm guessing ESP8266 does not support new AsyncFunction

**Comment by dtex** [comment]
Is there a make file or something I can edit to enable new AsyncFunction on ESP8266? I'd like to see what impact it has on my use case.

**Comment by phoddie** [comment]
@dtex , thanks for the report.

The ESP8266 host does support AsyncFunctions. The note in the conformance document is a bit misleading as it refers to the fact that we usually strip `eval` (and related functions such as `AsyncFunction` from the ESP8266 target. While `eval` and friends are not present by default, they do work there. But, your example does not depend on `eval`.

Your code does work if you change the name `constructor` to `foo` and then call `thing1.foo("Radner")` in the test. The problem appears to be specific to using the `async` keyword inside a constructor. 

We'll look into the details.

**Comment by phoddie** [comment]
@dtex, the error is caused by some obsolete code to prevent `new`  from being called on async functions. Your code works if that check is disabled. To try that, comment out lines 919 and 920 in [xsRun.c](https://github.com/Moddable-OpenSource/moddable/blob/public/xs/sources/xsRun.c#L919-L920).

We are working on an update to XS. We'll include this fix in the update.

Thank you,

**Comment by dtex** [comment]
I'll try it out tonight. I'm excited because this is the pattern I wanted to use. I had been exploring alternatives and none of them were quite as nice.

Thanks so much!

**Comment by dtex** [comment]
Thanks, I'm back on track. 

Commenting out those lines worked and I will keep an eye out for the next version.
