### ISSUE TITLE
Expose mac-address for AP object in WiFi Scan

### ISSUE THREAD

**Issue by drale2k** [Moddable-OpenSource/moddable#33]
i would like to access the mac address for found Wifi networks but currently there is only ssid, rssi, channel and so on.. 

Any chance to do this?

**Comment by phoddie** [comment]
The scan result includes the `BSSID` for each access point:

	WiFi.scan({}, item => {
		if (item)
			trace(`name: ${item.ssid}, password: ${item.authentication != "none"},
				rssi: ${item.rssi}, bssid: ${(new Uint8Array(item.bssid)).join(".")}\n`);
	});

**Comment by drale2k** [comment]
Oh wow how did i miss that.. thank you!
