### ISSUE TITLE
Misinterprets arrow functions without parentheses in many expressions

### ISSUE THREAD

**Issue by mzgoddard** [Moddable-OpenSource/moddable#330]
XS misinterprets some expressions with arrow functions as valid syntax but instead should report a SyntaxError or early ReferenceError.

The following expressions are not valid JavaScript. Adding parentheses around the arrows would make all of these expressions valid. The values XS currently reports (as returned values or thrown exceptions) would match if they had parentheses.

```js
() => {}.call // function call (){[native code]}
() => {}['call'] // function call (){[native code]}
() => {}`` // undefined
new () => {} // TypeError: ?: new 9: no constructor
() => {}() // undefined
() => {}(Date) // undefined
() => {}(Date.now) // undefined
+() => {} // NaN
!() => {} // false
delete () => {} // true
void () => {} // undefined
typeof () => {} // function
2 << () => {} // 2
() => {} instanceof Function // true
() => {} || 1 // function  (){[native code]}
'abc' in () => {} // false
() => {} ? true : false // true
```

I tested this running the xst binary installed by jsvu.

```sh
$ ~/.jsvu/xs -v
XS 9.0.3
$ uname -a
Darwin beep3.localdomain 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
```

**Comment by phoddie** [comment]
Confirmed these are active with XS10.

**Comment by phoddie** [comment]
These all generate an error now. (Thank you for the excellent find!)
