### ISSUE TITLE
Document that only ADC1 can be used on the ESP32, and meaning of Analog pin numbers

### ISSUE THREAD

**Issue by jernst** [Moddable-OpenSource/moddable#332]
The ESP32 has two ADCs (of which the second, apparently, cannot be used when WiFi is used as well). I cannot find any place in the documentation that mentions:

* only ADC0 is supported in the API
* the pin in `Analog.read(pin)` refers to the ADC channel, and does not use the same pin numbering scheme as the Digital pins. E.g. `Analog.read(4)` apparently reads from GPIO pin 32.

Took me a bit to figure that out.

Perhaps it would be useful to have "device-specific notes" for each supported device that explains that, and have a pointer from the API docs to the device-specific notes.

P.S. I may be wrong about some of what I'm writing here. In particular the documentation I'm asking for might exist; if so, it wasn't in a place that was "obvious" to me.

**Comment by phoddie** [comment]
Closing as this has been resolved by @andycarle's commit.
