### ISSUE TITLE
JNI like interface to link existing native libraries

### ISSUE THREAD

**Issue by MarsPlanet** [Moddable-OpenSource/moddable#333]
This is not an issue but want to know if there is any documentation which describes how to link existing native libraries

**Comment by dckc** [comment]
FFI is pretty extensively documented: https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20in%20C.md

is there something else you had in mind?

**Comment by MarsPlanet** [comment]
Looking for a simple "Hello World" example on how to integrate existing library. Thank you for link, will read through and see if it helps.

**Comment by dckc** [comment]
I think [examples/js/xs-in-c](https://github.com/Moddable-OpenSource/moddable/tree/public/examples/js/xs-in-c) is intended to be the "Hello World" of FFI.

**Comment by phoddie** [comment]
@dckc correctly references the XS in C documentation. This interface is used for all the native modules in the Moddable SDK, so there are tons of examples available to use as a starting point.
