### ISSUE TITLE
How does persistent / external storage work?

### ISSUE THREAD

**Issue by drale2k** [Moddable-OpenSource/moddable#34]
Is it possible to plugin in a mircoSD card via an adapter? If yes, how would it be accessible programmatically? Is there documentation available on this topic?

**Comment by phoddie** [comment]
In theory, yes it is possible to use a microSD card. There is [code](https://github.com/esp8266/Arduino/tree/master/libraries/SD) in the ESP8266 Arduino SDK for it. That said, we have not done the work to integrate it with the Moddable SDK. If the [SPIFFS](https://github.com/pellepl/spiffs) file system meets your needs, that is [supported](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/files/files.md#files).
