### ISSUE TITLE
Websocket: "Partial header!!"

### ISSUE THREAD

**Issue by mrpeu** [Moddable-OpenSource/moddable#343]
I am trying to have a webserver offering a websocket connection; to get a 2-way connection with a web browser. I've successfully used the HTTP server. A Websocket also instantiates successfully. Then I try to connect (from a web browser's devtools): ```let ws = new WebSocket("wss://192.168.178.52:81", "json");
ws.onopen = e => console.log("ws.onopen", e);```
And the server "traces": ```Partial header!!```
from https://github.com/Moddable-OpenSource/moddable/blob/4a6c84a7fa4ca3b0593243d90e7a1edf9c22f362/modules/network/websocket/websocket.js#L319
The network stacks go a little over my head so I might be doing something wrong. I figured I'd ask before starting to read deeper ^^

---
Environment:
WemosD1 mini (ESP8266) programmed through USB on Windows 10, acting as server in this scenario. The client being a Chromium browser (Brave) on same Windows10.

**Comment by phoddie** [comment]
That's interesting. It isn't an error. It is an untested code path. The trace is there to see when it actually happens.

Did the connection work for you? If so, I should remove the trace since the path is now tested. ;)

**Comment by mrpeu** [comment]
I left out a crucial information. When initiating the connection, the "partial header" message pops on the server, and then the browser/client times out with "WebSocket opening handshake timed out".
I am going to look if this handshake is supposed to be done by your lib or if I have to manually do something here.

----
Update/status: reading through [mdn](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers) and [websocket.js](https://github.com/Moddable-OpenSource/moddable/blob/public/modules/network/websocket/websocket.js), the lib has code dealing with the handshake, with the magic string and all.
When outputing what the server receives with
```
trace(
  `[websocket] state:${this.state} line: ${
    Array.from(line).map((c) => c.charCodeAt(0))
  }\n`
);
```
at [websocket.js#L310](https://github.com/Moddable-OpenSource/moddable/blob/4a5f43eabc1ed18c217eeb573215a08b0da0fc0b/modules/network/websocket/websocket.js#L310), it gives
```
[websocket] state:1 line: 22,3,1,2
```
Which does not help me understand what's up actually... ^^

**Comment by phoddie** [comment]
Not sure what is going on. We have successfully used the WebSocket server to communicate with web browsers.

**Comment by mrpeu** [comment]
It works! I was trying to connect to `wss://...` But `ws://...` works. I do no need a secure connection for my current applications so that's fine. I will have to look into it later, at least out of curiosity.

Thanks again for the responses, I'm learning a lot.
