### ISSUE TITLE
Cannot see any text in Hello World Example

### ISSUE THREAD

**Issue by arahasya** [Moddable-OpenSource/moddable#366]
Hi

I have build on macOS 
when I run mcconfig -d -m I can see the display but there is not text

<img width="170" alt="Screenshot 2020-05-22 at 12 24 17 AM" src="https://user-images.githubusercontent.com/59508143/82595152-bde3b900-9bc2-11ea-8bf1-04c9f1d3efdc.png">

What may be the issue?

**Comment by arahasya** [comment]
This is weird because I can see text with other examples

<img width="488" alt="Screenshot 2020-05-22 at 12 43 13 AM" src="https://user-images.githubusercontent.com/59508143/82596650-46fbef80-9bc5-11ea-8714-b78239e4492f.png">

**Comment by lprader** [comment]
If you look at the source code, the `helloworld` example does not display text on the screen. It breaks into the debugger and traces the message "Hello, world - sample" to the console.
