### ISSUE TITLE
ESP32  Preference.keys not implemented

### ISSUE THREAD

**Issue by wilberforce** [Moddable-OpenSource/moddable#368]
Had me going for a while until I saw it's returning an empty array.

Perhaps a warning should be output?

https://github.com/Moddable-OpenSource/moddable/blob/public/modules/files/preference/esp32/modPreference.c#L149

```
void xs_preference_keys(xsMachine *the)
{
	xsResult = xsNewArray(0);
}
```

I started to write the code - then found the function `nvs_entry_find` needed are in version 4 of the idf. Here is the starting point for the future when get to that version:

```
void xs_preference_keys(xsMachine *the)
{
	xsResult = xsNewArray(0);
	const char * domain = xsmcToString(xsArg(0));
	nvs_iterator_t it = nvs_entry_find("nvs", domain, NVS_TYPE_ANY);
	while (it != NULL) {
			nvs_entry_info_t info;
			nvs_entry_info(it, &info);
			it = nvs_entry_next(it);
			//printf("key '%s', type '%d' \n", info.key, info.type);
			xsVar(0) = xsString(info.key);
			xsCall1(xsResult, xsID_push, xsVar(0));
	}
}
```

**Comment by phoddie** [comment]
Ha. Yes, I recently stumbled upon `nvs_entry_find` but found it required ESP-iDF v4. When we do update to that, we'll add support. Meanwhile, perhaps adding an `xsTrace` to `xs_preference_keys` would be enough?

**Comment by andycarle** [comment]
This issue's time has finally come! I've enabled `Preference.keys` for esp32 and it is working well. 

That will be available in our next open source push.

**Comment by wilberforce** [comment]
I was thinking about looking at this... thanks for that.

When does the idf-4 branch go mainstream?

**Comment by andycarle** [comment]
The announced plan is "early February." Unless something big comes up, I think we're on pace to hit that target. 

@wilberforce ESP-IDF 4.2 builds are working well for you? I'm personally very happy with the builds and (especially) the installation process for 4.2.

**Comment by andycarle** [comment]
This change is now live. @wilberforce , please give it a shot when you can and close this out if everything looks good to you.

**Comment by wilberforce** [comment]
I'll give it a try.

**Comment by wilberforce** [comment]
Confirmed - preferences can now be read on the ESP32
