### ISSUE TITLE
The "success" icon for "xpt2046calibrate" looks like a prompt to tap the screen 

### ISSUE THREAD

**Issue by rwaldron** [Moddable-OpenSource/moddable#38]
While running this program, it was unclear to me that the following icon was meant to indicate that calibration was a success—I thought it was a prompt to tap the screen inside that box :D  

![success](https://user-images.githubusercontent.com/27985/36736266-2d287502-1ba6-11e8-8c1d-173f4bab098f.png)

I'd like to propose a change:

![check](https://user-images.githubusercontent.com/27985/36738469-90804f3a-1bab-11e8-921f-41ddff7e0b57.png)

Which looks like: 

![](https://i.gyazo.com/9ea1390905865ac1e852f8880129a3ea.jpg)

**Comment by waldopt** [comment]
— Rick,

Thanks for the feedback on the touch calibration app UI.

I agree it is not clear. 

Like your idea and have added text to support it.



Chris Krueger
Creative Director, Moddable
