### ISSUE TITLE
"Resource busy" on USB port

### ISSUE THREAD

**Issue by markingle** [Moddable-OpenSource/moddable#381]
**Build environment:** macOS Catalina 10.15.4
**Target device:** Moddable Two, 

**Description**
When trying to upload the hello world example the flash fails due to a Resource Busy error.  There are no other applications running and connected to the USB port.

**Steps to Reproduce**
Run "mcconfig -d -m -p esp32"

**Expected behavior**
Hello World to run on the MOddable

**Images**
<img width="1380" alt="Screen Shot 2020-06-08 at 10 17 54 PM" src="https://user-images.githubusercontent.com/11239466/84099095-d29fb980-a9d6-11ea-9e56-7130576bb239.png">

**Comment by andycarle** [comment]
Hi @markingle,

I suspect that what is happening here is that Espressif's idf.py tool is picking the wrong (virtual) serial port on your computer to attempt to upload to. It is choosing `/dev/cu.usbserial-0001`, but the Moddable programmer typically shows up in macOS as `/dev/cu.SLAB_USBtoUART` if the proper Silicon Labs VCP driver has been installed.

I recommend trying out the instructions in the [Getting Started guide's macOS ESP32 setup section](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/Moddable%20SDK%20-%20Getting%20Started.md#esp32-mac), step number 9. There is a note there about setting the optional `UPLOAD_PORT` environment variable and how to determine the proper port to use. 

Please give that a try and let me know how it goes. If that's not the issue, we'll keep digging.

Cheers!
&nbsp;- Andy

**Comment by markingle** [comment]
Yep! That got it!  Thanks for the quick reply!
