### ISSUE TITLE
ESP32 WiFi APSTA mode

### ISSUE THREAD

**Issue by almini** [Moddable-OpenSource/moddable#396]
The ESP32 has a WiFi station/AP-coexistence mode that allows it to run as access point and also to connect to an external access point as station. It would be great if this would be supported through the JavaScript API.

**Comment by phoddie** [comment]
Support for simultaneous Wi-Fi AP and STA operation has been committed. The JavaScript API is identical to ESP8266. The network documentation has been updated, specifically [`Net.get`](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/network/network.md#static-getproperty) for the IP address and MAC address and [`WiFi.accessPoint`](https://github.com/ModdableOpenSource/moddable/blob/public/documentation/network/network.md#static-accesspointdictionary) to explain the `station` property.

There's no example yet, but I made a simple test by merging the `httpget` and `accessPoint` examples. Here's the code:


```js
import WiFi from "wifi";
import {Request, Server} from "http"
import DNSServer from "dns/server";
import Net from "net"

let request = new Request({host: "www.example.com", path: "/", response: String});
request.callback = function(message, value, etc)
{
	if (Request.responseComplete == message) {
		trace(value);
		trace("\n");
	}
}


WiFi.accessPoint({
	ssid: "South Village",
	password: "12345678",
	channel: 8,
	hidden: false,
	station: true,
});

new DNSServer((message, value) => {
	if (DNSServer.resolve === message)
		return Net.get("IP", "ap");
})

let s = new Server({port: 80});
s.callback = function(message, value) {
	if (Server.status === message)
		this.path = value;

	if (Server.prepareResponse === message)
		return {headers: ["Content-type", "text/plain"], body: `hello, client at path ${this.path}.`};
}

trace(`IP default ${Net.get("IP")}\n`);
trace(`IP station ${Net.get("IP", "station")}\n`);
trace(`IP AP ${Net.get("IP", "ap")}\n`);
```

And here's the manifest:

```
{
	"include": [
		"$(MODDABLE)/examples/manifest_base.json",
		"$(MODDABLE)/examples/manifest_net.json",
	],
	"modules": {
		"*": [
			"./main",
			"$(MODULES)/network/http/*"
		],
		"dns/server": "$(MODULES)/network/dns/dnsserver"
	},
	"preload": [
		"http"
	]
}
```
