### ISSUE TITLE
MCP230XX driver and examples are all broken

### ISSUE THREAD

**Issue by rwaldron** [Moddable-OpenSource/moddable#40]
Before attempting to run any code, I rebuilt everything.

I'm not sure which commit broke the driver and I'm having trouble finding a "last good commit" (even when I go back to my last commit to this code, I get unrelated errors). This commit https://github.com/Moddable-OpenSource/moddable/commit/61315cb9ae8bc2c77c20be6c2ee02f4a13ee49d5 introduced alout of changes, but I currently cannot pinpoint the exact cause of breakage. 

This commit https://github.com/Moddable-OpenSource/moddable/commit/923feab22008459990e4cd3bff3afb57d768b522 broke the examples, because now there is no module "pins/digital" to import from. 

A lot of code churn is happening, and that code is getting merged without being tested against real hardware, in all configurations that will be affected. When I was writing this driver, I ran every single change against 5 different hardware setups: 

- Single MCP23008
- Multiple MCP23008
- Single MCP23017
- Multiple MCP23017
- Combo MCP23008 & MCP23017

I did this testing to ensure that my changes didn't introduce regressions. I tested these same configurations for the follow patch as well.

**Comment by phoddie** [comment]
I believe these are currently working. If you encounter issues, please re-open. Thanks.
