### ISSUE TITLE
Spec. Mismatch: Array.prototype.toString behaves differently against the specification

### ISSUE THREAD

**Issue by Reinose** [Moddable-OpenSource/moddable#404]
### Environment
```
# uname -a
Linux reinose-ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# xs -v
XS 10.3.0
```

### Bug description
```JavaScript
'use strict';
print(JSON.stringify(Array.prototype.toString.call( { } )));
```
The above JavaScript code produces an exception as follow in xs: `TypeError: Array.prototype.toString: no function`

However, according to ECMA262 specification([http://ecma-international.org/ecma-262/11.0/](http://ecma-international.org/ecma-262/11.0/)), the code should result in: `"[object Object]"`

### Details
In [22.1.3.30 Array.prototype.toString](http://ecma-international.org/ecma-262/11.0/#sec-array.prototype.tostring), the step 3 denotes that if the **join** function of given object is not callable, use the intrinsic function %Object.prototype.toString%.
Therefore, `Array.prototype.toString.call( { } )` would produce same result as `Object.prototype.toString.call( { } )`.
In xs, however, it seems to skip the step 3 and produce a TypeError by calling **join** function of `{ }`, which is **undefined**.

NOTE: The following is the result of Node v14.5.0
```
# node -e "'use strict'; console.log(JSON.stringify(Array.prototype.toString.call( { } )));"
"[object Object]"
```

**Comment by phoddie** [comment]
Fix pending
