### ISSUE TITLE
Spec. Mismatch: Async function toString result differs

### ISSUE THREAD

**Issue by Reinose** [Moddable-OpenSource/moddable#408]
### Environment
```
# uname -a
Linux reinose-ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# xs -v
XS 10.3.0
```

### Bug description
```JavaScript
'use strict';
var x = (async function * ( ) { }).toString();
print(JSON.stringify(x));
```
The above JavaScript codes produce a result as follow in xs: `"function  (){[native code]}"`

However, according to ECMA262 specification([http://ecma-international.org/ecma-262/11.0/](http://ecma-international.org/ecma-262/11.0/)), the code should result in: `"async function * ( ) { }"`

### Details
This bug is similar to #402.
The **[[SourceText]]** of the result closure is not from the source code.

NOTE: The following is the result of Node v14.5.0
```
# node -e "'use strict'; var x = (async function * ( ) { }).toString(); console.log(JSON.stringify(x));"
"async function * ( ) { }"
```

**Comment by phoddie** [comment]
This is not a bug for the same reason as given in #402.
