### ISSUE TITLE
Spec. Mismatch: For-in statement over a string does not work

### ISSUE THREAD

**Issue by Reinose** [Moddable-OpenSource/moddable#409]
### Environment
```
# uname -a
Linux reinose-ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# xs -v
XS 10.3.0
```

### Bug description
```JavaScript
'use strict';
var x = undefined;
for ( x in 'str' ) throw Error(42);
print(JSON.stringify(x));
```
The above JavaScript code produces a result as follow in xs: `undefined`

However, according to ECMA262 specification([http://ecma-international.org/ecma-262/11.0/](http://ecma-international.org/ecma-262/11.0/)), the code should throw an **Error**.

### Details
In [13.7.5.11 Runtime Semantics: LabelledEvaluation](http://ecma-international.org/ecma-262/11.0/#sec-for-in-and-for-of-statements-runtime-semantics-labelledevaluation), first, [13.7.5.12 Runtime Semantics: ForIn/OfHeadEvaluation](http://ecma-international.org/ecma-262/11.0/#sec-runtime-semantics-forinofheadevaluation) is called.
In ForIn/OfHeadEvaluation, the step 6.a~c will be executed.
Therefore, the iterator will contains **next**method which iterates over enumerable properties of String object.
Since String object contains a set of enumerable properties as described in [21.1.4 Properties of String Instances](http://ecma-international.org/ecma-262/11.0/#sec-properties-of-string-instances), the example should throw an **Error**.

NOTE: The following is the result of Node v14.5.0
```
# node -e "'use strict'; var x = undefined; for ( x in 'str' ) throw Error(42); print(JSON.stringify(x));"
[eval]:1
'use strict'; var x = undefined; for ( x in 'str' ) throw Error(42); print(JSON.stringify(x));
                                                    ^

Error: 42
    at [eval]:1:59
    at Script.runInThisContext (vm.js:131:18)
    at Object.runInThisContext (vm.js:295:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at evalScript (internal/process/execution.js:98:25)
    at internal/main/eval_string.js:23:3
```

**Comment by phoddie** [comment]
> The for-in statement failed to promote the string literal to a String instance

Fixed.
