### ISSUE TITLE
Spec. Mismatch: Cannot parse Destructuring assignment - ObjectAssignmentPattern

### ISSUE THREAD

**Issue by Reinose** [Moddable-OpenSource/moddable#410]
### Environment
```
# uname -a
Linux reinose-ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# xs -v
XS 10.3.0
```

### Bug description
```JavaScript
'use strict';
var x = undefined;
({x: (x)} = {x: 42});
print(JSON.stringify(x));
```
The above JavaScript code produces an exception as follow in xs: `SyntaxError: no reference`

However, according to ECMA262 specification([http://ecma-international.org/ecma-262/11.0/](http://ecma-international.org/ecma-262/11.0/)), the code should result in: `42`

### Details
The above expression should be parsed.
```
AssignmentExpression: LeftHandSideExpression = AssignmentExpression

AssignmentPattern: ObjectAssignmentPattern
ObjectAssignmentPattern: { AssignmentPropertyList }
AssignmentPropertyList: AssignmentProperty
AssignmentProperty: PropertyName : AssignmentElement

AssignmentElement: DestructuringAssignmentTarget Initializer_opt
DestructuringAssignmentTarget: LeftHandSideExpression
LeftHandSideExpression: NewExpression
NewExpression: MemberExpression
MemberExpression: PrimaryExpression
PrimaryExpression: CoverParenthesizedExpressionAndArrowParameterList
CoverParenthesizedExpressionAndArrowParameterList: ( Expression )
...
```
_LeftHandSideExpression_ is re-parsed using _AssignmentPattern_ in [12.15.4 Runtime Semantics: Evaluation](http://ecma-international.org/ecma-262/11.0/#sec-assignment-operators-runtime-semantics-evaluation).
_c.f._ The below code works well.
```JavaScript
'use strict';
var x = undefined;
({x: x} = {x: 42});
print(JSON.stringify(x));
```

NOTE: The following is the result of Node v14.5.0
```
# node -e "'use strict'; var x = undefined; ({x: (x)} = {x: 42}); console.log(JSON.stringify(x));"
42
```

**Comment by phoddie** [comment]
> Parenthesized expressions with a single item can indeed be a destructuring target in an object pattern

Fixed.
