### ISSUE TITLE
Spec. Mismatch: Array.prototype.slice does not work as specification

### ISSUE THREAD

**Issue by Reinose** [Moddable-OpenSource/moddable#411]
### Environment
```
# uname -a
Linux reinose-ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# xs -v
XS 10.3.0
```

### Bug description
```JavaScript
'use strict';
var x = Array . prototype . slice . call ( (a, b, c) => {} ) ;
print(JSON.stringify(Object.getOwnPropertyNames(x)))
```
The above JavaScript code produces a result as follow in xs: `["0","0","0","length"]`

However, according to ECMA262 specification([http://ecma-international.org/ecma-262/11.0/](http://ecma-international.org/ecma-262/11.0/)), the code should result in: `["length"]`

### Details
In [22.1.3.25 Array.prototype.slice ](http://ecma-international.org/ecma-262/11.0/#sec-array.prototype.slice), since function object has length property, it goes into the while loop starting from the step 10.
Function object does not have properties such as **0** and **1**, it never creates data properties.
Hence, the result object only contains **length** property.

NOTE: The following is the result of Node v14.5.0
```
# node -e "'use strict'; var x = Array . prototype . slice . call ( (a, b, c) => {} ) ; console.log(JSON.stringify(Object.getOwnPropertyNames(x)));"
["length"]
```

**Comment by phoddie** [comment]
This problem occurs as reported in xst with both -m and -s. However, it does not occur when running the same test inside `$MODDABLE/examples/helloworld`.
