### ISSUE TITLE
Spec. Mismatch: new.target in generator function does not work

### ISSUE THREAD

**Issue by Reinose** [Moddable-OpenSource/moddable#413]
### Environment
```
# uname -a
Linux reinose-ubuntu 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# xs -v
XS 10.3.0
```

### Bug description
```JavaScript
'use strict';
function * x ( ) { new . target } ;
x ( ) ;
throw Error(42);
```
The above JavaScript code produces an exception as follow in xs: `SyntaxError: invalid new.target`

However, according to ECMA262 specification([http://ecma-international.org/ecma-262/11.0/](http://ecma-international.org/ecma-262/11.0/)), the code should throw **Error(42)**

### Details
The **Syntax Error** rules related to `new.target` start from [15.1.1 Static Semantics: Early Errors](http://ecma-international.org/ecma-262/11.0/#sec-scripts-static-semantics-early-errors).
In [14.4.4 Static Semantics: Contains](http://ecma-international.org/ecma-262/11.0/#sec-generator-function-definitions-static-semantics-contains), Contains semantics about _Generator Function Definition_ always return **false**, so that no syntax error occur.

NOTE: The following is the result of Node v14.5.0
```
# node -e "'use strict'; function * x ( ) { new . target } ; x ( ) ; throw Error(42);"
[eval]:1
'use strict'; function * x ( ) { new . target } ; x ( ) ; throw Error(42);
                                                          ^

Error: 42
    at [eval]:1:65
    at Script.runInThisContext (vm.js:131:18)
    at Object.runInThisContext (vm.js:295:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at evalScript (internal/process/execution.js:98:25)
    at internal/main/eval_string.js:23:3
```

**Comment by phoddie** [comment]
> Since generators throw when used as constructors, XS expected the usage of new.target in generators to be an error. But it is not, it is just undefined.

Fixed.
