### ISSUE TITLE
Memory crash on exceptions in timer callback

### ISSUE THREAD

**Issue by eco747** [Moddable-OpenSource/moddable#42]
module/base/timer/modTimer.c : xs_timer_callback function should take care of exceptions in callback call because in case of exception fxForget is not called but c_free is.

more generally exceptions are not handled in timer callback and that not really good. They should also be traced somewhere.

code should be 
```
        xsBeginHost(ts->the);

		xsTry {
			xsCallFunction1(xsReference(ts->callback), xsGlobal, ts->self);
		}
		xsCatch {
			//xsStringValue message = fxToString(ts->the,&xsException);
			//xsDebugLog( message );
		}

		if (0 == modTimerGetSecondInterval(timer)) {
			xsForget(ts->self);
			ts->callback = NULL;
		}

	xsEndHost(ts->the);
```

**Comment by phoddie** [comment]
Good catch. It may be enough to reorganize the code as follows:

	xsBeginHost(ts->the);
		xsCallFunction1(xsReference(ts->callback), xsGlobal, ts->self);
	xsEndHost(ts->the);

	if (0 == modTimerGetSecondInterval(timer)) {
		xsForget(ts->self);
		xsmcSetHostData(ts->self, NULL);
	}

An unhanded exception stops at `xsEndHost`. The implementation of [xsEndHost logs](https://github.com/Moddable-OpenSource/moddable/blob/cf07a0f4c378d32e504eeaa0007a8cd2a1468707/xs/includes/xs.h#L1164) unhanded exceptions.

**Comment by eco747** [comment]
good choice

**Comment by phoddie** [comment]
Fix integrated
