### ISSUE TITLE
Property descriptor for set/get is different

### ISSUE THREAD

**Issue by f52985** [Moddable-OpenSource/moddable#421]
Build environment
macOS version 10.15.6
xst version XS 10.3.0

Bug Description
Property descriptor's name for set/get is different with expected result

When the following code is executed,
```js
var x = Object . defineProperty ( { } , "p" , { [ "get" ] : ( ) => { } , [ "set" ] : ( x ) => { } } ) ;
print(Object.getOwnPropertyDescriptor(x, "p").get.name);
print(Object.getOwnPropertyDescriptor(x, "p").set.name);
```
the result is as following:
get p
set p

but the expected result is as following:
get
set

**Comment by phoddie** [comment]
This same problem is found by test262. The fix is complex, so we have deferred it.
