### ISSUE TITLE
NMAKE fails to build TypeScript example

### ISSUE THREAD

**Issue by JanVanBraeckel** [Moddable-OpenSource/moddable#437]
**Build environment:** Windows
**Target device:** NodeMCU ESP8266.

**Description**
NMAKE fails when trying to build the helloworld example in **TypeScript**

Console output:
```
mcconfig -m -d -p esp
NMAKE : fatal error U1073: don't know how to make '%MODDABLE%\build\tmp\esp\debug\helloworld\modules\main.js'
Stop.
```

main.ts:
```
debugger;

let message = "Hello, world - TypeScript";
trace(message + "\n");

```

manifest.json:
```
{
	"include": [
		"$(MODDABLE)/examples/manifest_base.json",
		"$(MODDABLE)/examples/manifest_typings.json"
	],
	"modules": {
		"*": [
			"./main"
		]
	},
}
```

(Moddable env variable substituted for privacy)

**Steps to Reproduce**
1. Rename main.js to main.ts in the helloworld example
2. Add type declaration files to the include array
3. Run the build using mcconfig -m -d -p esp

**Expected behavior**
The build does not fail

**Comment by andycarle** [comment]
Thank you for the report. I have confirmed the build error on Windows and we are investigating a fix.

**Comment by andycarle** [comment]
@JanVanBraeckel We have pushed changes to fix support for TypeScript in Windows builds. You will need to pull the changes and then re-build the Moddable SDK tools to get the fixes. 

Please give it a shot and let me know how it goes. Thank you again for the report!

&nbsp;- Andy

**Comment by JanVanBraeckel** [comment]
@andycarle Works perfectly now without errors, thank you for looking into this and props for the quick resolution!
