### ISSUE TITLE
The 'mcconfig' command error

### ISSUE THREAD

**Issue by Hebiao19** [Moddable-OpenSource/moddable#438]
Hi,guys!

The 'mcconfig' command error threw by Windows terminal when i enter 'mcconfig -d -m -p win' for the example 'helloworld', it says that:

**'mcconfig'is not recognized as an internal or external command, operable program or batch file**

I followed every step by the Get Started guide, here is my system environment variable for PATH:
C:\%MODDABLE%\build\bin\win\release

Check many possibilities, but still failed!

Expect your help, Thanks very much!

**Comment by andycarle** [comment]
Hi @Hebiao19, let's see if we can get you up and running here. 

To build with the Moddable SDK on Windows, you need to make two changes to environment variables: 

- First, you must define MODDABLE and set it to the path where you cloned the Moddable SDK.
- Second, you add %MODDABLE%\build\bin\win\release to your PATH.

It looks like you may have a typo in your PATH variable. You have `C:%MODDABLE%\build\bin\win\release` when it should just be `%MODDABLE%\build\bin\win\release`. The `C:` part is already in the MODDABLE variable.

Please try that change and let me know how it goes.

Cheers!
&nbsp;- Andy

**Comment by Hebiao19** [comment]
> Hi @Hebiao19, let's see if we can get you up and running here. 
> 
> 
> 
> To build with the Moddable SDK on Windows, you need to make two changes to environment variables: 
> 
> 
> 
> - First, you must define MODDABLE and set it to the path where you cloned the Moddable SDK.
> 
> - Second, you add %MODDABLE%\build\bin\win\release to your PATH.
> 
> 
> 
> It looks like you may have a typo in your PATH variable. You have `C:%MODDABLE%\build\bin\win\release` when it should just be `%MODDABLE%\build\bin\win\release`. The `C:` part is already in the MODDABLE variable.
> 
> 
> 
> Please try that change and let me know how it goes.
> 
> 
> 
> Cheers!
> 
> &nbsp;- Andy

Hello Andy!

     Thanks so much for your time on my trouble! Unfortunately that I have tried as you told, but the same error still exist!

**Comment by andycarle** [comment]
@Hebiao19 Could you dump the contents of your environment variables in the console and paste them here? (Feel free to edit out any sensitive information.) That way I can take a look at your environment to see if I can find the problem.

You can print out all of the environment variables by using the `set` command (with no arguments) at the command prompt.

**Comment by Hebiao19** [comment]
> @Hebiao19 Could you dump the contents of your environment variables in the console and paste them here? (Feel free to edit out any sensitive information.) That way I can take a look at your environment to see if I can find the problem.
> 
> 
> 
> You can print out all of the environment variables by using the `set` command (with no arguments) at the command prompt. 

@andycarle Ok! I will do that after i finish my business trip.

**Comment by phoddie** [comment]
Is there an update to this? If not, we'll close this out.

**Comment by Hebiao19** [comment]
Hello, Phoddie, Sorry for late response! You can close the topic now. Thank you!
