### ISSUE TITLE
Listing on http://esp32.net/

### ISSUE THREAD

**Issue by wilberforce** [Moddable-OpenSource/moddable#444]
You should get a listing on the http://esp32.net page.

You can list projects and perhaps even metion your Moddable book?

**Comment by phoddie** [comment]
You're right. We should. Do you have a contacts there or do we just reach out to them on Twitter?

**Comment by wilberforce** [comment]
@phoddie 

Sorry - no contacts.

**Comment by lprader** [comment]
I reached out to [@ESP32net](https://twitter.com/ESP32net) on Twitter about this last week. I'm still waiting to hear back, but I'll try again soon if I don't get a reply.

**Comment by phoddie** [comment]
We did hear back from @ESP32net that an update is forthcoming. Fingers crossed.

**Comment by phoddie** [comment]
This was a great idea. And it seems we failed to get @ESP32net to make the requested addition. Alas.
