### ISSUE TITLE
readJPEG doesn't handle config.rotation well.

### ISSUE THREAD

**Issue by basuke** [Moddable-OpenSource/moddable#456]
**Description**
When adding rotation to `config` of the manifest, the result drawing is wrong. Each blocks is draws as if they are not rotated.

<img width="288" alt="Screen Shot 2020-09-18 at 11 30 34 AM" src="https://user-images.githubusercontent.com/42601/93632568-60aa1980-f9a2-11ea-8a15-16cf97857978.png">

**Project**
https://gist.github.com/basuke/53f8b3be5bc49b3dbe48719d06304794

**Comment by phoddie** [comment]
Correct. The JPEG decoder does not implement rotation. Therefore, it does not work with software rotation.

Both Moddable One and Moddable Two support hardware rotation. That will work with the JPEG decoder. Our blog post, [Run-time Display Rotation](https://blog.moddable.com/blog/rotate/), explains how to use hardware rotation.

**Comment by basuke** [comment]
Thanks!
