### ISSUE TITLE
Example "jpeghttp" fails because the url is redirected to its secure site.

### ISSUE THREAD

**Issue by basuke** [Moddable-OpenSource/moddable#458]
**Build environment:** macOS
**Target device:** Moddable One

**Description**
I'm building examples/commodetto/jpeghttp app for Moddable One. It fails when run.

**Steps to Reproduce**
1. `mcconfig -d -m -p esp/moddable_one ssid=SuzukiWiFi password=$SECRET_PASSWORD`
2. Wait xsbug come up.
```
Wi-Fi connected to "SuzukiWiFi"
IP address 192.168.186.5
date: Tue, 22 Sep 2020 18:15:27 GMT
server: Apache
location: https://www.moddable.com/example/images/example1.jpg
content-length: 326
content-type: text/html; charset=iso-8859-1
connection: close
326
/Users/basuke/work/moddable/modules/commodetto/commodettoReadJPEG.c (153) # Break: JPEG: jpeg init failed!
```
The content is redirect response to the secure version of JPEG image.

**Comment by phoddie** [comment]
Oops. Best practices for web sites are not best practices for graphics examples.

We set-up test.moddable.com without the https redirect. Change "www.moddable.com" to "test.moddable.com" here:

https://github.com/Moddable-OpenSource/moddable/blob/54d8e94710ed6f8c310f046c4fbc83c967ccd346/examples/commodetto/jpeghttp/main.js#L22

Then it works (confirmed on Moddable One).

(We'll push an update to the example in the coming days.)

**Comment by basuke** [comment]
Thanks!
