### ISSUE TITLE
How to run 'mcrun' command

### ISSUE THREAD

**Issue by LongNguyen1984** [Moddable-OpenSource/moddable#466]
Do you have questions about

I try to run the example for helloworld from 'mcrun -d -m -p esp32'
but it return to:
### TypeError: cannot coerce undefined to object

How to fix it?

**Comment by phoddie** [comment]
(Closing as duplicate of an [issue](https://github.com/Moddable-OpenSource/iot-product-dev-book/issues/2) in another repository.)
