### ISSUE TITLE
Change setjmp() to _setjmp() in xsTry and xsBeginHost macros in xs.h header for MinGW compatibility

### ISSUE THREAD

**Issue by iamtakingiteasy** [Moddable-OpenSource/moddable#47]
Please do. Otherwise, when crosscompiling, MinGW fails preprocessing complaining about incorrect number of arguments.

Also, what is your policy on pull requests? I've tried to submit this trivial patch twice, but both times got overridden by forced push into public branch from someone's local repo.

**Comment by phoddie** [comment]
This seems  to have languished for a long time. Apologies.

If there is still an issue, we would be happy to accept a PR to resolve it. (PR's are welcome. We ask that you [sign our CLA](https://github.com/Moddable-OpenSource/moddable/tree/public/licenses) first.)
