### ISSUE TITLE
Invalid JSON is manifest.json module

### ISSUE THREAD

**Issue by erights** [Moddable-OpenSource/moddable#476]
https://github.com/Moddable-OpenSource/moddable/blob/6165841a7725bc6488528d43704ca822204451b1/examples/helloworld/manifest.json#L7

The JSON grammar does not include trailing commas.

**Comment by phoddie** [comment]
Yes, we keep meaning to fix that. We should actually follow through. ;)

**Comment by dckc** [comment]
I plan to verify this; especially to check whether any of the manifests I added to agoric-sdk have trailing commas.
