### ISSUE TITLE
Support for BLE on ESP32?

### ISSUE THREAD

**Issue by dariosalvi78** [Moddable-OpenSource/moddable#48]
I couldn't find anything in the documentation. Is it supported?

**Comment by phoddie** [comment]
Funny you should ask. We have recently been looking into adding a JavaScript interface to BLE on ESP32. No ETA yet though.

**Comment by dariosalvi78** [comment]
thanks, it would be a great addition to the framework...
(BTW, there's some [preliminary work](https://github.com/espruino/Espruino/issues/1208) done around Espruino for ESP32, unofficial support still, but maybe can turn out to be useful)

**Comment by phoddie** [comment]
Is there a particular use of BLE you are interested in?

**Comment by dariosalvi78** [comment]
I guess ble server would be the first need, like to send messages to a phone or something like that

**Comment by phoddie** [comment]
Lots of BLE support arrived last week. Details are on out [blog](http://blog.moddable.tech/blog/ble/). Documentation is in [this repository](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/network/ble/ble.md#ble). Please give it a try.
