### ISSUE TITLE
Can not get the SDK running on Windows 10

### ISSUE THREAD

**Issue by MarcelisProgramming** [Moddable-OpenSource/moddable#491]
Sorry, but the instructions to set up the environment are not very clear.

**Comment by phoddie** [comment]
We are happy to help try to resolve the problem. For us to be able to help, you will need to provide specific information about the problems you are having. What is it that is unclear to you?

Many people have successfully set-up the Moddable SDK on Windows. It can be done.

**Comment by andycarle** [comment]
Hi @MarcelisProgramming,

(Looking back through your edits to try to understand the sticking point here.) The Windows environment variables should be set through the Control Panel app. Please follow [this guide](https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/) if you are unfamiliar with this process.

And thank you for the feedback on the instructions—I have clarified the Windows environment variables sections in an upcoming revision of our Getting Started documentation. 

Cheers!
&nbsp;- Andy

**Comment by MarcelisProgramming** [comment]
Hi,
Everything is going now, except that I can't get the compiling for ESP32 running.
I do exactly as the instructions say, but keep getting this error while compiling, and everything stops.
Hope you have some tips.
Kind regards,
Marcel
![2020-11-01 00_50_14-moddable_Moddable SDK - Getting Started md at public · Moddable-OpenSource_modda](https://user-images.githubusercontent.com/72037375/97792312-e4c80180-1bdc-11eb-95b4-94405860bf7a.jpg)

**Comment by MarcelisProgramming** [comment]
Hello,
I got it working now.
Thank you guys!
Kind regards,
Marcel :-)

**Comment by andycarle** [comment]
Hi @MarcelisProgramming,

Great! I'm glad to hear that you got everything fixed up. Out of curiosity: what was the issue that was causing the `0x2331` error you posted above? 

&nbsp;- Andy

**Comment by MarcelisProgramming** [comment]
Hi Andy,
Something must have gone wrong while installing the ESP-IDF Tools Installer. Maybe the downloaded file was corrupted or something. After I repeated the installationproces with a new downloaded file, it worked well.
Marcel

**Comment by andycarle** [comment]
Great; thank you for the info. 

I'm going to go ahead and close this out. Feel free to re-open the issue if you have any further problems!

&nbsp;- Andy
