### ISSUE TITLE
Is loadmod ready for use?

### ISSUE THREAD

**Issue by wilberforce** [Moddable-OpenSource/moddable#495]
I'm trying to follow: https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/mods.md

and files from here:
https://github.com/Moddable-OpenSource/iot-product-dev-book/tree/master/loadmod

The UPLOAD_SPEED and UPLOAD_PORT (defaults to COM8) does not get read from the board default manifest by `mcrun` like `mcconfig` does.

`mcrun -d -m -p esp32/m5stick_c`

```
F:\Projects\M5c-tilt\www>set VERBOSE=1

F:\Projects\M5c-tilt\www>mcrun -d -m -p esp32/m5stick_c
# xsc main.xsb

        tasklist /nh /fi "imagename eq serial2xsbug.exe" | (find /i "serial2xsbug.exe" > nul) && taskkill /f /t /im "serial2xsbug.exe" >nul 2>&1
        tasklist /nh /fi "imagename eq xsbug.exe" | find /i "xsbug.exe" > nul || (start F:\Projects\moddable\build\bin\win\debug\xsbug.exe && echo Starting xsbug... && timeout /nobreak /t 7 > nul)
        F:\Projects\moddable\build\bin\win\debug\serial2xsbug COM3 460800 8N1 -install F:\Projects\moddable\build\bin\esp32\debug\www\www.xsa
```

This defaults to the moddable 2 speed - and when I manually try to run using the 1500000 Buad rate - I seen nothing in xsbug and the script does not finish.

a. Is there a compete example with a host and a mod?

b. Does this work with the simulator? Is there anywhere the mods are installed for the simulator?

Thanks

**Comment by phoddie** [comment]
Mods work well. You'll hearing more about those from us soon.

That said, I haven't tried them (recently, al least) on a device that uses a baud rate of 1500000.

There are lots of examples [here](https://github.com/Moddable-OpenSource/iot-product-dev-book). I suggest starting with the Chapter 10 host and graph example. It works on devices (Moddable One, Moddable Two, M5Stack Fire) and the simulator.

![Screen Shot 2020-11-15 at 9 01 39 PM](https://user-images.githubusercontent.com/6856458/99214771-e0c3e400-2785-11eb-8dd4-7a5f44ab966b.png)

**Comment by wilberforce** [comment]
Thanks.

here is a PR for the `$DEBUGGER_SPEED`

https://github.com/Moddable-OpenSource/moddable/pull/496
