### ISSUE TITLE
compartment.evaluate SyntaxError line numbers

### ISSUE THREAD

**Issue by kriskowal** [Moddable-OpenSource/moddable#512]
When evaluating a string that does not parse as valid JavaScript, `evaluate` throws a `SyntaxError`. It would be useful, at least in debug mode, if that syntax error mentioned the position of the error within the given string, ideally `line:column`, better `sourceURL:line:column`, taking a `//#sourceURL=` comment at the end of the file into account.

The behavior I’m observing instead is a line in the XSBug console:

```
# Error: missing ,!
```

**Comment by phoddie** [comment]
I believe this has been resolved by the changes in how XS handles the source text of eval when debugging. Please confirm.
