### ISSUE TITLE
Build option for runtime symbols of dynamically evaluated code

### ISSUE THREAD

**Issue by kriskowal** [Moddable-OpenSource/moddable#515]
**Describe**
Stack traces in XSBug name frames according to the function called, but for code run by `eval`, all such frames are marked `?`. Is there a way to build an XS executable that will show symbols for code evaluated at run-time?

<img width="320" alt="Screen Shot 2020-12-11 at 1 50 24 PM" src="https://user-images.githubusercontent.com/60294/101958313-ee6b5e80-3bb7-11eb-868e-5dc84ae85b69.png">

**Why do you think this feature would be useful?**
At @agoric, we need a single executable that can execute arbitrary applications. With our current experiment, the application code is not inspectable in a debugger.

**Describe alternatives you've considered**
We’ve decided against compiling whole applications into unique executables since this would entrain the compiler in our trusted compute base, and because we have some CommonJS dependencies that are cost prohibitive to eliminate entirely, particularly the stand-alone version of the Babel parser framework. We also considered depending on Babel directly since it is ESM, but it entrains Node.js-specific built-in modules.

**Comment by phoddie** [comment]
@kriskowal - Apologies if this response is naive. Please see the attached screen shot. The function names are shown in the stack frames of evaluated code. What am I missing?

<img width="732" alt="Screen Shot 2020-12-11 at 2 39 16 PM" src="https://user-images.githubusercontent.com/6856458/101961656-0692ac00-3bbf-11eb-92ac-85088247b28b.png">

**Comment by kriskowal** [comment]
Curious. I’ll attempt a tighter isolation.

**Comment by kriskowal** [comment]
I was unable to reproduce named stack frames in isolation.

![image](https://user-images.githubusercontent.com/60294/101963578-e31e3000-3bc3-11eb-8f89-186c7c5889c5.png)

Platform: Mac OS X.15.7 (Catalina). Moddable base branch `9b2399f5` + changes to add TextEncoder and TextDecoder. The manifest is unremarkable except an oversized creation block. XS platform is default, `mac`.

**Comment by phoddie** [comment]
Note that XS does have an option to exclude the `name` and `length` properties from functions. We use that to reduce flash size, since those properties are generally not needed. I'm not sure that is relevant here.

Something is different between our builds. My test run was run by replacing the source of $MODDABLE/examples/helloworld/main.js and then running the usual `mcconfig -d -m`. If you do the same, what is your result?

**Comment by kriskowal** [comment]
I’ve taken the liberty of checking out `public` aka `9b2399f522f23d8fb812200e79ee99dd8d9f670f` and rebuilt Moddable tools.

Looks good in place!

![image](https://user-images.githubusercontent.com/60294/101964230-8f144b00-3bc5-11eb-80ca-04a4e6c9ff72.png)

If I delete our `creation` block in `manifest.json`, I see symbols in the stack trace! Looks like we just need to navigate to a creation block that has enough room for the run-time symbol table.

**Comment by phoddie** [comment]
@kriskowal - curious, but good. ;) If this issue makes a return, just let us know.

**Comment by kriskowal** [comment]
Sure thing. I’ve yet to come up with a creation block that turns the ?’s into names for our non-trivial 3MB bootstrap source, so I’m going to spend some time getting to know creation block docs.

**Comment by phoddie** [comment]
Yea, that's part of what I don't completely understand. If XS fails to allocate memory (for example, for a function name), it doesn't continue - it ends up in `fxAbort` and exit. It lands there if the symbol table is full too. So, perhaps there's something else going on here.

**Comment by kriskowal** [comment]
For reference, this isn’t enough yet — mind that I’m blindly doubling numbers:

```json
	"creation": {
		"static": 32768,
		"chunk": {
			"initial": 1536,
			"incremental": 1024
		},
		"heap": {
			"initial": 1024,
			"incremental": 1024
		},
		"stack": 524288,
		"keys": {
			"available": 4194304,
			"name": 65536,
			"symbol": 65536
		},
		"parser": {
			"buffer": 4194304,
			"table": 4096
		},
		"main": "main"
	}
```

**Comment by kriskowal** [comment]
I believe I need to submit a follow-up issue to capture the underlying problem, and I could use some help framing that issue.

I will be able to eventually share the branch, though I’m sure ideally I would whittle it down or binary search for the bundle size where function names turn to question marks in the debugger. The project branch is riddled with debts, as we try to spike to SES-tests-working-in-XS. The program I’m debugging is a 3MB bootstrapping bundle generated by Rollup, containing our SES shim and Node.js-package-graph to compartment-graph assembler.

I’m going to turn my attention to other debts for a while, but will eventually need to return to this debugging problem. My time is yours if I can help track this down. kris@agoric.com.

**Comment by phoddie** [comment]
Your manifest numbers are kind of crazy. XS is written first for a microcontroller so there are some limits along the way. In particular, there is a hard limit on the number of symbols of 32767. Setting `keys.available` above that is unexpected. :) 

I was able to reproduce a problem similar to yours by adjusting `keys.available`. That value is actually the number of symbols available beyond what is built-in (JavaScript built-ins plus preloads). For hello world, I turned it down to 32000 and everything worked. Somewhere between there and 32767 things go bad.

I didn't need to change any other numbers from your creation record. That said, some of them are staggering (at least from my microcontroller-centric perspective). The stack, for example, is measured in slots not bytes, so your stack is 8 MB on a 32-bit system (and more on a 64-bit system). But, that seems to work.

Anyway... please try adjusting `keys.available` down. It would be good to know if that resolves the problem. We can look at some better error reporting by the tools once we are sure of the problem. Thanks.

**Comment by phoddie** [comment]
I should also mention that `keys.name` is used for hashing the name table. It should be a prime number. It doesn't need to be particularly large. It impacts performance and memory use, but it isn't any kind of functional limit. We use 53 for microcontrollers. For larger systems we use 1993, which is what I'd suggest here.

**Comment by kriskowal** [comment]
Thanks for the details. I’ll try these recommendations out!

**Comment by kriskowal** [comment]
I did get another symbol in my stack trace with these creation block details.

![image](https://user-images.githubusercontent.com/60294/102419009-be56fd80-3fb3-11eb-8a34-21502625088e.png)

**Comment by phoddie** [comment]
Curious. Do those `?` functions have a real name or are they anonymous functions? Also, I see `async` in there. Is any of that pending async functions?

**Comment by kriskowal** [comment]
Ah, indeed. Digging around in the artifact generated by Rollup, there are in fact three IIFE’s before and after createCommonjsModule. So, it would seem this configuration 100% solves the function naming problem.

It would seem that the level up from here would be stack frame line numbers and, if present, the file location from a trailing `//#sourceURL=bootstrap-stage-2.js` comment. I can request that feature separately.

**Comment by phoddie** [comment]
OK, great. One down. ;)
