### ISSUE TITLE
Document "staticSize" machine allocation value

### ISSUE THREAD

**Issue by chances** [Moddable-OpenSource/moddable#521]
The [manifest documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/tools/manifest.md?rgh-link-date=2019-03-11T16%3A06%3A56Z#creation) has removed a reference to the XS in C document and the [machine allocation documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20in%20C.md#machine-allocation) does not explain `staticSize` (i.e. `creation.static` in manifests).

https://github.com/Moddable-OpenSource/moddable/blob/40162325723fa17b1b64158aee645e46ef16ab2d/xs/includes/xs.h#L1119-L1131

See https://github.com/Moddable-OpenSource/moddable/issues/147#issuecomment-748896071

**Comment by phoddie** [comment]
Short answer: for code running on computers (which seems to be your interest?), the `staticSize` field is unused. 

Here's a longer answer that will be added to the XS in C documentation:

> - Some XS hosts attempt to grow the slot and chunk heaps without limit at runtime to accommodate the memory needs of the hosted scripts; others limit the maximum memory that may be allocated to the machine. For the latter, the `staticSize` defines the total number of bytes that may be allocated for the combination of chunks and slots, which includes the stack. In general, only hosts running on resource constrained devices implement `staticSize`.

**Comment by chances** [comment]
@phoddie Thank you for updating the XS in C documentation.

Is this value not what `creation.static` is used for? If so, please also consider documenting that [here](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/tools/manifest.md?rgh-link-date=2019-03-11T16%3A06%3A56Z#creation), too.

**Comment by phoddie** [comment]
> Is this value not what creation.static is used for?

They are the same.

> If so, please also consider documenting that here, too

Sure.

**Comment by phoddie** [comment]
Closing as all requests have been addressed.
