### ISSUE TITLE
Object.prototype[Symbol.toPrimitive] needed in string coercion.

### ISSUE THREAD

**Issue by erights** [Moddable-OpenSource/moddable#524]
Related to #523 

```js
delete Object.prototype[Symbol.toPrimitive];
const o = {
  toString: () => "ok"
};
try {
  console.log(String(o));
} catch (e) {
  console.log('err', e.message);
}
```

Running this program on XS produces `err (host): no function`. But if the first `delete` line is commented out it produces `ok` as it should. The deleted property is non-standard and the behavior of the `String` coercion is specified to work when it does not find such a property. When the program above is run on Node it does produce `ok` as it should.

**Comment by phoddie** [comment]
Yup. We know. ;) Looking into it...

**Comment by erights** [comment]
See https://github.com/Agoric/SES-shim/pull/549

**Comment by phoddie** [comment]
This should now be resolved.

**Comment by erights** [comment]
Verified. Closing.
