### ISSUE TITLE
The syntaxError about illegal token '}' is not thrown as expected

### ISSUE THREAD

**Issue by YaoHouyou** [Moddable-OpenSource/moddable#526]
**Version**: [9ed5514
](https://github.com/Moddable-OpenSource/moddable/commit/9ed551497e76fc79f3e901d5a73fdd8f509233c3) 

**Description**
XS failed to detect illegal token `}` during the parsing phase. And I think it is a bug of XS.

**Test case**
``` js
var NISLFuzzingFunc = function() {
    print("hello");
};
};
var NISLCallingResult = NISLFuzzingFunc();
```
**Command**:
``` bash
./moddable/build/bin/lin/release/xst testcase.js
```

***Behavior***
Neither throws any exceptions nor outputs any other information

**Expected behavior**
Throw a SyntaxError exception, such as `SyntaxError: unexpected token in expression: '}'`

**Build environment:**  Linux

**Build steps**
``` bash
cd $MODDABLE/xs/makefiles/lin
make
```

**Comment by phoddie** [comment]
Good find. We'll take a look. Thank you!
