### ISSUE TITLE
`mcrun` not documented in the tools.md file

### ISSUE THREAD

**Issue by johnwargo** [Moddable-OpenSource/moddable#534]
The `tools.md` file in the documentation folder is missing any reference to the `mcrun` command.

**Comment by phoddie** [comment]
There is now a [description](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/tools/tools.md#mcrun) of `mcrun`.

**Comment by phoddie** [comment]
Documentation updated. Closing.
