### ISSUE TITLE
An issue about calling Object.prototype.hasOwnProperty without parameters

### ISSUE THREAD

**Issue by YaoHouyou** [Moddable-OpenSource/moddable#556]
**Version:**
[9ed5514](https://github.com/Moddable-OpenSource/moddable/commit/9ed551497e76fc79f3e901d5a73fdd8f509233c3)

**Overview:**

According to the specification, calling Object.prototype.hasOwnProperty without parameters should return false. However, XS throws TypeError, which looks like an issue.

**Testcase:**

``` js
var NISLFuzzingFunc = function (e) {	
 	var v = e.hasOwnProperty();
 	print(v);
};
var NISLParameter0 = 'hello';
NISLFuzzingFunc(NISLParameter0);
```

**Actual Results:**

```
TypeError: invalid key.
```

**Expected Results:**

```
false
```

**Comment by phoddie** [comment]
Nice find!

This issue been resolved by [this commit](https://github.com/Moddable-OpenSource/moddable/commit/6492e8c587adf053e009ed41736d93661c0caa22). The commit resolves other related issues.
