### ISSUE TITLE
Startup sound don't work on M5stack

### ISSUE THREAD

**Issue by stc1988** [Moddable-OpenSource/moddable#560]
**Build environment:** Windows
**Target device:** M5stack

**Steps to Reproduce**
1. Build any application using this build command: `mcconfig -d -m -p esp32/m5stack`
2. I can't hear the startup sound when application launch,.

**Comment by wilberforce** [comment]
@stc1988

There was a change to the speaker setup a while back:

https://github.com/Moddable-OpenSource/moddable/commit/ac0732dbb50e6fcb44320e1d7f4b64f80101d08d

```
"config": {
		"screen": "ili9341",
		"touch": "",
		"autorotate": 300,
		"startupSound": "bflatmajor.maud"
	}
```

Are you overriding this in your config?

**Comment by stc1988** [comment]
@wilberforce 
I don't override my config.

https://github.com/Moddable-OpenSource/moddable/blob/157795cbb7b63f17e1c21e0ab1892442f17d755f/build/devices/esp32/targets/m5stack/setup-target.js#L13-L26
I confirmed that `speaker.start()` and `speaker.callback` was called.

And,  I cant'  hear the sound in `example/piu/sound` application,so it seems to `AudioOut` has any problem.

**Comment by andycarle** [comment]
Thank you for the report. 

The speaker and startup sound are working correctly for me on the M5Stack Core2. Curious that it isn't working on the M5Stack. I'll look into it.

**Comment by stc1988** [comment]
Yes, My M5stack Core2 is working correctly too.
It there any way how  debug it?

**Comment by andycarle** [comment]
Do you recall if the startup sound ever worked on your M5Stack? If not, we probably just have a pin number wrong.

I know I've tested the audio on the M5Stack Fire, but I'm not sure I've ever actually used a plain M5Stack.

**Comment by stc1988** [comment]
It was definitely working around November last year.

https://user-images.githubusercontent.com/11245747/107649062-65a89600-6cc0-11eb-9e62-7df5c01927ce.MOV

I think this issue occured since update to ESP‑IDF 4.2

**Comment by andycarle** [comment]
I've pushed a fix to address this. It's working for me on the M5Go, but it could use verification on the original M5Stack.

**Comment by stc1988** [comment]
I saw this issue fixed with my M5stack.
Thank you for your help.
