### ISSUE TITLE
A performance issue caused by regular expression.

### ISSUE THREAD

**Issue by Haobin-Lee** [Moddable-OpenSource/moddable#593]
**Version**:[a461685](https://github.com/Moddable-OpenSource/moddable/commit/a4616854e6692daff6fdb8b6d9d7cbb4dffbfdac) 

**Description**
When repeatedly declaring long regular expression objects, if there are more loops, the execution time of XS much longer than jerryscript.Therefore, I would like to ask about the specific reasons and solutions for this problem.

Their running time is as follows:
[jerryscript](https://github.com/jerryscript-project/jerryscript): `44 ms`
XS: `9220 ms`

**Test case**

```
var NISLFuzzingFunc = function(){
    for(var INDEX = 0; INDEX < 100000; INDEX++){
        var e = /aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/;
    }
}
NISLFuzzingFunc();
```

**Command**:

```
./moddable/build/bin/lin/release/xst testcase.js
```

**Build environment:** Linux

**CPU:**
Intel(R) Core(TM) i9-9940X CPU @ 3.30GHz

**Build steps**

```
cd $MODDABLE/xs/makefiles/lin
make
```

**Comment by phoddie** [comment]
Yes, this garbage collector thrashing is another synthetic example that does not reflect real world use. We would be happy to have a PR that address it, one that does not significantly increase the code size of XS or the memory required for regular expressions.

Meanwhile, this behavior is not getting in the way of embedded systems development with JavaScript. Therefore, it is not a priority. Please see #549 for similar example.
