### ISSUE TITLE
Extra '}' at the bottom of modules/base/cli/commands/archive.js

### ISSUE THREAD

**Issue by dbhaig** [Moddable-OpenSource/moddable#597]
> Note: This template is intended to help organize your report. Feel free to modify it as you need. The most important thing is to file a clear, detailed report, not to follow the template.

> You may use this template to file a report of a security vulnerability. If you prefer to report the issue privately, please send the report by email to info@moddable.com.

**Build environment: Linux
**Target device:All

**Description**
Error thrown when compiling examples/base/console due to an extra '}' at the bottom of modules/base/cli/commands/archive.js

**Steps to Reproduce**
Run console example

**Expected behavior**
That the console example would compile and run

**Images**
Screenshots or photos to help explain the problem

**Other information**
Once the extra '}' was removed the example compiled and ran sucessfully

**Comment by phoddie** [comment]
Thank you for this find from your tour of the examples.

The stray `}` used to be ignored by the parser. Improvements to the parser caused this error to be detected.

**Comment by dbhaig** [comment]
Thanks
