### ISSUE TITLE
How do you specify a module location?

### ISSUE THREAD

**Issue by dbhaig** [Moddable-OpenSource/moddable#598]
Do you have questions about

When I try to run the examples/base/instrumentation/instrumentation xsbug displays an error: module "instrumentation" not found

I'm assuming that there is something missing from the manifest.json file but I am at a loss as to what should be added to the file and the explanation behind it.

Thanks

Feel free to ask us here!

You can also ping us in our [chatroom on Gitter](https://gitter.im/embedded-javascript/moddable). This is a great option if you have a project you'd like to talk about or want to have a longer discussion.

**Comment by phoddie** [comment]
Thanks for the report.

You shouldn't need to do anything for that example to work. The example was broken when the JavaScript instrumentation was removed from the `manifest_base.json`. We'll update the instrumentation example manifests to include it. Meanwhile, you can use this manifest.

```
{
	"include": "$(MODDABLE)/examples/manifest_base.json",
	"modules": {
		"*": [
			"./main",
			"$(MODULES)/base/instrumentation/*"
		]
	},
	"preload": [
		"instrumentation"
	]
}
```

**Comment by dbhaig** [comment]
I can confirm that both instrumentation examples now compile and run. Getting output from xsuse is still a bit of a mystery to me but I assume that all will become clear eventually.

**Comment by phoddie** [comment]
Thanks for confirming. Understanding instrumentation in general, and `xsuse` isn particular, can be a bit challenging as there are providing information about the internal state of the engine.
