### ISSUE TITLE
An issue about the regular expression /[\0-\1]/ and \[\1]\ matching

### ISSUE THREAD

**Issue by Haobin-Lee** [Moddable-OpenSource/moddable#599]
**Version**: [a461685](https://github.com/Moddable-OpenSource/moddable/commit/a4616854e6692daff6fdb8b6d9d7cbb4dffbfdac)

**Description**
When I use \[\0-\1]\ and \[\1]\ to match strings, the matching situation of XS is inconsistent with other engines, such as Jerryscript and quickjs. I think this may be a bug.

**Test case**

```
var Func = function() {
	var reg1 = /[\0-\1]/;
	var reg2 = /[\1]/;
	var str1 = 'hello world\1';
	var str2 = 'hello world1';
	print(str1.search(reg1));
	print(str1.search(reg2));
	print(str2.search(reg1));
	print(str2.search(reg2));
};
Func();
```

**Command**:

```
./moddable/build/bin/lin/release/xst testcase.js
```

***Behavior***
Separately output 5, -1, 5, 11.

**Expected behavior**
Separately output 11, 11, -1, -1.

**Build environment:** Linux

**Build steps**

```
cd $MODDABLE/xs/makefiles/lin
make
```

**Comment by phoddie** [comment]
This is related to the Annex B RegExp grammar, which accepts octal escapes in sloppy mode. XS does not support the Annex B RegExp grammar because XS is not an engine for web browsers. Instead of

```
var reg1 = /[\0-\1]/;
var reg2 = /[\1]/;
```

use

```
var reg1 = /[\0-\u0001]/;
var reg2 = /[\u0001]/;
```
