### ISSUE TITLE
Error Modetto Clock example when using a TTO LilyGo T7789 1.14 " Led Screen See Item #576

### ISSUE THREAD

**Issue by louisvangeldrop** [Moddable-OpenSource/moddable#600]
Since the last conversation I have tried to use the info from TFT-ESP project. 
The setup-file is: Setup25_TTGO_T_Display.h
And the init file: ST7789_Init.h

So I have updated the register-settings as follows:

 [
            "0x11, 0,",
            "0xff, 120,",
            "0x13, 0,",
            "0x36,1,0x08,",
            "0xb6,2,0x0a,0x82,",
            "0x3a,1,0x55,",
            "0xff,10,",
            "0xb2,5,0x0c,0x0c,0x00, 0x33,0x33,",
            "0xb7,1,0x35,",
            "0xbb,1,0x28,",
            "0xc0,1,0x0c,",
            "0xc2,2,0x01,0xFF,",
            "0xc3,1,0x10,",
            "0xc4,1,0x20,",
            "0xc6,1,0x0f,",
            "0xd0,2,0xa4,0xa1,",
            "0xe0,14,0xd0,0x00,0x02,0x07,0x0a,0x28,0x32,0x44,0x42,0x06,0x0e,0x12,0x14,0x17,",
            "0xe1,14,0xd0,0x00,0x02,0x07,0x0a,0x28,0x31,0x54,0x47,0x0e,0x1c,0x17,0x1b,0x1e,",
            "0x21,0,",
            "0x2a,4,0x00,0x00,0x00,0xE5,",
            "0x2b,4,0x00,0x00,0x01,0x3F,",
            "0xff,120,",
            "0x29,0,",
            "0xff,120,"
        ]

However it crashes immediately, when calling the config.Sreen({})

**Comment by phoddie** [comment]
Your message does not indicate what JSON element in the manifest the registers above are contained in. It could be:

```
"registers": [
```

Or 

```
			"registers_append": [
```

If it is `"registers"` then you need to include a terminator in the array after the delay. Without that, the `ili9341Init` function will blindly read memory past your data structure.

```
"0x29,0,",
"0xff,120,"
"0xff,0"
]
```
```

**Comment by louisvangeldrop** [comment]
"defines": {
        "spi": {
            "hz": 40000000,
            "mosi": 19,
            "sck": 18,
            "mode": 3
        },
"ili9341": {
            "spi_port": "HSPI_PORT",
            "width": 135,
            "height": 240,
            "cs_pin": 5,
            "dc_pin": 16,
            "rst_pin": 23,
            "backlight_pin": 4,
            "column_offset": 40,
            "row_offset": 53,
            "registers": [
"0x11, 0,",
"0xff, 120,",
"0x13, 0,",
"0x36,1,0x08,",
"0xb6,2,0x0a,0x82,",
"0x3a,1,0x55,",
"0xff,10,",
"0xb2,5,0x0c,0x0c,0x00, 0x33,0x33,",
"0xb7,1,0x35,",
"0xbb,1,0x28,",
"0xc0,1,0x0c,",
"0xc2,2,0x01,0xFF,",
"0xc3,1,0x10,",
"0xc4,1,0x20,",
"0xc6,1,0x0f,",
"0xd0,2,0xa4,0xa1,",
"0xe0,14,0xd0,0x00,0x02,0x07,0x0a,0x28,0x32,0x44,0x42,0x06,0x0e,0x12,0x14,0x17,",
"0xe1,14,0xd0,0x00,0x02,0x07,0x0a,0x28,0x31,0x54,0x47,0x0e,0x1c,0x17,0x1b,0x1e,",
"0x21,0,",
"0x2a,4,0x00,0x00,0x00,0xE5,",
"0x2b,4,0x00,0x00,0x01,0x3F,",
"0xff,120,",
"0x29,0,",
"0xff,120,"
]}

**Comment by phoddie** [comment]
Thanks. So you need to add the `"0xff,0"` as noted above.

**Comment by louisvangeldrop** [comment]
The Clock example freezes at line 38: render.end()

Manifest.json:

`{
	"include": [
		"$(MODDABLE)/examples/manifest_base.json",
		"$(MODDABLE)/examples/manifest_commodetto.json",
		"$(MODDABLE)/examples/manifest_net.json",
		"$(MODULES)/drivers/st7789/manifest.json"
	],
	"modules": {
		"*": "./main"
	},
	"resources": {
		"*-alpha": "./digits"
	},
	"config": {
		"sntp": "pool.ntp.org",
		"screen": "st7789"
	},
	"defines": {
		"spi": {
			"hz": 40000000,
			"mosi": 19,
			"sck": 18,
			"mode": 3
		},
		"ili9341": {
			"spi_port": "HSPI_HOST",
			"width": 135,
			"height": 240,
			"cs_pin": 5,
			"dc_pin": 16,
			"rst_pin": 23,
			"backlight_pin": 4,
			"column_offset": 40,
			"row_offset": 53,
			"registers": []
		}
	}
}`

**Comment by louisvangeldrop** [comment]
Clock example freeezes at line 38: render.end()

Manifest.json:

{
	"include": [
		"$(MODDABLE)/examples/manifest_base.json",
		"$(MODDABLE)/examples/manifest_commodetto.json",
		"$(MODDABLE)/examples/manifest_net.json",
		"$(MODULES)/drivers/st7789/manifest.json"
	],
	"modules": {
		"*": "./main"
	},
	"resources": {
		"*-alpha": "./digits"
	},
	"config": {
		"sntp": "pool.ntp.org",
		"screen": "st7789"
	},
	"defines": {
		"spi": {
			"hz": 40000000,
			"mosi": 19,
			"sck": 18,
			"mode": 3
		},
		"ili9341": {
			"spi_port": "HSPI_HOST",
			"width": 135,
			"height": 240,
			"cs_pin": 5,
			"dc_pin": 16,
			"rst_pin": 23,
			"backlight_pin": 4,
			"column_offset": 40,
			"row_offset": 53,
			"registers": []
		}
	}
}

**Comment by phoddie** [comment]
I suggested you **add** a line at the end of the `registers` element.  It seems you just **emptied out** the registers element instead. That seems very unlikely to work correctly. 

The $MODDABLE/examples/commodetto/clock example works as expected on Moddable Two and the simulator.

This does not appear to be an issue with the Moddable SDK but, instead, a request for help using the ILI9341 (MIPI) display driver with another display. Therefore, I'm moving this from Issues to Discussions.
