### ISSUE TITLE
Does XS support printing the line number of the exception code

### ISSUE THREAD

**Issue by YaoHouyou** [Moddable-OpenSource/moddable#603]
When compiling XS according to the [tutorial](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20Conformance.md#linux), the exception information of XS does not contain the line number where the exception code is located. This is difficult for code debugging. I would like to ask whether XS supports displaying the line number where the exception code is located in the exception information. If yes, how can I compile XS or how to run `xst`? 
Looking forward to your reply. Thanks.

Testcase:
```
 print(c);
```
Exception Infomation:
```
ReferenceError: get c: undefined variable
```

**Comment by phoddie** [comment]
XS is happy to provide line numbers for errors. The `xst` tool is not designed for debugging, but to run test262 where debugging lines numbers are seldom very useful.

If you launch the xsbug debugger prior to running xst, it will break on exceptions and display the line number.

<img width="971" alt="Screen Shot 2021-03-15 at 2 20 45 PM" src="https://user-images.githubusercontent.com/6856458/111222913-ad5d5e80-8599-11eb-81e4-ea1e9bc6e513.png">

Alternatively, you can use a the recently implemented [Error Stacks proposal](https://github.com/tc39/proposal-error-stacks) to display the stack trace captured at the time of an exception. For example, using this script:

```js
try {
	print(c);
}
catch (e) {
	print(e.stack);
}
```

The output is:

```
$ xst ~/test.js 
ReferenceError: ?: get c: undefined variable
 at (/Users/hoddie/test.js:2)
```
