### ISSUE TITLE
A possible performance issue about array expansion algorithm

### ISSUE THREAD

**Issue by YaoHouyou** [Moddable-OpenSource/moddable#607]
### Overview
XS performed the above test case for  117 minutes, while other engines runs took less than 1 second, such as [jerryscript](https://github.com/jerryscript-project/jerryscript). I would like to know why XS is so slow, is it because of frequent array expansion? If yes, maybe this [issue](https://github.com/facebook/hermes/issues/401) can give some inspiration. Hope it can make some contributions to improve XS.

The execution time of the two resource-constrained JavaScript engine is as follows:
XS: `7053013 ms`
jerryscript: `222 ms`

### Version
771d593

### Build steps
```
cd $MODDABLE/xs/makefiles/lin
make
```
### Testcase
```
var NISLFuzzingFunc = function(size) {
    var array = new Array(size);
    while (size--){
        array[size] = 0;
    }
    print(array.length);
};
var NISLParameter0 = 904862;
NISLFuzzingFunc(NISLParameter0);
```
### Output
```
904862
```
### Execution steps
```
$MODDABLE/build/bin/lin/release/xst testcase.js
```

**Comment by phoddie** [comment]
We agree with the comment in the Hermes issue you thoughtfully reference:

> An easy workaround is to fill the array with undefined before starting to add elements in reverse order

We agree with the sentiment expressed in the issue as well, specifically that Hermes has goals that include "simplicity and [maintaining a] small binary footprint". XS has made different choices from Hermes as our targets are even smaller. We congratulate and support the JerryScript team in making yet a different set of choices, no doubt most appropriate for their goals.

One of the many great things about JavaScript is that the specification is so well written and carefully considered, and that the community has invested so much in conformance tools, that we have many different JavaScript engines with very different runtime characteristics. Developers can choose one that works best for them. For developers who prioritize populating Arrays backwards, XS is not the best choice. ;)

While on the topic, we have recently implemented improvements to XS that make it fast enough to populate dense arrays sequentially forward.

```js
const a = [];
let count = 1_000_000;
let i = 0;
while (count--)
	a[i++] = count;
```
