### ISSUE TITLE
XS: Eval preventing const declaration in the caller scope

### ISSUE THREAD

**Issue by tevador** [Moddable-OpenSource/moddable#64]
Specification:
> Strict mode eval code cannot instantiate variables or functions in the variable environment of the caller to eval. Instead, a new variable environment is created and that environment is used for declaration binding instantiation for the eval code ([18.2.1](http://www.ecma-international.org/ecma-262/6.0/#sec-strict-mode-of-ecmascript)).

```
xst -e "'use strict'; eval('e=1'); const e = 0;"
ReferenceError: ?: set e: already initialized
```
Works with a non-constant variable:
```
xst -e "'use strict'; eval('e=1'); let e = 0;"
```

**Comment by phoddie** [comment]
There was a bug but the report was misleading. It has to fail with both const and let because e is not initialized yet. Fix committed. XS now works like the other engines.
For both
```js
'use strict'; eval('e=1'); const e = 0;
```
and
```js
'use strict'; eval('e=1'); let e = 0;
```
eshost prints:
```
#### JavaScriptCore
ReferenceError: Cannot access uninitialized variable.
#### SpiderMonkey
ReferenceError: can't access lexical declaration 'e' before initialization
#### V8
ReferenceError: Cannot access 'e' before initialization
#### XS
ReferenceError: ?: set e: not initialized yet 
```
