### ISSUE TITLE
Chapter 3 Book examples not working

### ISSUE THREAD

**Issue by k4lzy** [Moddable-OpenSource/moddable#641]
I was able to get the host code loading in the Moddable Two.  When running the following:  ```mcrun -d -m -p esp32/moddable_two ssid="MYSSID" password="MYPASSWORD"```  I get the following error:

```
~/Projects/iot-product-dev-book/ch3-network/host/main.js (46) # Break: (host): import ? not found!
```

This breaks on ```LoadMod.importNow("example");```

Not sure what I am doing wrong. I was able to successfully run the chapter 1 examples with no issues.

Thanks
Mike

**Comment by lprader** [comment]
Thanks for the report! You're not doing anything wrong, there's just a bug in the Moddable SDK. We'll let you know when we've resolved the issue and pushed a fix.

For now, you can roll back to [this commit](https://github.com/Moddable-OpenSource/moddable/commit/a2a38f4625371bbce3e9993a07c4e9bab3d2b8f7) if you'd like to keep running book examples. Be sure to do a clean build of the Moddable SDK tools if you do this.

**Comment by lprader** [comment]
We've pushed a fix, so no need to roll back to that older commit--just update your tree and you should be all set.

**Comment by phoddie** [comment]
Note  that as part of updating your Moddable SDK you'll need to rebuild the Moddable SDK tools. Follow the links to the Updating instructions for your  @computer in our [Getting Started](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/Moddable%20SDK%20-%20Getting%20Started.md#table-of-contents) document if you haven't  done that before.

**Comment by k4lzy** [comment]
Ok thanks

**Comment by k4lzy** [comment]
Works great.  Thanks for the help.
