### ISSUE TITLE
What's the appropriate version of esp-idf to use?

### ISSUE THREAD

**Issue by mikew67** [Moddable-OpenSource/moddable#65]
Followed your Getting started instructions [here](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/Moddable%20SDK%20–%20Getting%20Started.md#esp32-setup) for the Mac and the ESP32.  They directed that the esp-idf toolchain be retrieved from a GitHub [repo](https://github.com/espressif/esp-idf.git).  But with this setup, when building the drag example program, the following warning message is encountered:

`WARNING: Toolchain version is not supported: 1.22.0-75-gbaf03c2
Expected to see version: 1.22.0-80-g6c4433a
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
`

This happens even if you pull the latest changes (one today, bunch on June 14th) from the GitHub repo.
If you go to the ESP-IDF Programming Guide [here](https://esp-idf.readthedocs.io/en/latest/get-started/macos-setup.html#toolchain-setup), it provides a different version of esp-idf, in fact version 1.22.0-80 as cited in the warning.

- What version should be used with the moddable SDK.
- If it's the more recent one, is there a repo (rather than a zip download) available, for easier updating.

TIA,

Mike

**Comment by bfriedkin** [comment]
Mike -

Thank you for the follow-up. 

The warning message comes from the ESP-IDF firmware build and basically means that the ESP-IDF is expecting to be built from a newer GCC toolchain. My guess is that you pulled the ESP-IDF repo but didn't have the most recent GCC toolchain installed. The GCC toolchain can be downloaded [here](https://dl.espressif.com/dl/xtensa-esp32-elf-osx-1.22.0-80-g6c4433a-5.2.0.tar.gz). We also updated the GCC toolchain link in our Getting Started document (Section 5, ESP32 setup for macOS) on June 18.

The warning should go away if you rebuild with the latest toolchain.

We recommend following the ESP32 setup instructions in the Getting Started document. Clone the top-of-tree ESP-IDF and download/install the corresponding GCC toolchain.

Thanks,
Brian
