### ISSUE TITLE
code points above Latin1 are not recognized as white space

### ISSUE THREAD

**Issue by gibson042** [Moddable-OpenSource/moddable#665]
**Environment:** XS 10.5.0

**Description**
In the ECMAScript lexical grammar, [_WhiteSpace_](https://tc39.es/ecma262/#sec-white-space) is defined to include ASCII tab/vertical tab/form feed/space, nonbreaking space, BOM/zero-width nonbreaking space, and any code point with the Unicode property “Space_Separator”, and [_LineTerminator_](https://tc39.es/ecma262/#sec-line-terminators) is any of U+000A LINE FEED, U+000D CARRIAGE RETURN, U+2028 LINE SEPARATOR, and U+2029 PARAGRAPH SEPARATOR. Both are required to be insignificant in between expression tokens, but XS does not seem to recognize _WhiteSpace_ code points above the Latin-1 Supplement block.

**Steps to Reproduce**
1. Evaluate source text like `0 ` (i.e., a numeric literal followed by U+1680 OGHAM SPACE MARK).
2. Check all _WhiteSpace_ and _LineTerminator_ characters (as identified at [unicode.org](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5B%5B%5Cu0009%5Cu000B%5Cu000C%5Cu0020%5Cu00A0%5CuFEFF%5D%5B%3ASpace_Separator%3A%5D+%5B%5Cu000A%5Cu000D%5Cu2028%5Cu2029%5D%5D&g=&i=)):
   ```
   ["0009", "000A", "000B", "000C", "000D", "0020", "00A0",
    "1680", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "200A",
    "2028", "2029", "202F", "205F", "3000", "FEFF"
   ].filter(hex => {
     const cp = String.fromCharCode(parseInt(hex, 16));
     try {
       eval("[true]" + cp + "[0]");
       // No parsing error, suppress code point.
       return false;
     } catch ( ex ) {
       // Parsing error, keep code point.
       return true;
     }
   })
   ```

**Expected behavior**
1. No error.
2. An empty array.

**Actual behavior**
1. _SyntaxError: invalid character 5760_
2. 1680,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,200A,202F,205F,3000,FEFF

**Script**
```sh
$ ./xs -v; cat /tmp/js; ./xs /tmp/js
XS 10.5.0
const ws = ["0009", "000A", "000B", "000C", "000D", "0020", "00A0",
  "1680", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "200A",
  "2028", "2029", "202F", "205F", "3000", "FEFF"
]
const rejected = ws.filter(hex => {
  const cp = String.fromCharCode(parseInt(hex, 16));
  try {
    eval("/x/" + cp);
    // No parsing error, suppress code point.
    return false;
  } catch ( ex ) {
    // Parsing error, keep code point.
    return true;
  }
});
print("rejected: " + rejected);
rejected: 1680,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,200A,202F,205F,3000,FEFF
```

**Comment by gibson042** [comment]
Updated to reflect that this issue is more general than the [regular-expression-specific one in JavaScriptCore](https://bugs.webkit.org/show_bug.cgi?id=227944).

**Comment by phoddie** [comment]
Thank you for the detailed report.  You are absolutely correct that the problem was more general than just `RegExp`.

This is fixed in today's Moddable SDK update. The `xst` binary hasn't been updated yet, so to verify the fix you need to build from sources.
