### ISSUE TITLE
 Benchmarks?

### ISSUE THREAD

**Issue by mikew67** [Moddable-OpenSource/moddable#68]
Folks, do you have any benchmarks that you can share in the following three categories?
1. ESP32 raw hardware vs other SBCs
2. JavaScript vs other languages on the ESP32
3.  Moddable JavaScript vs other implementations
Re application category, does it make sense to think of the ESP32 as a host for a g-code interpreter for a fast 3D printer or router?
TIA,
Mike

**Comment by phoddie** [comment]
Most of this is a little out-of-scope for our work. We do regularly run the test262 suite, the definitive JavaScript language test suite, against XS. The [results](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20Conformance.md) are well above 99% for the current language specification, unmatched by any other engine on any embedded device.

**Comment by diogoviannaaraujo** [comment]
Ive was playing with espruino before I found this project and it feels that moddable is quite faster than espruino on esp32.

Maybe I can post some real benchmarks later
