### ISSUE TITLE
xs: SIGBUS when overloading regexp.prototype.exec

### ISSUE THREAD

**Issue by bakkot** [Moddable-OpenSource/moddable#680]
Mac OS, XS v10.5.0

This is another one of those "I went looking for dumb edge cases" bugs. This didn't come up in real code - it requires code to be _very_ poorly written - and should be prioritized accordingly. Anyway:

```js
let evil = new RegExp;
evil.exec = () => ({ 0: '1234567', length: 1, index: 0 });
'abc'.replace(evil, `$'`);
```
and
```js
let evil = new RegExp;
evil.exec = () => ({ 0: 'x', length: 1, index: 3 });
print('abc'.replace(evil, `$'`));
```
both produce SIGBUS crashes, on my machine. The correct results are the empty string and `abc` respectively.

These exercise an extremely dumb case in [GetSubstitution](https://tc39.es/ecma262/multipage/text-processing.html#sec-getsubstitution): in the `$'` case, there is a `tailPos ≥ stringLength` condition. The strict `>` case there is very strange: it means that you have a match M at position P in string S such that the length of M exceeds the number of code units subsequent to P in S. Obviously this does not make sense, and indeed built-in RegExps can't do this (I am reasonably sure).

But this can be achieved by overriding the `exec` method on a RegExp (something [we have not yet gotten rid of](https://github.com/tc39/proposal-rm-builtin-subclassing)), either (in the first case) by producing a match string which is longer than the input or (in the second case) by producing a nonempty match string at position past where it could have fit in the input.

**Comment by phoddie** [comment]
Hey, @bakkot, that's a great find. Thanks for the report. As you note, this isn't likely a problem for well intentioned scripts. Still, it is a problem we should resolve to defend against malicious scripts.

Both test cases give the same stack trace when the Address Sanitizer is enabled for `xst`. The only difference is the size of the negative length passed to `memcpy`. I'm including the trace here for completeness.

```
==17915==ERROR: AddressSanitizer: negative-size-param: (size=-4)
    #0 0x1019f1d1d in __asan_memcpy (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x5ed1d)
    #1 0x1010a1fb7 in fxPushSubstitutionString xsString.c:1863
    #2 0x100fda526 in fx_RegExp_prototype_replace xsRegExp.c:835
    #3 0x100feee46 in fxRunID xsRun.c:842
    #4 0x10109b366 in fx_String_prototype_withRegexp xsString.c:1613
    #5 0x10108c78b in fx_String_prototype_replace xsString.c:1066
    #6 0x100feee46 in fxRunID xsRun.c:842
    #7 0x100f3d8ed in fxExecuteModules xsModule.c:250
    #8 0x100f4ce05 in fxRunImport xsModule.c:1188
    #9 0x1012072a2 in fxRunModuleFile xst.c:1361
    #10 0x101204bf2 in main xst.c:271
    #11 0x100d34773 in start (xst:x86_64+0x100001773)
```
