### ISSUE TITLE
IDE pour développement 

### ISSUE THREAD

**Issue by pc152** [Moddable-OpenSource/moddable#686]
Bonjour, 

Quel éditeur utiliser sous Windows pour développer avec Moddable.

J'ai suivi toute la procédure d'installation sous Windows et j'ai pu faire le test de compilation et du debug.

Mais je ne comprends pas avec quel editeur on peut développer. 

Merci

**Comment by wilberforce** [comment]
You can use any editor your want - even notepad!

VScode works very well: https://code.visualstudio.com/download 
<https://code.visualstudio.com/download>

**Comment by pc152** [comment]
Ok merci, le fait d'installer Visual studio community n'est que pour les outils de compilation ?

**Comment by wilberforce** [comment]
> Ok merci, le fait d'installer Visual studio community n'est que pour les outils de compilation ?

Yes - for compilation only

This is a complete editor with plugins for javascript:

<https://code.visualstudio.com/download>

**Comment by phoddie** [comment]
This appears to be resolved. Closing. Please re-open if needed.
