### ISSUE TITLE
Upgrading to ESP-IDF 4.2, U1050 error

### ISSUE THREAD

**Issue by avivsiegel** [Moddable-OpenSource/moddable#692]
Hello,

After working for long time with v3.2, I encountered a suspected memory leak in networking; as part of troubleshooting I decided to upgrade all to most recent code, libraries and toolchain, which is now ESP-IDF v4.2.1.
Reinstalling and upgrading worked well to run my code on Win debug mode.

Now ready to run helloworld for my Moddable Two, I encounter the following error - 

 fatal error U1050: Detected ESP-IDF version v4.2.2. Expected ESP-IDF version v4.2.1

Any idea how to progress from here?

Thanks, Aviv.

**Comment by Frida854** [comment]
Look in "discussions" under "config error" maybe it can help you further.

**Comment by avivsiegel** [comment]
Thank you so much!

That did the trick; my Moddable Two is happily running now, and I will watch if the memory leak is still there.
