### ISSUE TITLE
correctness: `-(1 << -1)` evaluates to -2147483648, but should evaluate to 2147483648

### ISSUE THREAD

**Issue by bakkot** [Moddable-OpenSource/moddable#704]
```
$ eshost -s -e ' -(1 << -1)'
#### ChakraCore, engine262, Hermes, SpiderMonkey, V8
2147483648

#### GraalJS, Moddable XS
-2147483648
```

It's definitely supposed to be 2147483648 per spec. Note that XS does correctly say that `1 << -1` is -2147483648.

**Comment by phoddie** [comment]
Alas, an integer optimization edge case. Fortunately, the fix appears to be easy -- take the same code path as -0. That should be in our next update. Thank you.
