### ISSUE TITLE
Support the M5Stack ESP32 Core Ink Development Kit

### ISSUE THREAD

**Issue by braechnov** [Moddable-OpenSource/moddable#705]
**Describe**
Add build support for the [M5Stack ESP32 Core Ink Development Kit](https://shop.m5stack.com/collections/low-power/products/m5stack-esp32-core-ink-development-kit1-54-elnk-display)

**Why do you think this feature would be useful?**
You already support a range of M5 Stack products, it would surely make sense to extend that range and _please_ support this product as well.

**Describe alternatives you've considered**
None considered yet other than having to use Arduino or ESP-IDF

**Comment by phoddie** [comment]
We can take a look. The display driver is likely the most significant part of the effort. We don't have one here. Do you happen to have a spare unit??

**Comment by braechnov** [comment]
If you're prepared to take a look I'll buy you one!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by phoddie** [comment]
All in. Send an email to info@moddable.com and I'll send you our office address.

**Comment by phoddie** [comment]
(Hardware is on the way!)

**Comment by phoddie** [comment]
Hardware arrived. Here's a test pattern drawn using a quick port.

<img src="https://user-images.githubusercontent.com/6856458/135797521-893ef48d-93a6-43af-9af3-75787191accf.JPG" width=300/>

**Comment by phoddie** [comment]
More progress: this image was drawing using Poco. The image shows five levels of gray even though the display has only black and white pixels. The dithering is done in the driver -- Burkes dither here though I intend to switch over to the venerable  [Atkinson dither](https://twitter.com/phoddie/status/1274054350034223104).

<img src="https://user-images.githubusercontent.com/6856458/136071060-b61e70b4-1ad9-4c9a-9ee6-80cc299b382e.jpg" width=260/>

**Comment by tribalmatt** [comment]
Hi Peter,

Are these samples in the SDK?  Did I miss them when I was trying to setup
the Heltec OLED?

Thx,
Matt

**Comment by phoddie** [comment]
@tribalmatt - The M5Core Ink work isn't posted yet. I'll get there in a day or so. There's some work remaining to make it at all generally useful. The [M5Paper](https://github.com/phoddie/m5paper) work is up on my personal site, ahead of migrating over to the Moddable SDK.  Every detail of the M5Paper and M5Core Ink efforts is different, but the structure is almost exactly the same

One big difference from the Heltec/SSD1306 driver you looked at is that both M5Core Ink and M5Paper have display drivers implemented in JavaScript, not C. They use the Ecma-419 APIs to do that. I've been using them as a test bed to explore that. Despite being written in JavaScript, the performance is still quite respectable.

**Comment by phoddie** [comment]
The M5Core Ink port is [available](https://github.com/phoddie/m5core_ink)! It includes an entirely new [display driver](https://github.com/phoddie/m5core_ink/blob/master/targets/m5core_ink/gdew0154m09.js) written using [Ecma-419](https://419.ecma-international.org) IO [APIs](https://419.ecma-international.org/#-9-io-class-pattern) and the new Commodetto [Dither module](https://github.com/Moddable-OpenSource/moddable/blob/public/modules/commodetto/commodettoDither.c). It works well but there's still some bits and pieces to do, so it is in my personal repository for now. The [readme](https://github.com/phoddie/m5core_ink/blob/master/readme.md) explains the details.

**Comment by phoddie** [comment]
Closing as support fro M5Core Ink (and M5Paper) have been merged to the Moddable SDK repository. Enjoy.
