### ISSUE TITLE
Running C commands

### ISSUE THREAD

**Issue by diogoviannaaraujo** [Moddable-OpenSource/moddable#71]
Hi, I would like to know. its possible to run some C code inside my JS?

Im trying to do some serial communication with ESP32 and since theres is no module implementing its hardware serial, Im thinking of playing with playing with the C functions.

**Comment by phoddie** [comment]
Please check out the [XS in C](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20in%20C.md) documentation.

**Comment by diogoviannaaraujo** [comment]
Sorry I missed that, thanks!
