### ISSUE TITLE
`TypeError: super: no constructor` when `prototype.constructor` deleted

### ISSUE THREAD

**Issue by mhofman** [Moddable-OpenSource/moddable#727]
**Build environment:** Linux
**Target device:** XS Test Engine

**Description**
When removing the `constructor` property from the prototype of a derived class, XS can no longer construct instances of that class.

**Steps to Reproduce**
```js
class Foo {}
class Bar extends Foo {}
delete Bar.prototype.constructor;
new Bar(); 
```

**Expected behavior**
No error

**What happened**
```
TypeError: Bar: super: no constructor
```

**Other information**
I'm not sure if a test262 exists for this, but I've verified v8, SM and JSC allow this, and AFAIK this is permitted by the spec.

**Comment by phoddie** [comment]
I won't ask why anyone would want to do that. ;)  We'll take a look. Thank you!
