### ISSUE TITLE
storage size of 'tz' isn' known when building for moddable_two

### ISSUE THREAD

**Issue by ollex** [Moddable-OpenSource/moddable#732]
Hi, I just tried to go through the required setup steps and build the first example following [https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/esp32.md] all without any hiccups, but the final building process with mcconfig -d -m -p esp32/moddable_two  fails because:

/home/linux/ModdableProjects/moddable/xs/platforms/esp/xsHost.c: In function 'modSetTime':
/home/linux/ModdableProjects/moddable/xs/platforms/esp/xsHost.c:663:18: error: storage size of 'tz' isn't known
  struct timezone tz;
               
I don't have a board connected, but that shouldn't matter I guess as the moddable_two storage sizes should be known to the compiler/scripts ?

**Comment by ollex** [comment]
I see something similar for windows in https://github.com/Moddable-OpenSource/moddable/issues/731 so will try to see if I have a different version of esp-idf than 4.31 (installed latest I guess following the instructions) and rebuild...

**Comment by phoddie** [comment]
Please see issue #731. It reports the same issue and explains how to resolve it.

**Comment by ollex** [comment]
Hm - after checking out v4.3.1 and running install.sh again it tells me 
# Reconfiguring ESP-IDF...
/bin/sh: 1: idf.py: not found

**Comment by ollex** [comment]
I did run source export.sh again so not sure what's gone havoc...

**Comment by andycarle** [comment]
~~That sounds like you probably did not re-run export.bat after running install.bat. I'd recommend opening up a new command prompt and running export.bat in it before proceeding.~~ Just saw your note that you did run that. (And realized you're not building on Windows.) 

You might also want to clear out $MODDABLE/build/bin/esp32 and $MODDABLE/build/tmp/esp32.

And I would also recommend opening a new terminal to start over fresh, then sourcing export.sh again.

**Comment by ollex** [comment]
Hm I i will try to clear out the build folder and a new terminal running export.sh again (did that before but to no avail although it reported everything like before when it was running through until the tz size unknown error)

**Comment by ollex** [comment]
that helped - project build complete - great !
