### ISSUE TITLE
worker link error in simulator

### ISSUE THREAD

**Issue by mckidder** [Moddable-OpenSource/moddable#787]
**Build environment:** macOS Catalina and Monterey
**Target device:** simulator

**Description**
After recent commits to modWorker (appears to be 03346898babb914d60e091b9d64d05022d167875), when building code that implements a worker, you are not able to launch the simulator (the debugger also fails to load the worker) with the following error:

> Cannot open "/Users/_user_/Desktop/moddable/build/bin/mac/mc/debug/worker/mc.so"
> dlopen(/Users/_user_/Library/Application Support/tech.moddable.simulator.so, 0x0002): symbol not found in flat namespace '_xs_worker_postfromworkerinstantiator'

**Please note:** To reduce noise from my side, the moddable example from base/worker has been used to reproduce the issue.

**Steps to Reproduce**
1. Clone after commit 03346898babb914d60e091b9d64d05022d167875 was pushed i.e. current master
2. Build ${MODDABLE}/examples/base/worker via 'mcconfig -d -m -p mac'
3. See error

**Expected behavior**
When building prior to commit 03346898babb914d60e091b9d64d05022d167875 (for example tag [OS210826](https://github.com/Moddable-OpenSource/moddable/releases/tag/OS210826)), the simulator will launch and the debugger will show trace messages for 'start worker ${index}'.

**Image**

![moddable_simulator_error](https://user-images.githubusercontent.com/42742046/150425251-e6b231ff-40bd-4aa7-abba-383d3a78a210.png)

**Other information**
As stated, this issue appears in projects that implement a worker from the current master. The base/worker example was cited to remove unintended interactions from outside the Moddable SDK. The simulator failure is exactly the same from the base/worker example and other projects with a worker. This has been observed on both debug and release simulator builds.

**Comment by mckidder** [comment]
Issue verified fixed by linked commit on both the moddable worker example and my project.

Cheers!

**Comment by phoddie** [comment]
Great! Thanks for verifying.
