### ISSUE TITLE
Is there a way to export functions with the '@' syntax in JS files.

### ISSUE THREAD

**Issue by creationix** [Moddable-OpenSource/moddable#81]
I want to be able to export values other than classes.  For example, can I do this?

```js
// utils.js
export function print() @ "my_print"
```

And have `xsc` and `xsl` expose it in a way that I can consume it like this?

```js
import { print } from "utils"
print("Hello XS")
```

**Comment by phoddie** [comment]
I separate the declaration of the native function from the export. For example, in `foo.js`:

```
function foo(bar) @ "xs_my_native_function"

export default foo;
foo();
```

Then import as usual:

`import foo from "foo"`

**Comment by creationix** [comment]
Thanks
