### ISSUE TITLE
XS abort: dead strip at regular expression literal

### ISSUE THREAD

**Issue by stc1988** [Moddable-OpenSource/moddable#841]
**Build environment:** macOS, Windows

**Target device:** desktop simulator, ESP32

**Steps to Reproduce**
Build and install  below code using this build command: `mcconfig -d -m`

```
let regexp = /[a-z]+/;
let match = "test".match(regexp);
```
Application stops with  `XS abort: dead strip` at first line.

**Comment by stc1988** [comment]
I confirmed this issue fixed.
Thank you.

**Comment by phoddie** [comment]
Thanks for the report and quick confirmation!
