### ISSUE TITLE
Question on the HTTP Server sample code

### ISSUE THREAD

**Issue by eltoroit** [Moddable-OpenSource/moddable#845]
[The sample code for the HTTP Get server](https://github.com/Moddable-OpenSource/moddable/blob/3458406d8c63783019e58d03de9e2a7055f1983c/examples/network/http/httpserver/main.js#L21) has this assignment `this.path = value;`

What happens with multiple concurrent requests? Is `this` the server or each independent request?

**Comment by eltoroit** [comment]
Never mind, I find my answer [here](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/network/network.md#callbackmessage-val1-val2-1)

> A new HTTP Request is instantiated for each incoming request. The callback is invoked with `this` set to the callback instance for the request. The callback function may attach properties related to handling a specific request to this, rather than using global variables, to ensure there are no state collisions when there are multiple active requests.

**Comment by eltoroit** [comment]
Thanks for building this awesome SDK!

**Comment by phoddie** [comment]
Thanks for sharing the answer to your question.
