### ISSUE TITLE
Error on include microseconds module

### ISSUE THREAD

**Issue by fernandotetu** [Moddable-OpenSource/moddable#848]
**Build environment:**
MacBook Pro (15-inch, 2017) | Intel Core i7
MacOS Monterey (12.2.1) | Xcode 13.2.1 (Build version 13C100)

**Description**
I'm trying to use the microseconds module. I have included it in my manifest, but the application does not compile. I get the following message:

	...
	# xsc microseconds.xsb
	/Users/fernando/moddable/modules/base/microseconds/manifest.js:2: error: missing ;!
	### 1 error(s) 

I was looking at the manifest.js, and it seems like the manifest.json file. Thus, I ask you this file  manifest.js is right? Then, whether I delete it, everything works correctly. 

**Steps to Reproduce**
1. Declare microseconds into modules entries on the manifest.json
2. Import Time from "time" in your script
3. Call  Time.microseconds
4. Compile the application

**Comment by phoddie** [comment]
The expected way to add the microseconds module is to your project is to include the microseconds manifest in the `include` section of your project's manifest. This is documented in [base.md](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/base/base.md#microseconds-property--optional).

**Comment by fernandotetu** [comment]
Thanks @phoddie 

I had included using `*` and the file (manifest.js) was processed, causing the error. So, I changed the import entry to use only manifest.json instead of * its works properly.
