### ISSUE TITLE
Worker gets stuck in Simulator environment [MAC]

### ISSUE THREAD

**Issue by beckerzito** [Moddable-OpenSource/moddable#866]
**Build environment:** macOS
**Target device:** desktop simulator

**Description**
I have one application that creates a worker. During the simulation on Desktop, I realized that the main virtual machine runs fine (I'm able to check the instrumentation panel getting updated and some debug traces being written on the console).

On the other hand, the worker execution seems to get stuck sometimes. I have a complex worker that when simulating, it creates a WebSocket server to communicate with a web client tool I develop to simulate some external hardware. I realized that sometimes the web simulator loses some packets because the worker was stucked and couldn't answer. 

I tried, then, to implement just a simple worker to understand if that was a problem with my application or if that was an issue on the simulator itself, and I got the same results, worker is not consistent. 

One fun fact is that while I have the focus on the Chrome process, trying to use the web tool, the worker seems to get stuck. Then, If I put the focus on the XSbug again, the worker seems to run normally.

The second fact is that even the Instrumentation panel gets stuck when the worker freezes for some seconds.

Not sure if that is related to the scheduling process of the worker on MAC environemnet. But I'd like to understand if there is some specific action to improve this behavior and make the worker run smoothly in the simulator.

NOTE: I tried with Screen Test.app and MCSIM already.

**Steps to Reproduce**
1. Implemented the following `simpleworker.js`
```
import Timer from "timer"
import Instrumentation from "instrumentation";

class TestClass {
	constructor(a, b){
		this.setValues(a, b);
	}

	setValues(a, b){
		this.a = a;
		this.b = b;
	}

	result(){
		return (this.a * this.b);
	}

}
export default function () {
	let counter = 0;
	let obj = new TestClass(counter, counter);

	Timer.repeat(() => {
		counter++;
		obj.setValues(counter, counter);
		trace("Result: " + obj.result() + "\n #########\n");
		trace("Slots: " + Instrumentation.get(11) + "\n");
		trace("Chunk: " + Instrumentation.get(12) + "\n");
		trace("Garbage Collection: " + Instrumentation.get(14) + "\n");
		trace("Stack peak: " + Instrumentation.get(16) + "\n");
		trace("-----------\n");
	}, 1000);

	self.onmessage = function(msg) {
		self.postMessage({hello: "from simple worker", counter: ++counter});
	}
}
```

3. Initialized that as: 

```
import Worker from "worker";

class MainApp extends Worker {
  constructor() {
    super("simpleworker", {
      allocation: 9128,
      stackCount: 100,
      slotCount: 64
    });
  }
}
```

4. Debug the code for some minutes.

**Expected behavior**
You should see some traces on the console with the Instrumentation data for the worker and the result of the multiplication of `counter * counter` with 1 second period, but what happens is that sometimes the worker gets stuck and then the trace stops for a while.

**Comment by phoddie** [comment]
Modern computer operating systems have complex thread scheduling strategies to balance resources, ensure responsiveness to user interactions, and manage energy use. macOS includes a [App Nap](https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/AppNap.html) feature which throttles threads of apps, especially those in the background.

App Nap puts the simulator to sleep, which blocks the repeating timer in the worker script:

![image](https://user-images.githubusercontent.com/6856458/157113491-267ce431-fb28-4380-a363-6eb0ee470c04.png)

You can disable App Nap on your computer:

```console
defaults write NSGlobalDomain NSAppSleepDisabled -bool YES
```

It may be possible for applications like `mcsim` to programmatically disable App Nap. That's beyond my current knowledge.

> **Note**: To run the examples above, it is necessary add the instrumentation module to the manifest and to invoke the `MainApp` constructor in `main.js`.
