### ISSUE TITLE
Numeric keys larger than 2**24 - 2*20 + 1 are given as the empty string

### ISSUE THREAD

**Issue by bakkot** [Moddable-OpenSource/moddable#87]
Consider the following program:

```js
let obj = {
  [2**24 - 2**20]: 0,
};

let obj2 = {
  [2**24 - 2**20 + 1]: 0,
};


function isEmptyKey(thing) {
  let keys = Reflect.ownKeys(thing);
  if (keys.length !== 1) throw 'too many keys';
  console.log(keys[0] === '');
}

isEmptyKey(obj);
isEmptyKey(obj2);
```

This prints `false, true`. In every other engine, and per [the spec](https://tc39.github.io/ecma262/#sec-ordinaryownpropertykeys), it should be `false, false`. (No one ever hits the error path; that's just for illustration.)

**Comment by phoddie** [comment]
That seems very obscure! Thanks for the report. We'll take a look.

**Comment by bakkot** [comment]
Note that there's an [open question](https://github.com/tc39/ecma262/issues/1242) about the order of `ownKeys` for large integer keys (> 2**32 - 2), though it's not all that closely related to this issue (it's just how I came across it).

**Comment by phoddie** [comment]
Patrick has a fix for this one. We'll push that to GitHub in the next couple days.
