### ISSUE TITLE
WiFiModule Allow PSK instead of password

### ISSUE THREAD

**Issue by MKGaru** [Moddable-OpenSource/moddable#870]
**Describe**
WiFi Module Allow PSK instead of password

**Why do you think this feature would be useful?**
There is a slight security advantage as it avoids storing raw passwords.

**Proposal change**

https://github.com/Moddable-OpenSource/moddable/blob/5df3b556aa18cdefc03fd076b735ac26b4178aeb/modules/network/wifi/esp/modwifi.c#L133

https://github.com/Moddable-OpenSource/moddable/blob/5df3b556aa18cdefc03fd076b735ac26b4178aeb/modules/network/wifi/esp32/xs6wifi.c#L183

remove -1  both files.
(both source use memcpy, not strcpy , because maybe not required terminate null charactor)

I tried on esp32, it works.

ref.
http://jorisvr.nl/wpapsk.html
esp8266/Arduino/pull/1850

**Comment by phoddie** [comment]
Interesting. It is nice that the password wouldn't need to be stored, though the PSK value still allows log-in to the network, so that should still be secured in a real product.

It seems like the password and PSK are not quite the same. I'm not sure if there should be a different name in JavaScript to distinguish those (`config.psk` instead of `config.password`). If everyone else is already overloading password, maybe we should do the same.

**Comment by wilberforce** [comment]
How do you generate the PSK?

**Comment by wilberforce** [comment]
https://www.wireshark.org/tools/wpa-psk.html
[pbkdf2.js](http://anandam.name/pbkdf2/) might be useful - then the same ssid and password in the manifest could be used and they could be converted to the psk for use on the device.

**Comment by phoddie** [comment]
Sorry to be so slow The proposed change makes sense. Even macOS allows a 64 character password, so we should just always do that. This will be included in tomorrow's Moddable SDK update. Thank you!

**Comment by phoddie** [comment]
Closing as the proposed change has been [applied](https://github.com/Moddable-OpenSource/moddable/commit/731df5c8f807240c28cb84413b8f9e5eb13a393d).

**Comment by MKGaru** [comment]
> Closing as the proposed change has been [applied](https://github.com/Moddable-OpenSource/moddable/commit/731df5c8f807240c28cb84413b8f9e5eb13a393d).

Thank you so much!
By the way, you applied for access point ssid & password, but i think should be change sta mode too.

**Comment by phoddie** [comment]
😱

**Comment by phoddie** [comment]
I tried again. ;) Any better?

**Comment by MKGaru** [comment]
Excellent!
It's works.
Thank you for update.
