### ISSUE TITLE
Setup modules not loaded when running in a simulator

### ISSUE THREAD

**Issue by FWeinb** [Moddable-OpenSource/moddable#871]
**Build environment:** macOS
**Target device:** Simulator/m5paper

**Description**
I want to add support for the [`global.power`](https://github.com/Moddable-OpenSource/moddable/blob/5df3b556aa18cdefc03fd076b735ac26b4178aeb/build/devices/esp32/targets/m5paper/setup-target.js#L6-L19) object to the simulator but as the [`Control`-class relies on `screen`](https://github.com/Moddable-OpenSource/moddable/blob/5df3b556aa18cdefc03fd076b735ac26b4178aeb/build/simulators/modules/control.js#L14) I need to execute this during setup. But when adding a `setup/target` module to the `preload`-object in the [manifest.json of the m5paper simulator](https://github.com/Moddable-OpenSource/moddable/blob/public/build/simulators/m5paper/manifest.json) like this:
```js
{
  "modules": {
    	// ...
		"setup/target": "./setup-target"
  },
  "preload": [
 	//  ...
    "setup/target"
  ],
  // ...
}
```
with `setup-target.js`
```js
export default function () {
  trace(`Setup-Target called\n`);
  done();
}
```
the default exported function is never called.  

**Steps to Reproduce**
1. Copy the content of [these files](https://gist.github.com/FWeinb/a83e2a30e26cea0c01ceb4902f3bb35a) to `$MODDABLE/build/simulators/m5paper`
2. Run any of the `$MODDABLE/examples/piu/epaper-*` examples using `mcconfig -d -m -p sim/m5paper`  
3. See that `Setup-Target called` is never printed in the xsbug output. 

**Other information** [Edit]
I had a little more time to investigate this. It looks like the behaviour described in the [setup documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/base/setup.md) is only implemented for the embedded platforms in `$MODDABLE/xs/platforms/*`. But as mods are even working in the simulator I am not quite sure if I am on the right track here. 

Okay, it looks like you are building a shared library that exports the `fxScreenLaunch` function for the use in the simulator with the entry point [here in screen.c](https://github.com/Moddable-OpenSource/moddable/blob/public/build/simulators/modules/screen.c#L310) i think that would be the place to add the "setup/" init like done for the xsHost on an mc. 

Got it working. Here is an initial patch for the Simulator-`screen.c`:
```patch
diff --git a/build/simulators/modules/screen.c b/build/simulators/modules/screen.c
index 50f3ff2e..7c2b65bd 100644
--- a/build/simulators/modules/screen.c
+++ b/build/simulators/modules/screen.c
@@ -307,10 +307,38 @@ static int32_t modInstrumentationStackRemain(xsMachine *the)
 	return (the->stackTop - the->stackPeak) * sizeof(txSlot);
 }
 
+static uint16_t gSetupPending = 0;
+
+static void setStepDone(txMachine *the)
+{
+	gSetupPending -= 1;
+	if (gSetupPending)
+		return;
+
+	xsBeginHost(the);
+	{
+		xsVars(1);
+		xsVar(0) = xsAwaitImport("main", XS_IMPORT_DEFAULT);
+		if (xsTest(xsVar(0))) {
+			if (xsIsInstanceOf(xsVar(0), xsFunctionPrototype)) {
+				xsCallFunction0(xsVar(0), xsGlobal);
+			}
+			else if (xsFindResult(xsVar(0), xsID_onLaunch)) {
+				xsCallFunction0(xsResult, xsVar(0));
+			}
+		}
+		xsCollectGarbage();
+	}
+	xsEndHost(the);
+
+	txScreen* screen = the->host;
+	screen->start(screen, 5);
+}
+
 void fxScreenLaunch(txScreen* screen)
 {
 	static xsStringValue signature = PIU_DOT_SIGNATURE;
-	void* preparation = xsPreparation();
+	txPreparation* preparation = xsPreparation();
 	void* archive = (screen->archive) ? fxMapArchive(preparation, screen->archive, screen->archive, 4 * 1024, fxArchiveRead, fxArchiveWrite) : NULL;
 	screen->machine = fxPrepareMachine(NULL, preparation, strrchr(signature, '.') + 1, screen, archive);
 	if (!screen->machine)
@@ -385,25 +413,41 @@ void fxScreenLaunch(txScreen* screen)
 		xsVar(1) = xsNewHostFunction(screen_get_frameBuffer, 0);
 		xsDefine(xsVar(0), xsID_frameBuffer, xsVar(1), xsIsGetter);
 #endif
-
 		xsSet(xsVar(0), xsID_pixelFormat, xsInteger(kCommodettoBitmapFormat));
 		xsSet(xsVar(0), xsID_when, xsNumber(C_NAN));
 		xsSet(xsGlobal, xsID_screen, xsVar(0));
 
-		xsVar(1) = xsAwaitImport("main", XS_IMPORT_DEFAULT);
-		if (xsTest(xsVar(1))) {
-			if (xsIsInstanceOf(xsVar(1), xsFunctionPrototype)) {
-				xsCallFunction0(xsVar(1), xsGlobal);
-			}
-			else if (xsFindResult(xsVar(1), xsID_onLaunch)) {
-				xsCallFunction0(xsResult, xsVar(1));
+		txInteger scriptCount = preparation->scriptCount;
+		txScript* script = preparation->scripts;
+
+		xsVar(0) = xsNewHostFunction(setStepDone, 0);
+
+		gSetupPending = 1;
+
+		while (scriptCount--) {
+			if (0 == c_strncmp(script->path, "setup/", 6)) {
+				char path[PATH_MAX];
+				char *dot;
+
+				c_strcpy(path, script->path);
+				dot = c_strchr(path, '.');
+				if (dot)
+					*dot = 0;
+
+				xsResult = xsAwaitImport(path, XS_IMPORT_DEFAULT);
+				if (xsTest(xsResult) && xsIsInstanceOf(xsResult, xsFunctionPrototype)) {
+					gSetupPending += 1;
+					xsCallFunction1(xsResult, xsGlobal, xsVar(0));
+				}
 			}
+			script++;
 		}
-		
 		xsCollectGarbage();
 	}
 	xsEndHost(screen->machine);
-	(*screen->start)(screen, 5);
+
+	setStepDone(screen->machine);
 }
 
 #ifdef mxInstrument
```

**Comment by phoddie** [comment]
Setup modules were created to set-up the runtime environment ahead of execution of `main`. They take care of things like initializing the display and connecting to the network. Those things are are done by the host operating system when running on a computer. The documentation alludes to this: "The simulator implicitly performs the work of setup already..".

It should be fine to support `setup/*` modules the simulator too. That can be useful in some scenarios, and having a consistent mechanism makes sense. Your changes above to do that look very reasonable. If you would bundle that into a PR, we can review and merge it. Thanks!

**Comment by phoddie** [comment]
This has been resolved with the PR from @FWeinb (thank you!).
