### ISSUE TITLE
Directory.create always throws 'failed' on ESP32

### ISSUE THREAD

**Issue by cmidgley** [Moddable-OpenSource/moddable#872]
**Build environment:** Linux
**Target device:** ESP32/Heltec_lora_32

**Description**
Attempting to create a directory on ESP32 always fails with exception 'failed' (modFile.c, line 476).  General file I/O works fine.

**Steps to Reproduce**

`main.js`:
```ts
import config from "mc/config";
import { Directory } from "file";

trace(`Creating directory ${config.file.root}test\n`);
Directory.create(config.file.root + "test");
trace("Create complete\n");
```

`manifest.json`:
```json
{
        "include": ["$(MODDABLE)/examples/manifest_base.json",
                "$(MODDABLE)/modules/files/file/manifest.json"],
        "modules": {
                "*": [
                        "./main"
                ]
        }
}
```

**Expected behavior**
The directory should be created.

**Other information**
I have tried with and without the `config.file.root` path, with no change in behavior.  `File` is working fine, this is just `Directory.create` (though I've not yet been able to try `Directory.delete`).

**Comment by cmidgley** [comment]
Closing - was using SPIFFS, which does not support true directories.  For others who may encounter this, if you want sub-directories you need to considering using FAT, or work with fake-paths (slash is a valid character in a filename) on SPIFFS flat file system.

**Comment by wilberforce** [comment]
@cmidgley 

Curious to know what you are using the File system for?

**Comment by cmidgley** [comment]
@wilberforce I've sent you a DM on gitter.
