### ISSUE TITLE
Overflow in timers

### ISSUE THREAD

**Issue by Arorar3** [Moddable-OpenSource/moddable#875]
**Environment**

* Development Board: ESP32
* ESP-IDF version: v4.4
* Moddable SDK version: d085d3a6
* Build System: mcconfig
* Compiler version: xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 5.2.0
* Operating System: Mac
* Using an IDE?: No
* Power Supply: 12V DC
* Router: Mobile Hotspot

**Problem Description**
  
   1. The timer module behaves incorrectly after overflowing variables. The timer behaves incorrectly in two scenarios: 
        1) when the trigger time gets overflow and
        2) when the internal tick variable overflows.  
   2. Timer module behaves as follows when a variable overflows:
       1) the callback gets repeated.
       2) the callback stays uncalled for a while.
   3. Due to repeated callbacks, moddable exhibits the following issues:
      1) Multiple timer callbacks are getting call repeatedly within 1 second.
      2) application gets stuck for a while. 

**Steps to reproduce**

Here are the steps to reproduce the issue in [MODDABLE](https://github.com/Moddable-OpenSource/moddable)

1. In [xsHost.h](https://github.com/Moddable-OpenSource/moddable/blob/public/xs/platforms/esp/xsHost.c), we must declare the OFFSET micro.
![xsHost_H](https://user-images.githubusercontent.com/101744961/158665384-6f32dc34-1e0c-46fe-ab8a-803797c1d1f6.png)

2. In [xsHost.c](https://github.com/Moddable-OpenSource/moddable/blob/public/xs/platforms/esp/xsHost.c), we need to add OFFSET with the current modMilliseconds clock. So that timer module will overflow after 40 secs.
![xsHost_C](https://user-images.githubusercontent.com/101744961/158665661-69d5fd68-ec07-4684-82ee-f6f54ffeac44.png)

3. I took mqttbasic example to produce this timer overflow behavior. In the example, a timer is getting call every 1 second and publishing mqtt request.
![mqttBasic](https://user-images.githubusercontent.com/101744961/158665895-b47afbbc-2bbb-4453-b2c9-aa3f0fd7dbad.png)

**Debug Logs**

1. Continuous callbacks - after 40 secs of running, 31 continuous calls to timer callback functions within 1 second of duration.

<img width="826" alt="continuous_callbacks" src="https://user-images.githubusercontent.com/101744961/158666821-944ba2ca-01d7-4cab-90f7-a909cea2d08f.png">

2. Application getting stuck - After 31 continuos calls  within 1 second, application gets stuck for around 31 seconds and then resumes.

<img width="880" alt="stuck" src="https://user-images.githubusercontent.com/101744961/158667172-0c7de0f9-06b0-43fc-bb57-6355b6072c73.png">

**Analysis:**

1. In [xsHost.c](https://github.com/Moddable-OpenSource/moddable/blob/public/xs/platforms/esp/xsHost.c), **modMilliseconds** API provides the tick to the timer module, which is an **unsigned integer** (0, 4294967295) thus overflows after 49 days, 17 hours and 2 mins. 

![xsHost_C_modMillisecs](https://user-images.githubusercontent.com/101744961/158668235-e1dba072-7b16-493b-a2d8-1a01fb0eab39.png)

However, in the **modTimersExecute** function of [Timer.c](https://github.com/Moddable-OpenSource/moddable/blob/public/modules/base/timer/mc/timer.c) this **modMilliseconds** function gets assigned to **now** variable which is an **signed integer** (-2147483647, +2147483647). 
The timer structure modTimerRecord has a variable **triggerTime**  that also is of type **signed integer**. Both of these will both overflow after 24 days, 20 hours and 31 mins.

![timer_c](https://user-images.githubusercontent.com/101744961/158668393-f9e84651-cd89-48e4-baf8-ac40ed947e4e.png)

 Furthermore, when the timer callback is called at every specified interval, the **triggerTime** is updated and it overflows when it is near to the maximum value of **signed integer** (24 days, 20 hours and 31 mins).  

<img width="1029" alt="triggerTimeUpdate" src="https://user-images.githubusercontent.com/101744961/158668558-bf1981a4-a45d-4223-8b35-ef3d6b7b84c6.png">

2. In the mqttbasic example, timer gets called every 1 second(1000 millisecs) interval. modMilliseconds() provides the current time as time ticks from boot up + offset which is close to **signed integer** overflow limit. After 40 seconds of running when timer executes, it sets the triggertime variable to next interval. At this point triggerTime variable crosses its limit from +2147483647 and goes in negative value. 
After that whenever the **modTimersExecute** function is called, **(walker->triggerTime <= now)** becomes true and the callbacks are repeated.

<img width="1072" alt="callback" src="https://user-images.githubusercontent.com/101744961/158669177-4875ef30-7303-4972-b07f-b9372d29f56f.png">

**Proposed solutions:**
1. The first solution is to put a condition in **modTimersExecute** function while iterating the global timers. The condition is to check the timers when **walker->triggerTime** overflows its range and goes in negatives and **now** does not. And when that situation happens then continue the loop and move to next timer.
<img width="1089" alt="timer_c_solution1" src="https://user-images.githubusercontent.com/101744961/158671007-8199fe09-b036-418b-96a8-029aeb5258c9.png">

2. The second solution is increase the timer variables from integer(32 bits) type to long integer(64 bits) type and postpone this problem to happen to thousand of years.
Code changes are below(attached):

2.1. Change the **modMilliseconds()** to provide current ticks from 32 bits to 64 bits.
![xsHost_c_Sol2](https://user-images.githubusercontent.com/101744961/158671993-48505066-2431-49dc-82dc-6467dfd78791.png)

2.2. Update the **modMilliseconds()** in xsHost.h file.

![xsHost_h_Sol2](https://user-images.githubusercontent.com/101744961/158672220-0b52889e-3254-49d8-8272-8fcb18f888b2.png)

2.3. Change the modTimerRecord structure. Update **triggerTime** variable  from 32 bits integer to 64 bits signed integer. This will increase the structure size to 40  bytes, so we are using #pragma pack(2) to pack structure members with 2 bytes alignment.
![Timer_c_Sol2_StructureChange](https://user-images.githubusercontent.com/101744961/158677264-7e6b569a-27a5-47ce-a2f1-5c1318702131.png)

2.4. Update the **now** variable in **modTimerExecute()** to 64 bits signed integer type.

![Timer_c_Sol2_NowVarChange](https://user-images.githubusercontent.com/101744961/158677390-222c2bdf-996f-4e9d-bf13-386fed727642.png)

2.5. Update the modTimerNext(). Update the **now** and **delta** variables to 64 bits signed integers.
![Timer_c_Sol2_ModTimerNextChange](https://user-images.githubusercontent.com/101744961/158677473-212944ae-b601-4df7-bdf7-0b9ddf3c7ceb.png)

**Debug Logs**
1. [Failure log (moddable)](https://github.com/Moddable-OpenSource/moddable/files/8271950/teraterm_Pub_Moddable.1.log)

**attachment**
[Solution2_CodeDiff.zip](https://github.com/Moddable-OpenSource/moddable/files/8273617/Solution2_CodeDiff.zip)

**Comment by phoddie** [comment]
Thank you for the report, @Arorar3!

The second proposed solution has some issues:

- Increases memory used by each timer
- Increases execution time by promoting 32-bit math to 64-bit math in calculations
- Isn't portable to all targets that use this timer implementation (includes changes only for ESP32)

The first proposed solution has none of these issues and is considerably simpler. If the first proposed solution works in all cases, it isn't clear why the alternative is offered. Is there a known issue with the first proposed solution that the second proposed solution solves?

**Comment by Arorar3** [comment]
Thanks for the response!

The issue happens when **triggerTime** overflows its integer range and goes in negatives and after that whenever the modTimersExecute function is called, condition **(walker->triggerTime <= now)** becomes true and the callbacks are unnecessarily repeated.

With the first proposed solution, it will handle this repeated callbacks scenario but what we have observed that when this overflows happens there are frequent (in 0-2 milliseconds interval) calls to **modTimerExecute()** function for some iterations. That would affect the performance.

To avoid that we have come up with second solution in which we have increased timer variable size from 32 bits to 64 bits so the overflow will occur after thousand of years.
Answering to the concerns you have regarding the second proposed solution.
- Yes, it will increase memory. With the size change in **triggerTime** variable in **modTimerRecord** structure, the structure size was becoming 40 bytes so we have used #pragma pack(2) to pack structure members with 2 bytes alignment. With this each timer will take 2 bytes extra. 
- Yes, it will require some more execution time.
- Yes, it may not be portable to all the targets but with this solution we are bypassing the variables overflow issue and the drawback of first proposed solution where we have observed frequent calls to **modTimerExecute()**.

**Comment by phoddie** [comment]
Thank you for your notes.

> ...the structure size was becoming 40 bytes so we have used #pragma pack(2) to pack structure members with 2 bytes alignment.

This seems likely to break targets that have a 4-byte alignment requirement , including the Xtensa in ESP8266 and lower-performance ARM cores.

It does not appear that there is a viable solution here. The first solution causes unnecessary CPU load; the second has multiple issues, most notably that it is not portable.
