### ISSUE TITLE
mcconfig: command not found error

### ISSUE THREAD

**Issue by sharmisthasg** [Moddable-OpenSource/moddable#88]
I'm using Ubuntu 16.04. I followed all the steps for building and configuring Moddable SDK for ESP32. However, at the final step, I get command not found error for mcconfig.

**Comment by mkellner** [comment]
Hello. Did you add $MODDABLE/build/bin/lin/release to your PATH?

**Comment by Frijol** [comment]
@SharmisthaSG was this your error?

![screen shot 2018-09-13 at 12 15 45 pm](https://user-images.githubusercontent.com/454690/45510390-ea3d0600-b74e-11e8-81cd-d1aec9e1441f.png)

I was able to reproduce a "command not found" from a failure to `cd` into the `examples/helloworld` folder. However, when I used the `mcconfig` command from inside the helloworld folder, it began to run:

![screen shot 2018-09-13 at 12 19 54 pm](https://user-images.githubusercontent.com/454690/45510537-5ddf1300-b74f-11e8-9435-1447500007a9.png)

etc.

I did then run into a different error:

![screen shot 2018-09-13 at 12 20 35 pm](https://user-images.githubusercontent.com/454690/45510657-b0b8ca80-b74f-11e8-831a-995299f389d2.png)

@SharmisthaSG does this help?
@mkellner any suggestions from here?

Thanks!

**Comment by mkellner** [comment]
Is `IDF_PATH` set? That's part of the normal setup for ESP32 development and looks like it is missing from the Getting Started document.

https://docs.espressif.com/projects/esp-idf/en/latest/get-started/index.html#setup-path-to-esp-idf

**Comment by sharmisthasg** [comment]
Hey
@mkellner I tried both your suggestions. It still says command not found. I noticed an error in the previous step (make install) which I had somehow overlooked. Attaching a screenshot of the same. Maybe this can help.

![link](https://user-images.githubusercontent.com/29104739/45572827-15774080-b888-11e8-8bf7-9a9dfab699fc.png)

@Frijol I did check the directory. I was in the correct one.

**Comment by mkellner** [comment]
In `build/makefiles/lin/simulator.mk`,  it looks like `BUILD_DIR` is evaluating to an empty string, causing `TMP_DIR` to become a non-existent path.

Is BUILD_DIR defined in your environment? (ie. `printenv | grep BUILD_DIR`)
If it is defined, it will be used in the .mk file. That is, the assignment to BUILD_DIR is done with the ?= operator which only sets BUILD_DIR if it is not already set.
 `BUILD_DIR ?= $(realpath ../..)`

If BUILD_DIR is not set in your environment, then does realpath work for you? Try `realpath ../..` on the command line. Does it return a path?

**Comment by sharmisthasg** [comment]
realpath ../.. doesn't return any path. And BUILD_DIR isn't set either. How do I resolve this?

**Comment by mkellner** [comment]
Do you have `realpath`? (ie. what does `which realpath` return?)
If you don't have realpath, you can install it.
https://unix.stackexchange.com/questions/101080/realpath-command-not-found
Suggests how to install.
`$ sudo apt-get install realpath`
