### ISSUE TITLE
Application crash without exception - style missing in text

### ISSUE THREAD

**Issue by tony-abraham** [Moddable-OpenSource/moddable#887]
**Build environment:** macOS
**Target device:**  Moddable Two, desktop simulator

**Description**
For a `Text` PIU object without a `style` assigned, if an attempt is made to set the `width`, the application crashes without throwing any exceptions. 
Mcsim crashes with the message "mcsim quit unexpectedly" (screenshot attached); Moddable Two attempts to reboot the application continuously.
It is understood that `Text` object needs a `style` if a `width` has to be set; but shouldn't an exception be thrown before the application crashes in case of a missing style?

**Steps to Reproduce**
Reproduced the issue on the following sample code using `mcconfig -d -m`
```
let application = new Application(null, {
	width: 320, height: 240,
	skin: new Skin({ fill: "white" })
});

/**
 * Setting a width to Text Object without a style causes an application crash without exception.
 * The crash without exception happens only if an attempt to set the width is done. 
 * Setting the height does not cause the crash
 */
let text = new Text(null, {
	//style: new Style({ font: "myFont" }),	
	width: 150, 
	height: 50,
	string: "sample string"
});
application.add(text);
export default application;
```
 
**Expected behavior**
It is understood that the `Text` object needs a `style` if width / string is to be set. 
But, in case of an unforeseen error in an application logic which causes the style not to be set correctly, an attempt to set the width should throw an exception like "style missing in text" . 

**Images**
![image](https://user-images.githubusercontent.com/55189688/160513894-47f23704-95a5-442f-a629-cc325aedb381.png)

**Other information**
1. `Text` Object - Attempting to set a `height` without setting a `style` - does not cause a crash.
2. `Label` Object - Attempting to set a `width` or  `height` without setting a `style` - does not cause a crash

**Comment by phoddie** [comment]
Thank you for the report. The absence of a `layout` should not trigger a crash.

> in case of an unforeseen error in an application logic which causes the style not to be set correctly, an attempt to set the width should throw an exception like "style missing in text" .

Would you please explain how you concluded that throwing an exception from the `Text` constructor is the correct behavior?

For example, this works but would fail if the constructor were to throw in the absence of ` `layout`:

```js
let text = new Text(null, {
	width: 150, 
	height: 50,
	string: "sample string"
});
text.style = new Style({ font: "myFont" });
application.add(text);
```

This comment is unclear and doesn't appear to match the runtime behavior:

```js
 * The crash without exception happens only if an attempt to set the width is done. 
 * Setting the height does not cause the crash
```

For example, this does not crash:

```js
let text = new Text(null, {
	width: 0, 
	height: 50,
	string: "sample string"
});
```

Maybe the comment should be "The crash only occurs when width has a non-zero value"?

**Comment by tony-abraham** [comment]
Thanks for the response. 

Regarding the first point : Yes, I got your point. If the text constructor were to throw an exception, adding a `style` after creating the `Text` object (which works fine today) would also fail. 
The expected behavior should be "The absence of a `style` property should not trigger a crash" (Similar to how `label` behaves today) 

Regarding the comment : Yes, your statement is correct. The crash happens only when the width has a non zero value.
