### ISSUE TITLE
Maps and sets incorrectly distinguish NaN values

### ISSUE THREAD

**Issue by gibson042** [Moddable-OpenSource/moddable#888]
**Environment:** XS 11.6.0 32 4

**Description** XS incorrectly differentiates NaN values in maps and sets.

**Steps to Reproduce**

```js
(new Set([NaN, Number("x"), Math.sqrt(-1), Infinity * 0, Infinity - Infinity])).size // => 2
(new Map([[NaN, true]])).get(Infinity / Infinity) // => undefined
```

**Expected behavior**
All NaN values should be indistinguishable from each other, with the first expression above returning `1` and the second returning `true` because both [Map Objects](https://tc39.es/ecma262/multipage/keyed-collections.html#sec-map-objects) and [Set Objects](https://tc39.es/ecma262/multipage/keyed-collections.html#sec-set-objects) specify that "_distinct [key] values are discriminated using the [SameValueZero](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-samevaluezero) comparison algorithm_", which via [Number::sameValueZero](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-numeric-types-number-sameValueZero) must return **true** when both operands are **NaN**.

**Actual behavior**
XS maps and sets differentiate `NaN` from constructed NaN values.

**Comment by phoddie** [comment]
Thank you!

XS normalizes zero for Map and Set keys here:

https://github.com/Moddable-OpenSource/moddable/blob/40cf4e46b2965b3a5a064b0b8da502750c87d238/xs/sources/xsMapSet.c#L916-L920

Extending that to also normalize NaN gives the expected result:

```c
		else if (XS_NUMBER_KIND == kind) {
			if (slot->value.number == 0)
				slot->value.number = 0;
			else if (c_isnan(slot->value.number))
				slot->value.number = C_NAN;
			sum = *((txU8*)&slot->value.number);
		}
```

Some more careful review and test262 testing will be needed to be sure this is a correct fix.
