### ISSUE TITLE
xsbug not working on esp32-s3

### ISSUE THREAD

**Issue by liurenqiu520** [Moddable-OpenSource/moddable#902]
**Build environment:** macOS
**Target device:** ESP32-S3

**Description**
debug not work

**Steps to Reproduce**
1. Build and install the app using this build command: `mcconfig -d -m -p esp32/esp32s3`
2. set breakpoint
3. debug not work

**Expected behavior**
break

**Other information**
when i changed a esp32 device, debug works. but esp32-s3 device not work aways.

**Comment by mkellner** [comment]
Hello @liurenqiu520, which development board are you using?

**Comment by liurenqiu520** [comment]
@mkellner 
![图像 2](https://user-images.githubusercontent.com/2038316/164150463-0ca548b5-0a7f-44f2-a156-32dc1fa56db4.jpeg)

**Comment by liurenqiu520** [comment]
@mkellner 
![图像 2](https://user-images.githubusercontent.com/2038316/164150639-145b7d8b-c7ec-4853-99bb-c5061bcd6283.jpeg)

**Comment by liurenqiu520** [comment]
@mkellner 
![图像 2](https://user-images.githubusercontent.com/2038316/164151649-f9c6b538-19f6-4cea-be1c-1614178fdcda.jpeg)
<img width="280" alt="QQ20220420-123922@2x" src="https://user-images.githubusercontent.com/2038316/164151665-dafb4454-9621-48f6-92d3-86fb408b17ba.png">

**Comment by mkellner** [comment]
Hello @liurenqiu520, I have pushed some updates for esp32s3 to run on the ESP32-S3-DevKitC.

The pin definitions in `$MODDABLE/build/devices/esp32/targets/esp32s3/manifest.json` may have to be updated for your board.

**Comment by liurenqiu520** [comment]
it works

**Comment by mkellner** [comment]
That's good to hear.
