### ISSUE TITLE
Built-in function %ThrowTypeError% is incorrectly recognized as a constructor

### ISSUE THREAD

**Issue by gibson042** [Moddable-OpenSource/moddable#903]
**Environment:** XS 11.6.0 32 4

**Description**

**Steps to Reproduce**
```js
(function() {
  "use strict";

  const constructibles = [];
  if (isConstructible(Object.getOwnPropertyDescriptor(Function.prototype, "caller").get)) {
    constructibles.push(`Function.prototype "caller" getter`);
  }
  if (isConstructible(Object.getOwnPropertyDescriptor(Function.prototype, "arguments").get)) {
    constructibles.push(`Function.prototype "arguments" getter`);
  }
  if (isConstructible(Object.getOwnPropertyDescriptor(arguments, "callee").get)) {
    constructibles.push(`arguments "callee" getter`);
  }

  return constructibles;

  function isConstructible(fn) {
    try {
      Reflect.construct(function(){}, [], fn);
      return true;
    } catch (err) {
      return false;
    }
  }
})();

// => [`Function.prototype "caller" getter`, `Function.prototype "arguments" getter`, `arguments "callee" getter`]
```

**Expected behavior**
Output should be an empty array.

**Other information**
Per https://tc39.es/ecma262/#sec-built-in-function-objects , "_Built-in [function objects](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#function-object) that are not identified as [constructors](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#constructor) do not implement the [[Construct]] internal method unless otherwise specified in the description of a particular function._" There is no such specification at https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-%throwtypeerror% , so the %ThrowTypeError% built-in function should not have a [[Construct]] method and attempts to construct with it such as in the above code should fail with a TypeError exception per https://tc39.es/ecma262/multipage/reflection.html#sec-reflect.construct .

**Comment by phoddie** [comment]
Thank you for the report. This one has an easy fix (don't set `XS_CAN_CONSTRUCT_FLAG` on `%ThrowTypeError%`. That will be in our next SDK update.
