### ISSUE TITLE
How do I share code with the browser.

### ISSUE THREAD

**Issue by creationix** [Moddable-OpenSource/moddable#91]
I'm writing some generic JS logic in a module that I intend to share with my browser implementation of the same app.  I've hit a very annoying wall.

In the browser, the only supported way currently to import is full relative file paths.  For example in `foo.js`, I need to load `bar.js` using:
```js
import bar from "./bar.js"
```
But on moddable XS, I can only get it to work by doing:
```js
import bar from "bar"
```

The two platforms are mutually exclusive in their support so I can't share the same source between both.

Why doesn't moddable support the more explicit syntax and/or how can I enable it in my build?

**Comment by phoddie** [comment]
How "module name" portion of the import statement (the part in quotes) are interpreted is host dependent. The MDN page, for example, states:

> This is often a relative or absolute path name to the .js file containing the module. Certain bundlers may permit or require the use of the extension; check your environment.

The XS engine implementation does not take a position on how the "module name" should be handled. It defers the to the host. You can provide any behavior you like for your host, including one that matches the browsers. The [XS Platform documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20Platforms.md#modules) describes this is greater detail. An example of one implementation is in the ESP implementations of [`fxFindModule`](https://github.com/Moddable-OpenSource/moddable/blob/09690eb71f6a649708b2e05120470c133b7c2af2/xs/platforms/esp/xsHost.c#L907) and [`fxLoadModule`](https://github.com/Moddable-OpenSource/moddable/blob/09690eb71f6a649708b2e05120470c133b7c2af2/xs/platforms/esp/xsHost.c#L984).
