### ISSUE TITLE
TLS handshake failing on using Application Layer Protocol Negotiation(ALPN)

### ISSUE THREAD

**Issue by barianand7** [Moddable-OpenSource/moddable#916]
#### Environment :
- Moddable version: [b18d0b0](https://github.com/Moddable-OpenSource/moddable/commit/b18d0b012134ef16679b95adb0aa505e4dfb76f7)
- Build System: mcconfig
- Compiler version: Microsoft visual studio C++ framework 
- Operating System: Windows 10

#### Problem Description :
TLS handshake fails on using application layer protocol negotiation(ALPN) as part of the TLS extension. 

#### Expected Behavior:
TLS handshake should work fine even with the ALPN extension enabled.

#### Actual Behavior :
After enabling ALPN extension, moddable breakdown on this point `if (typeof ext == 'string') ext = ext.split(':');`

#### Steps to reproduce :
The problem can be reproduced by using the `httpgets` moddable example application with below modifications mentioned in the Code to reproduce this issue section:
1) Configure the code as per following where the problem is reproduced.
`		secure: {
			protocolVersion: 0x303,
			applicationLayerProtocolNegotiation: "mqtt"				// Adding ALPN 
		}`
2) Add the certificate `"$(MODULES)/crypt/data/ca222"` additionally if it is reported an failure on xsbug.
3) Build and Run the `httpsgets` moddable example application in desktop simulator (mcconfig -d -m -p win)
4) Monitor the failure on xsbug console logs

#### Code to reproduce this issue :

![example_main](https://user-images.githubusercontent.com/96224583/172160732-ddd2c7c2-a050-44bc-b2ee-eb9dac817683.png)
![manifest](https://user-images.githubusercontent.com/96224583/172160751-733e8fb9-90e8-4f96-90cc-098c85134adb.png)

#### Analysis : 
`const ext = session.options[i];`
In SSL_Handshake.js file `ext` is defined as const.
Code `if (typeof ext == 'string') ext = ext.split(':');` has been break down where `const ext` variable tried to update with new value. which causes break issue to establish handshaking

![Issue_xsbug_log](https://user-images.githubusercontent.com/96224583/172160793-70922a76-a2d4-456b-ad67-d5cab2a62430.png)

#### Proposed Solution :

Declare the `const ext` variable with `let ext` instead of `const`  in `ssl_handshake.js` module.
(Problem were not found before Github [commit ](https://github.com/Moddable-OpenSource/moddable/commit/efe5107169243d24c8ec85a9e1523fcba79ec527)).

![SSL_handshake](https://user-images.githubusercontent.com/96224583/172160845-8ac512d1-25e4-494d-ac57-7274e4e84611.png)
![Proposed_Solution_xsbug_log](https://user-images.githubusercontent.com/96224583/172160869-9cb56bb3-e2ac-4658-811b-ee552a85059b.png)

**Comment by phoddie** [comment]
Thank you for the detailed report. We'll resolve this in our next update.

**Comment by phoddie** [comment]
This issue has been resolved by [this commit](https://github.com/Moddable-OpenSource/moddable/commit/00872b1f108b96d422454f6fcd4358410f32bc09). The commit adds support for binary and UTF-8 protocol names. It also changes the way multiple protocols are passed (now an array rather than a single string with separator). The documentation has been updated to reflect these changes.

**Comment by barianand7** [comment]
Thank you for the support.
Issue has been verified and seems resolved with [New commit](https://github.com/Moddable-OpenSource/moddable/commit/00872b1f108b96d422454f6fcd4358410f32bc09)

![ALPN issue resolve](https://user-images.githubusercontent.com/96224583/175861063-4523e896-96dc-4dcf-9642-1ed3dc44bf62.png)
