### ISSUE TITLE
TLS handshake failure with cipher TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256

### ISSUE THREAD

**Issue by barianand7** [Moddable-OpenSource/moddable#918]
## Problem Description

TLS issue observed in Moddable SDK (SSL_Handshake.js) while performing Handshaking with HTTPS server for the cipher suite `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256`. 

**Note:** Many of the servers are not supporting this cipher yet. The specific server used in this case AWS IOT endpoint which supports this cipher.

## Expected Behavior

TLS handshake shall complete successfully while using the cipher `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256` supported by the Moddable SDK.

## Actual Behavior

Handshaking with server  getting failed with the `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256` cipher. The debugger stopped at an exception indicating "Cert: Unsupported algorithm"

## Steps to reproduce

1) Enable only one cipher suite `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256` in ['ssl_ciphersuites.js'](https://github.com/Moddable-OpenSource/moddable/blob/public/modules/crypt/ssl/ssl_ciphersuites.js) while commenting all other cipher suites. This is to ensure, the server must select this expected cipher
2) Update ` Host:  " "` parameter in `main.js` of moddable `httpsget` example  `~\moddable\examples\network\http\httpsget`.  This host should supports `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256` cipher.
3) set the TLS protocol version to be TLS1.2 
4) Build and run the application `mcconfig -d -m`
5) Monitor the debug console and Wireshark terminal (optional).

## Code to reproduce this issue
Moddable example [httpsget](https://github.com/Moddable-OpenSource/moddable/tree/public/examples/network/http/httpsget) with above mentioned modification in the steps to reproduce

![C02B_VS_exampleMain_2](https://user-images.githubusercontent.com/96224583/175305130-7761061e-0940-4b2f-932b-f9823ace7278.png)

![C02b_VS_ssl_ciphersuites](https://user-images.githubusercontent.com/96224583/175225852-920eacc5-bcae-4ad1-829f-028b34fc312a.png)

## Debug

![C02B_xsBug](https://user-images.githubusercontent.com/96224583/175225931-b6cbe722-1f1c-4347-9e39-553b136a86e6.png)

## Analysis :
- Client and server both align on the cipher suite `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256`.
- Server send signature algorithm ID : 1.2.840.10045.4.3.2 (ecdsa-with-SHA256) in the server certificate.
- Signature algorithm is not listed in `ssl_cert.js` file from moddable. 
- Which cause fail handshake with the error `Cert: unsupported algorithm`. 

![C02B_Wireshark_Signaturesend_from_server](https://user-images.githubusercontent.com/96224583/175226018-85771824-bdd7-48f3-98a4-718a5b2dd4bd.png)

![C02B_Wireshark_cipherSuiteSelected](https://user-images.githubusercontent.com/96224583/175226041-ada48886-d4ee-4eb9-aa1a-93dff784c3ec.png)

![C02B_Wireshark_signAlgo](https://user-images.githubusercontent.com/96224583/175226071-56d9927b-b178-4430-8959-f647a6df8a0f.png)

## Wireshark Log :
[ Wireshark Log Link ](https://drive.google.com/drive/folders/1Gnru3UQ26S-xgl1disz0dVGJlhjPMfZ6?usp=sharing)

**Comment by phoddie** [comment]
Unable to reproduce this report. Because no host was provided, I used www.google.com to test. In ssl_ciphersuites.js the available cipher suite list is simplified to provide `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 ` as the only option:

``` js
const supportedCipherSuites = [
	{
		// TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
		value: [0xc0, 0x2b],
		isExportable: false,
		keyExchangeAlgorithm: ECDHE_RSA,
		cipherAlgorithm: AES,
		cipherKeySize: 16,
		cipherBlockSize: 16,
		hashAlgorithm: SHA256,
		hashSize: 32,
		encryptionMode: GCM,
		ivSize: 8,	// explicit nonce size
		saltSize: 4,	// implicit part
	}
];
```

The test uses httpsget example modified to use www.google.com as the host and setting the TLS version to 1.2:

```js
let request = new Request({host: "www.google.com", path: "/", response: String,
		port: 443, Socket: SecureSocket, secure: { trace: true, protocolVersion: 0x303}});
```

The trace from the TLS stack indicates a successful negotiation prior to beginning to output the HTTP headers and body:

```
FINISHED: ECDHE_RSA-AES-GCM-SHA256
```

The server selects the expected cipher suite:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/6856458/175366388-ae9930fd-a110-4323-9b25-9609816dc1bb.png">
