### ISSUE TITLE
Esp32 ble close function wrongly documented

### ISSUE THREAD

**Issue by diogoviannaaraujo** [Moddable-OpenSource/moddable#92]
Hi, in ble documentation is stated that the close function for the BLEServer class is used to terminate a BLE client connection. But as I’ve understood from esp32/modBLEServer.c its actually destroying and freeing all Bluetooth resources.

Here is the esp32 implementation of the close function:

```
void xs_ble_server_close(xsMachine *the)
{
	modBLE *ble = xsmcGetHostData(xsThis);
	if (!ble) return;
	
	xsForget(gBLE->obj);
	xs_ble_server_destructor(gBLE);
	xsmcSetHostData(xsThis, NULL);
}

void xs_ble_server_destructor(void *data)
{
	modBLE ble = data;
	if (!ble) return;
	
	ble->terminating = true;
	for (uint16_t i = 0; i < service_count; ++i)
		if (ble->handles[i][0])
			esp_ble_gatts_delete_service(ble->handles[i][0]);
	esp_ble_gatts_app_unregister(ble->gatts_if);
	if (ble->advertisingData)
		c_free(ble->advertisingData);
	if (ble->scanResponseData)
		c_free(ble->scanResponseData);
	c_free(ble);
	gBLE = NULL;
	
	esp_bluedroid_disable();
	esp_bluedroid_deinit();
	esp_bt_controller_disable();
	esp_bt_controller_deinit();
}
```

I didn’t check the gecko implementation to see if its doing the same but If it is we should change the documentation to the current implementation and create another function like closeConnection(device) and map it to  esp_ble_gatts_close()

**Comment by bfriedkin** [comment]
Diogo -

Thank you for reporting this issue. The close() call does terminate any client connection, but also releases all BLE resources.

We will add a disconnect() call that disconnects the client but leaves the server running and also update the documentation accordingly.

Regards,
Brian

**Comment by diogoviannaaraujo** [comment]
I’ll have some time later in the week so I can play a little bit and see what I can do.

I think the most important is to define who to disconnect so it won’t disconnect a already authorized client.

**Comment by bfriedkin** [comment]
Diogo -

We have added a disconnect() call to the [BLEServer class](
https://github.com/Moddable-OpenSource/moddable/blob/public/modules/network/ble/bleserver.js) and updated the documentation. The updates will be available in our next Open Source release.

Regards,
Brian
