### ISSUE TITLE
Windows Getting Started fails

### ISSUE THREAD

**Issue by AnthonyKNorman** [Moddable-OpenSource/moddable#93]
Issue #1 was the assumptions re downloading into 'Project' folder
Issue #2 was could not find nmake - added path "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\Hostx86\x86" into PATH
issue #3 

C:\Users\antho\moddable\build\makefiles\win>build

C:\Users\antho\moddable\build\makefiles\win>nmake GOAL=debug BUILD_DIR=C:\Users\antho\moddable\build XS_DIR=C:\Users\antho\moddable\xs /c /f C:\Users\antho\moddable\xs\makefiles\win\xsc.mak /s
xsdtoa.c
C:\Users\antho\moddable\xs\platforms\xsPlatform.h(85): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory
NMAKE :  U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\Hostx64\x64\cl.EXE"' : return code '0x2'
Stop.

Should ctype.h be in the Git download?

**Comment by bfriedkin** [comment]
Hello -

Thank you for the follow-up. Looking at the error, I am wondering if you are building from the "Developer Command Prompt for VS 2017" command line console. This is documented in the [Getting Started](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/Moddable%20SDK%20–%20Getting%20Started.md) document in step 5. This command line console sets up additional environment variables when opened, including the path to the toolchain required by the Moddable SDK build. You shouldn't need to explicitly add the path to nmake or any other Visual Studio tools.

Please let us know if building from the "Developer Command Prompt for VS 2017" command line console resolves the build issue.

Thanks,
Brian

**Comment by AnthonyKNorman** [comment]
Hi
D'Oh! Thanks for that. Rule 1 -  read ALL the words!
build has now run.

Latest issue


```
C:\Users\antho\moddable\build\makefiles\win>xsbug
'xsbug' is not recognized as an internal or external command,
operable program or batch file.

```
```
C:\Users\antho\moddable\build\makefiles\win>cd %MODDABLE%\examples\helloworld

C:\Users\antho\moddable\examples\helloworld>mcconfig -d -m -p win
'mcconfig' is not recognized as an internal or external command,
operable program or batch file.

```

```
Path=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\x86;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PuTTY\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;%MODDABLE%\build\bin\win\release;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\Hostx86\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

```

Clearly, the MODDABLE environment variable exists and PATH looks right.
Can you help?

**Comment by bfriedkin** [comment]
Hello -

Let's first make sure that the tools build completed successfully. Navigate to %MODDABLE%\build\bin\win\release and verify that xsbug.exe and mcconfig.bat are in that directory.

If these files exist, then I would suggest editing your %MODDABLE% PATH environment variable entry to exclude the %MODDABLE% variable. When I print my PATH, my %MODDABLE% path entry is a full path without any environment variable. The way the PATH environment variable is interpreted and defined may vary depending on your version of Windows.

So in your PATH environment variable definition, change this:

%MODDABLE%\build\bin\win\release

To this:

C:\Users\antho\moddable\build\win\release

Thanks,
Brian

**Comment by AnthonyKNorman** [comment]
OK, Using the full path in the PATH environment variable definition did the trick.
We have "Hello, world - sample" in the console!
Thanks for all your help. Going to hook up my ESP32 now!
Tony

**Comment by AnthonyKNorman** [comment]
Hi
Sorry, me again.

Now failing to flash the ESP32

```
C:\Users\antho\moddable\examples\helloworld>mcconfig -d -m -p esp32
"# no idf_build_dir - remove .prior"
FC: cannot open C:\USERS\ANTHO\MODDABLE\BUILD\DEVICES\ESP32\XSPROJ\SDKCONFIG.DEFAULT.PRIOR - No such file or folder

        1 file(s) copied.

Press any key to complete build **after** MinGW x32 console window closes...
# cc xsHost.o (strings in flash)
In file included from C:\Users\antho\moddable\xs\sources/xsCommon.h:41:0,
                 from C:\Users\antho\moddable\xs\sources/xsAll.h:41,
                 from C:\Users\antho\moddable\xs\platforms\esp\xsHost.c:38:
C:\Users\antho\moddable\xs\platforms\esp/xsPlatform.h:100:24: fatal error: lwip/netdb.h: No such file or directory
compilation terminated.
NMAKE : fatal error U1077: 'C:\Users\antho\msys32\opt\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.EXE' : return code '0x1'
Stop.

```
The MinGW x32 console window opens and appears to do the build., but after pressing a key I get this>

Any advice please?

**Comment by bfriedkin** [comment]
Hello -

It looks like Espressif updated their all-in-one toolchain for Windows as well as the ESP-IDF, since we last updated our open source repository. We are working through updating our build. 

Thank you for your patience. I will write back here after we've posted an update.

Thanks,
Brian

**Comment by bfriedkin** [comment]
Hello -

We have updated our build to be compatible with the recent Windows all-in-one toolchain and ESP-IDF updates from Espressif. The fixes will be available in our next Open Source release. Please follow the updated Windows setup instructions in our Getting Started document.

Regards,
Brian
