### ISSUE TITLE
manifest.json missing - or documentation misleading?

### ISSUE THREAD

**Issue by ralphwetzel** [Moddable-OpenSource/moddable#938]
Hi!
[Documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/data/data.md#class-crc8-crc16) for `modules/data/crc` states
> Include the module's manifest to use it in a project:

	"include": [
		"$(MODULES)/data/crc/manifest.json"
	]

Yet `$(MODULES)/data/crc/manifest.json` [does not exist](https://github.com/Moddable-OpenSource/moddable/tree/public/modules/data/crc).

Am I missing something?

**Comment by phoddie** [comment]
That looks like an oversight. Thanks for reporting it. We'll add the manifest for the CRC module.

**Comment by ralphwetzel** [comment]
Works as expected now! Thank you!
