### ISSUE TITLE
make.esp32.mk: KILL command for serial2xsbug undefined

### ISSUE THREAD

**Issue by ralphwetzel** [Moddable-OpenSource/moddable#939]
In `make.esp32.mk`, the command to terminate the instances of `serial2xsbug` is assigned to the variable `KILL_SERIAL_2_XSBUG`.

https://github.com/Moddable-OpenSource/moddable/blob/bd4b94f6db2d9789687da8f7d7f0d0f6d4083d0c/tools/mcconfig/make.esp32.mk#L348-L362

For buildtarget `xsbug` yet a variable named `KILL_SERIAL2XSBUG` is referenced; this one is undefined. Consequentially no instance of `serial2xsbug` is terminated.

https://github.com/Moddable-OpenSource/moddable/blob/bd4b94f6db2d9789687da8f7d7f0d0f6d4083d0c/tools/mcconfig/make.esp32.mk#L392-L397

Should be easy to fix!

**Comment by phoddie** [comment]
@ralphwetzel - thank you for the report. As you suggest, the fix is easy. We'll do that for both macOS and Linux.
