### ISSUE TITLE
Cannot parse as BigInt strings prefixed with `+`

### ISSUE THREAD

**Issue by mhofman** [Moddable-OpenSource/moddable#941]
**Build environment:** Linux
**Target device:** XST

**Description**
Spec compliance of `BigInt(integerString)` parsing when string prefixed by `+`

**Steps to Reproduce**
1. `xst -e 'BigInt("+42")'`

**Expected behavior**
`42`

**Actual Behavior**
`SyntaxError: BigInt: Cannot coerce string to bigint`

**Other information**
The [spec](https://tc39.es/ecma262/#sec-stringtobigint) says to try parsing as [`StringIntegerLitteral`](https://tc39.es/ecma262/#prod-StringIntegerLiteral), which includes [`SignedInteger`](https://tc39.es/ecma262/#prod-SignedInteger) which includes [`+ DecimalDigits`](https://tc39.es/ecma262/#prod-DecimalDigits).

All other engines are compliant:
```
$ eshost -se 'BigInt("+42")'
#### engine262, JavaScriptCore, SpiderMonkey, V8
42

#### Moddable XS

SyntaxError: BigInt: Cannot coerce string to bigint
```

**Comment by phoddie** [comment]
Thank for the report. It is a bit surprising that test262 didn't catch this. We might want to propose a new test case there. Fix will be In our next public SDK update.
