### ISSUE TITLE
nodered2mcu creates erroneous code for "is of type" @ switch node

### ISSUE THREAD

**Issue by ralphwetzel** [Moddable-OpenSource/moddable#942]
https://github.com/Moddable-OpenSource/moddable/blob/bd4b94f6db2d9789687da8f7d7f0d0f6d4083d0c/tools/nodered2mcu.js#L663-L670

Line 669 creates code in the form of 
``` javascript
	if (number === typeof value) {
```
which is erroneous: `# Exception: onMessage: get number: undefined variable!`

Line 669 should read
``` javascript
	case "number":
	case "boolean":
	[...]
	case "null":
==>		test = `"${config.v}" === typeof value`;
		break;
```

**Comment by phoddie** [comment]
Thank you for the report! Your proposed fix looks good. I'll get that integrated.
