### ISSUE TITLE
LED not blinking on ESP32C3

### ISSUE THREAD

**Issue by louisvangeldrop** [Moddable-OpenSource/moddable#948]
**Build environment:** Windows,
**Target device:** ESP32-C3 NodeMCU devkit

**Description**
LED not blinking using the Cold White LED-pin:19 running the Blink example from the moddable\ecamples library

![image](https://user-images.githubusercontent.com/10716245/197624849-8f76baf3-d1f6-4f1d-8574-1078a70b5005.png)

Arduino example:

![image](https://user-images.githubusercontent.com/10716245/197624443-e8af6fc0-010c-4f71-b1bd-3aec43baeb47.png)

The Arduino example shows a blinking LED.

**Comment by mkellner** [comment]
Thank you for the bug report.

The ESP32C3 defaults to using pins 18 and 19 for USB.
Setting the function of the pin to GPIO wasn't enough, but resetting the pin before setting the function clears the USB feature.

I have also added some targets for the AI Thinker ESP32 C3-32S-Kit. `esp32/c3_32s_kit` is for the 4MB version and `esp32/c3_32s_kit_2m` is for the 2MB version.

**Comment by louisvangeldrop** [comment]
@mkellner 
Thank you for the quick response and the fix. It works now.

**Comment by louisvangeldrop** [comment]
I have tried the io-blink sample with this board and do get the following error:

![image](https://user-images.githubusercontent.com/10716245/197871046-d19098d3-e3aa-4014-bed6-503cefcbd657.png)

**Comment by phoddie** [comment]
This appears to be an unrelated issue. If that is correct, please close this issue and open a new one. Thank you.
