### ISSUE TITLE
io digital blink sample not working on esp32_c3_32s_kit

### ISSUE THREAD

**Issue by louisvangeldrop** [Moddable-OpenSource/moddable#949]
I have tried the io-blink sample with the esp32_c3_32s_kit board and do get the following error:

![image](https://user-images.githubusercontent.com/10716245/197871046-d19098d3-e3aa-4014-bed6-503cefcbd657.png)

**Comment by mkellner** [comment]
Please try with the latest release.

**Comment by louisvangeldrop** [comment]
It works now. Thanks for the update
