### ISSUE TITLE
pico/captouch & pico/ili9341 fail to build

### ISSUE THREAD

**Issue by ralphwetzel** [Moddable-OpenSource/moddable#952]
Both platforms fail to build w/
`### Error: '$(BUILD)/devices/$(PLATFORM)/targets/$(SUBPLATFORM)/host/provider': directory not found!`

The source of the error seems to be this manifest:
https://github.com/Moddable-OpenSource/moddable/blob/3c7f16c3c113aefa907b79a1884ab09a5b8a9ab9/modules/io/manifests/pico/manifest.json#L43-L47

As stated, those are the only Pico targets lacking the definition of `host/provider.js`.

**Comment by phoddie** [comment]
Fix committed!

**Comment by ralphwetzel** [comment]
Confirmed! 👍
