### ISSUE TITLE
xsbug not opening for QT-Py ESP32-S3

### ISSUE THREAD

**Issue by danfinlay** [Moddable-OpenSource/moddable#960]
**Build environment:** macOS Monterey 12.1 on a M1 Macbook Air
**Target device:** [Adafruit QT-Py ESP32-S3](https://learn.adafruit.com/adafruit-qt-py-esp32-s3)

Seems kinda similar to #902, and it seems esp32s3 is a bit on the bleeding edge here.

**Description**
When I use mcconfig with this board, it doesn't successfully open xsbug, so I can't really debug issues with it.

**Steps to Reproduce**
0. Followed [this suggestion](https://github.com/Moddable-OpenSource/moddable/issues/70) to get BLE working.
1. Build and install the app using this build command: `IDF_PATH=$HOME/esp32/esp-idf UPLOAD_PORT=/dev/cu.usbmodem1101 mcconfig -d -m -p esp32/esp32s3 -t xsbug`
2. Notice xsbug doesn't oepn

**Expected behavior**
xsbug to open

**Comment by phoddie** [comment]
The ESP32-S3 board I use works fine with xsbug. It has two USB ports. Both work for flashing firmware but only one works with xsbug. Is it possible you have the same situation? Which board are you using?

**Comment by phoddie** [comment]
Oops! You mentioned the board in your post. I think @mkellner might have one of those to try to help.

**Comment by mkellner** [comment]
Hello.

I do not have a QT-Py ESP32-S3 yet.

Looking at your command:
`IDF_PATH=$HOME/esp32/esp-idf UPLOAD_PORT=/dev/cu.usbmodem1101 mcconfig -d -m -p esp32/esp32s3 -t xsbug`

Try it without the `-t xsbug`. That bypasses the build and just tries to launch xsbug without building or installing an app.

`mcconfig -d -m -p esp32/esp32s3` should build and install then launch xsbug (assuming there is no problem).

If that does not work for you, please add `VERBOSE=1` to the beginning of your build line to see more build output. If the output doesn't provide any clues, please post it here for more analysis.

**Comment by mkellner** [comment]
Looking further at this, I think that running xsbug over the built-in serial port will require some development. My current understanding is that TinyUSB is used to create a serial endpoint.

To use the debugger now, with a USB to tty adapter, you can connect it to the A0 and A1 pins (U1RXD and U1TXD).

![image](https://user-images.githubusercontent.com/6822704/200464193-3b476b97-eb96-43d1-873f-a5c7d2864260.png)

(`https://learn.adafruit.com/assets/112464`)

In `$MODDABLE/build/devices/esp32/xsProj-esp32s3/main/main.c` around line 98, you'll need to change the defines for the debugger serial port to:

```
    #define USE_UART    UART_NUM_1
    #define USE_UART_TX 17
    #define USE_UART_RX 18
```

I will verify that works when my device arrives.

**Comment by danfinlay** [comment]
Awesome, that's some great next steps, thank you!

**Comment by danfinlay** [comment]
I removed that tail of the command (I had added it in trying to fix this issue). xsbug still doesn't open, probably the lack of tty comms like you said. I do get _some kind of logs_ out of it, they look like this:

```
Writing at 0x0009babb... (91 %)
Writing at 0x000a1011... (95 %)
Writing at 0x000a684b... (100 %)
Wrote 631376 bytes (386275 compressed) at 0x00010000 in 6.6 seconds (effective 764.0 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 123...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (123 compressed) at 0x00008000 in 0.1 seconds (effective 390.3 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
Executing action: flash
Running ninja in directory /Users/danfinlay/Documents/moddable/build/tmp/esp32/esp32s3/debug/MY_PROJECT_NAME/xsProj-esp32s3/build
Executing "ninja flash"...
Done
ESP-ROM:esp32s3-20210327
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0xa (SPI_FAST_FLASH_BOOT)
Saved PC:0x403cdf0b
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x13c
load:0x403c9700,len:0xbb0
load:0x403cc700,len:0x285c
entry 0x403c98bc
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0xa (SPI_FAST_FLASH_BOOT)
Saved PC:0x4206797e
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x13c
load:0x403c9700,len:0xbb0
load:0x403cc700,len:0x285c
```

**Comment by danfinlay** [comment]
I tried connecting a tty programmer as @mkellner suggested, but it seems to stall out for me at:
> # starting xsbug

**Comment by mkellner** [comment]
My apologies, set the environment variable DEBUGGER_PORT to the device of the tty programmer. For example:
```
banana:net mkellner$ ls /dev/cu.*
/dev/cu.BLTH			/dev/cu.URT2
/dev/cu.Bluetooth-Incoming-Port	/dev/cu.usbserial-015F95C2
/dev/cu.URT1
banana:net mkellner$ export DEBUGGER_PORT=/dev/cu.usbserial-015F95C2
```

The do the mcconfig command.

**Comment by danfinlay** [comment]
Oh! Wow thank you for the super prompt reply!

**Comment by danfinlay** [comment]
This is all instead of the `UPLOAD_PORT`? I take it that wouldn't be used anymore (I wouldn't connect the device by two USB cables?)

**Comment by mkellner** [comment]
In addition to the UPLOAD_PORT. By default, the DEBUGGER_PORT is set to the UPLOAD_PORT, but it can be independent for devices that are programmed over a different port than the debugger port. Yes, two USB cables.

**Comment by danfinlay** [comment]
I've set both, but same stalled "starting xsbug" message.

You don't mean I should connect to both usb ports, right? (both the QtPy and the usb=>tty programmer)? I'm currently only connected to the usb=>tty.

**Comment by mkellner** [comment]
I've had devices where I have both usb ports connected, sometimes even three with a JTAG. You'll need some sort of power going to the QtPy. The easiest is to have the two cables connect.

**Comment by danfinlay** [comment]
ok, easy enough to try!

**Comment by danfinlay** [comment]
(I was running power from the programmer to the qtpy, it lit up, but maybe it also needs data?)

**Comment by mkellner** [comment]
If you connect a serial monitor tool to the tty instead of xsbug and reset the device, you should see some `<xsbug>` connect messages. If, after a short while, xsbug doesn't respond, the app will continue without xsbug.

I checked my order status and what do you know? My QtPy in my mailbox. Let me grab it and spend some quality time with it tonight.

**Comment by danfinlay** [comment]
So I've connected two USBs to the programmer and the qtpy directly, but getting the same result. Over the moon that you actually got one and are playing with it. It's a really delightfully small & cheap device! I could see throwing it in a lot of projects.

Here's my current setup, just for color:
<img width="744" alt="Screen Shot 2022-11-12 at 5 11 27 PM" src="https://user-images.githubusercontent.com/542863/201500781-20d3c216-2b09-4ae1-b075-1f00dca09e21.png">

**Comment by danfinlay** [comment]
Where I'm at: https://github.com/danfinlay/smart-diaper/tree/advice-1306886011

You can just modify the `build.sh` script to include the correct device ports for your debugger and upload ports. Then `./build.sh` is the command I've been running to try to install it.

**Comment by danfinlay** [comment]
Ok  didn't get to try properly again til now.

I am now getting this output:
```
# starting xsbug
grep: /Users/danfinlay/Documents/moddable/build/tmp/esp32/esp32s3/debug/smartdiaper/xsProj-esp32s3/flashOutput: No such file or directory
make: *** [xsbug] Error 1
```

**Comment by mkellner** [comment]
The latest release (3.5.0) of the Moddable SDK includes experimental support for installation and debugging over USB, including the QTPyS3.

Please see the discussion at #971 for details.
