### ISSUE TITLE
Example wifi-config throws "invalid color" exception

### ISSUE THREAD

**Issue by rei-vilo** [Moddable-OpenSource/moddable#967]
**Build environment:** macOS
**Target device:** Moddable Two, both board and simulation

**Description**

Example wifi-config crashes with "invalid color".

> /Users/USER/Projects/moddable/modules/piu/All/piuColor.c (147) # Break: Skin: invalid color!

**Steps to Reproduce**

1. Command line

```
cd /Users/USER/Projects/moddable/examples/piu/wifi-config
% mcconfig -d -m -p sim/moddable_two
% mcconfig -d -m -p esp32/moddable_two
```

3. The screen displays a list of SSIDs. 
4. Selecting one crashes with the message displayed above.

**Expected behavior**
No error message

**Images**

<img width="872" alt="Capture 2022-11-27 à 20 19 56" src="https://user-images.githubusercontent.com/951776/204155467-1bc3f8a7-f450-4d8a-a614-97f061ee9ec9.png">

**Other information**

Thank you!

**Comment by phoddie** [comment]
Thanks for the report. Somehow this got broken along the way. It will be fixed in the December Moddable SDK release. The change is to add a `color` property to the style in line 28 of `$MODDABLE/examples/piu/wifi-config/assets.js`:

```js
const OpenSans20 = Style.template({ font: "20px Open Sans", color: BLACK, vertical: "middle", horizontal: "left" });
```

**Comment by rei-vilo** [comment]
Strange, there is already a `OpenSans20` constant defined. 

https://github.com/Moddable-OpenSource/moddable/blob/758b624dc985362c77cd283739bec7f87bc28ac2/examples/piu/wifi-config/assets.js#L26

The edited code...

```
const OpenSans20 = Style.template({ font: "20px Open Sans", vertical: "middle", horizontal: "left" });
const OpenSans20 = Style.template({ font: "20px Open Sans", color: BLACK, vertical: "middle", horizontal: "left" });
```

results in an error.

```
/Users/USER/Projects/moddable/examples/piu/wifi-config/assets.js:29: error: duplicate variable OpenSans20!
```

**Comment by rei-vilo** [comment]
Great, it works fine now.
