### ISSUE TITLE
Error in "clut" example

### ISSUE THREAD

**Issue by AnthonyKNorman** [Moddable-OpenSource/moddable#97]
Hi
I get this error when trying to run the 'clut' example on ESP8266
```bash
C:\Users\antho\moddable\modules\files\resource\Resource.c (43) # Break: Resource: Resource not found: gray.cct!```
I couldn't work out how to fix this one.
Tony

**Comment by phoddie** [comment]
Good news. The color table (CLUT) examples work again! See release notes for [October 20, 2020](https://github.com/Moddable-OpenSource/moddable/releases/tag/OS201020).
