### ISSUE TITLE
xsbug locate source has bad .js filter on Linux

### ISSUE THREAD

**Issue by tve** [Moddable-OpenSource/moddable#988]
**Build environment:** Arch Linux

**Description**
When xsbug can't locate a source file due to directory path mismatch since compilation it has a "locate" button which brings up a file browser/selector. This selector ostensibly filters for .js files but that appears broken.

**Steps to Reproduce**
1. Build an example project using docker, which causes paths to differ from the host
2. Start xsbug and load the app, e.g. esp32
3. xsbug comes up and tries to show /data/main.js, there's a locate button, use that and try to find the file

Here's xsbug:
![image](https://user-images.githubusercontent.com/39480/207779852-e758b0eb-3b9d-434b-a0bb-315bcaaf5b0d.png)

So far so good, the locate button brings up this file dialog, which I have open on the source directory:
![image](https://user-images.githubusercontent.com/39480/207779958-0fefb4cd-cb1c-4a05-9428-3a84f2759875.png)

Notes:
- the bug is that `main.js` does not appear
- `ls` in that dir shows: `foo.js  js  main.js  manifest.json`
- I created `js` and `foo.js` after seeing that `main.js` doesn't appear
- the filter at the bottom-right says `js`, I wonder whether it should say `.js`, it's ominous that the only file shown is the one called exactly `js`...
- I assume you can create the issue by moving the source files after building the image

**Comment by phoddie** [comment]
> Build an example project using docker, which causes paths to differ from the host
>
> I assume you can create the issue by moving the source files after building the image

Please provide steps to reliably  reproduce the issue without docker. Thank you.

**Comment by tve** [comment]
STR on Linux:
- Build a project that produces an error in xsbug, for example the drivers/lora example
- xsbug shows the error at the bottom (`/home/sw/moddable/moddable/examples/drivers/lora/main.js (26) # Break: main: get device: undefined variable!`) and the source file
- Rename trhe source directory, e.g., `mv lora lora2`
- the source file immediately disappears from xsbug and you get a "locate" button
- hit the button a file browser shows up, navigate to the `lora2` dir
- the source file `main.js` is not visible in the file browser

**Comment by phoddie** [comment]
Thank you for the updated steps. We'll take a look.

**Comment by phoddie** [comment]
This has been fixed by [this commit](https://github.com/Moddable-OpenSource/moddable/commit/86e1a62527bad2306991b822509c1cdaf8634254). We had previously disabled the file filter on Windows and macOS. That's now been appleid to Linux as well.
