### ISSUE TITLE
Socket error: -1 on MQTT Connection

### ISSUE THREAD

**Issue by diogoviannaaraujo** [Moddable-OpenSource/moddable#994]
**Build environment:** macOS
**Target device:** ESP32

**Description**
When trying to connect to AWS IoT services using custom authenticator connection fails with error -1

**Steps to Reproduce**
Created a custom authenticator on AWS IoT service
Verified it working by using mosquitto client:
```
mosquitto_pub -p 443 -i 'clientid1234' -h 'xxxxxxx-ats.iot.us-east-1.amazonaws.com' --cafile AmazonRootCA1.pem --tls-alpn mqtt -u 'username?x-amz-customauthorizer-name=MyCustomAuthorizer' -P 'MTIzNA==' -t customauthtesting -m "Hello World!"
```
It connects and publish a message successfully.

But when trying to connect on moddable mqtt client using:
```
    connection = new MQTT({
        host: "xxxxxxxxx-ats.iot.us-east-1.amazonaws.com",
        id: "clientid1234",
        username: "username?x-amz-customauthorizer-name=MyCustomAuthorizer",
        password: "MTIzNA==",
        port: 443,
        Socket: SecureSocket,
        timeout: 60000,
        secure: {
          cache: false,
          applicationLayerProtocolNegotiation: "mqtt",
          protocolVersion: 0x303,
          certificate: new Resource("AmazonRootCA1.der"),
          verify: true,
          trace: true,
        },
      })
```

I get an error
`MQTT FAIL: socket error -1`

I can provide the complete host url if needed for testing

**Expected behavior**
Expect to connect and/or give a more meaningful error code

Edit:
Using trace option I was able to get TLS negotiation logs:

```
> clientHello.packetize
>> handshakeProtocol.packetize
>>> recordProtocol.packetize
>>>> tlsPlainText.packetize
>>>>> tlsCompressed.packetize
>>>>>> tlsCipherText.packetize
> recordProtocol.unpacketize
>> tlsCipherText.unpacketize
>>> tlsCompressed.unpacketize
>>>> tlsPlainText.unpacketize
>>>>> handshakeProtocol.unpacketize
>>>>>> serverHello.unpacketize
> recordProtocol.unpacketize
>> tlsCipherText.unpacketize
>>> tlsCompressed.unpacketize
>>>> tlsPlainText.unpacketize
>>>>> handshakeProtocol.unpacketize
>>>>>> certificate.unpacketize
> recordProtocol.unpacketize
>> tlsCipherText.unpacketize
>>> tlsCompressed.unpacketize
>>>> tlsPlainText.unpacketize
>>>>> handshakeProtocol.unpacketize
>>>>>> serverHelloDone.unpacketize
> clientKeyExchange.packetize
>> handshakeProtocol.packetize
>>> recordProtocol.packetize
>>>> tlsPlainText.packetize
>>>>> tlsCompressed.packetize
>>>>>> tlsCipherText.packetize
> changeCipherSpec.packetize
>> recordProtocol.packetize
>>> tlsPlainText.packetize
>>>> tlsCompressed.packetize
>>>>> tlsCipherText.packetize
> finished.packetize
>> handshakeProtocol.packetize
>>> recordProtocol.packetize
>>>> tlsPlainText.packetize
>>>>> tlsCompressed.packetize
>>>>>> tlsCipherText.packetize
> recordProtocol.unpacketize
>> tlsCipherText.unpacketize
>>> tlsCompressed.unpacketize
>>>> tlsPlainText.unpacketize
>>>>> changeCipherSpec.unpacketize
> recordProtocol.unpacketize
>> tlsCipherText.unpacketize
>>> tlsCompressed.unpacketize
>>>> tlsPlainText.unpacketize
>>>>> handshakeProtocol.unpacketize
>>>>>> finished.unpacketize
FINISHED: RSA-AES-CBC-SHA1
> recordProtocol.packetize
>> tlsPlainText.packetize
>>> tlsCompressed.packetize
>>>> tlsCipherText.packetize
> recordProtocol.unpacketize
>> tlsCipherText.unpacketize
>>> tlsCompressed.unpacketize
>>>> tlsPlainText.unpacketize
>>>>> alert.unpacketize
SSL: close notify
MQTT FAIL: socket error -1
```

**Comment by phoddie** [comment]
The TLS connection succeeded. That's visible in your trace `FINISHED: RSA-AES-CBC-SHA1`.

The remote endpoint disconnects almost immediately. The MQTT login is the first operation after the TLS connection is established. Comparing your call to the constructor with the [documentation](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/network/network.md#constructordictionary-8) shows a possibly relevant difference. You are passing the user name with the `username` property but the MQTT implementation expects it on the `user` property.

> Expect to connect and/or give a more meaningful error code

Understand that remote TLS endpoints seldom give meaningful error messages. This seems to be a practice to avoid giving an attacker information that might help them.

**Comment by diogoviannaaraujo** [comment]
Hmm got it, so it's not a TLS issue. 
The meaningful error code was only to fill something on the expected behavior, I understand that is not possible sometimes.

The user one was a good catch, switched and now im getting the disconnection after the onReady, so that problem is fixed, now there is another one, probably some auth config.

Thanks again phoddie!
